//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsServerControls
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        protected global::System.Web.UI.WebControls.PlaceHolder phMessage;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.TextBox txtAuthor;
        protected global::System.Web.UI.WebControls.DropDownList ddlGenre;
        protected global::System.Web.UI.WebControls.TextBox txtYear;
        protected global::System.Web.UI.WebControls.RadioButtonList rblFormat;
        protected global::System.Web.UI.WebControls.CheckBoxList cblTags;
        protected global::System.Web.UI.WebControls.RadioButton rbAvailable;
        protected global::System.Web.UI.WebControls.RadioButton rbReserved;
        protected global::System.Web.UI.WebControls.CheckBox chkInStock;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.LinkButton lnkClear;
        protected global::System.Web.UI.WebControls.ImageButton ibSave;
        protected global::System.Web.UI.WebControls.GridView gvBooks;
    }
}
