using System;
using Xunit;

namespace System.Web.Tests
{
    // Tier-5b: GridView data binding + rendering.
    //   * AutoGenerateColumns over a DataTable: a <table> with a header row + one row per record,
    //     correct column/row/cell counts, header rendered as <th>.
    //   * Explicit BoundField (DataField): only the declared columns render, with the cell values.
    //   * Paging + sort command via the public API (same HandleSort/HandlePage path that a
    //     "Sort$"/"Page$" IPostBackEventHandler postback drives).
    // Driven INSIDE the ALC. Deterministic.
    public class GridViewTests
    {
        private static SystemWebUnderTest Web => SystemWebUnderTest.Instance;

        [Fact]
        public void AutoGenerateColumnsOverDataTableRendersTable()
        {
            object[] r = (object[])Web.RunInAlc("System.Web.Tests.DataBindingWorker", "GridViewAutoGenerateDataTable");

            Assert.Equal(3, (int)r[0]);                 // 3 data rows
            Assert.True((bool)r[1], "GridView should render a <table>");
            Assert.True((bool)r[2], "auto-generated header should contain 'Name'");
            Assert.True((bool)r[3], "auto-generated header should contain 'Dept'");
            Assert.True((bool)r[4], "cell value 'Carol' should render");
            Assert.Equal(3, (int)r[5]);                 // header row: 3 columns
            Assert.Equal(3, (int)r[6]);                 // first data row: 3 cells
            Assert.True((bool)r[7], "header cells should render as <th>");
        }

        [Fact]
        public void BoundFieldRendersOnlyDeclaredColumns()
        {
            object[] r = (object[])Web.RunInAlc("System.Web.Tests.DataBindingWorker", "GridViewBoundField");

            Assert.Equal(2, (int)r[0]);                 // 2 data rows
            Assert.Equal(2, (int)r[1]);                 // 2 header cells (only the bound fields)
            Assert.True((bool)r[2], "BoundField HeaderText 'Employee' should render");
            Assert.True((bool)r[3], "BoundField HeaderText 'Department' should render");
            Assert.True((bool)r[4], "Dept cell value 'Eng' should render");
            Assert.False((bool)r[5], "Id is not bound, so its value should NOT render as a cell");
            Assert.Equal("Alice", (string)r[6]);        // first row, first bound cell
        }

        [Fact]
        public void PagingAndSortCommandReflowData()
        {
            object[] r = (object[])Web.RunInAlc("System.Web.Tests.DataBindingWorker", "GridViewSortPage");

            Assert.Equal(2, (int)r[0]);                 // page 0 shows PageSize (2) of 5 rows
            Assert.Equal(3, (int)r[1]);                 // PageCount = ceil(5/2)
            Assert.Equal("1", (string)r[2]);            // page 0 first Id
            Assert.Equal("3", (string)r[3]);            // page 1 first Id after SetPageIndex(1)
            Assert.Equal(2, (int)r[4]);                 // still binds a full page after Sort
            Assert.Equal("Name", (string)r[5]);         // Sort recorded the expression
            Assert.Equal("Ascending", (string)r[6]);    // and the direction
            Assert.Equal(0, (int)r[7]);                 // Sort resets PageIndex to 0
        }
    }
}
