using Mono.Cecil;
using System.Globalization;
using System.Text;

namespace ExtractApi;

/// <summary>
/// Emits a compilable C# skeleton from metadata. Every body is
/// `throw new NotImplementedException()`. One file per namespace.
/// </summary>
internal static class StubEmitter
{
    public static int Emit(List<TypeDefinition> allVisible, string outDir)
    {
        // Top-level types only; nested are emitted within their declaring type.
        var topLevel = allVisible.Where(t => !t.IsNested).ToList();

        var order = new List<string>();
        var buckets = new Dictionary<string, List<TypeDefinition>>(StringComparer.Ordinal);
        foreach (var t in topLevel)
        {
            string ns = t.Namespace ?? "";
            if (!buckets.TryGetValue(ns, out var list))
            {
                list = new List<TypeDefinition>();
                buckets[ns] = list;
                order.Add(ns);
            }
            list.Add(t);
        }

        int files = 0;
        foreach (var ns in order)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> clean-room System.Web API skeleton.");
            sb.AppendLine("// Bodies are NotImplementedException; this proves signature completeness only.");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine();

            string indent;
            if (ns.Length == 0)
            {
                indent = "";
            }
            else
            {
                sb.Append("namespace ").Append(ns).AppendLine();
                sb.AppendLine("{");
                indent = "    ";
            }

            foreach (var t in buckets[ns])
                EmitType(sb, t, indent);

            if (ns.Length != 0)
                sb.AppendLine("}");

            string fileName = (ns.Length == 0 ? "_Global" : ns) + ".cs";
            File.WriteAllText(Path.Combine(outDir, fileName), sb.ToString());
            files++;
        }
        return files;
    }

    private static void EmitType(StringBuilder sb, TypeDefinition t, string indent)
    {
        string kind = Model.KindOf(t);
        switch (kind)
        {
            case "enum": EmitEnum(sb, t, indent); return;
            case "delegate": EmitDelegate(sb, t, indent); return;
        }

        bool isInterface = t.IsInterface;
        bool isStatic = t.IsAbstract && t.IsSealed && !isInterface;

        // ---- declaration line ----
        sb.Append(indent).Append(Model.TypeAccessibility(t));
        if (isStatic) sb.Append(" static");
        else if (kind == "class")
        {
            if (t.IsAbstract) sb.Append(" abstract");
            else if (t.IsSealed) sb.Append(" sealed");
        }
        sb.Append(kind == "struct" ? " struct " : isInterface ? " interface " : kind == "class" ? " class " : " class ");
        sb.Append(Model.DisplayName(t));

        // base list (not for static classes)
        var bases = new List<string>();
        if (!isStatic)
        {
            string bt = Model.BaseTypeForJson(t); // empty for object/value/iface
            if (bt.Length > 0) bases.Add(Naming.Stub(t.BaseType!));
            foreach (var i in t.Interfaces)
                if (IsVisibleInterface(i.InterfaceType)) bases.Add(Naming.Stub(i.InterfaceType));
        }
        if (bases.Count > 0) sb.Append(" : ").Append(string.Join(", ", bases));

        EmitGenericConstraints(sb, t.GenericParameters);
        sb.AppendLine();
        sb.Append(indent).AppendLine("{");
        string inner = indent + "    ";

        // ---- constructors ----
        if (!isStatic && !isInterface)
        {
            int emitted = 0;
            foreach (var m in t.Methods.Where(m => m.IsConstructor && !m.IsStatic && Model.IsMemberVisible(m)))
            {
                EmitConstructor(sb, t, m, inner);
                emitted++;
            }
            // If the only ctor(s) were internal (stripped from the ref assembly), no ctor remains and C#
            // would synthesize a public default ctor that cannot chain to a base lacking a parameterless ctor.
            // Emit a non-public ctor so the type stays correctly non-constructable and the base chains.
            if (emitted == 0 && kind == "class")
            {
                string? baseCall = BaseCtorCall(t);
                sb.Append(inner).Append("internal ").Append(Naming.StripArity(t.Name)).Append("()");
                if (baseCall != null) sb.Append(" : ").Append(baseCall);
                sb.AppendLine(" { throw new global::System.NotImplementedException(); }");
            }
        }

        // ---- methods ----
        foreach (var m in t.Methods.Where(Model.IsRealMethod).Where(Model.IsMemberVisible))
            EmitMethod(sb, t, m, inner, isInterface);

        // ---- properties ----
        foreach (var p in t.Properties)
            EmitProperty(sb, t, p, inner, isInterface);

        // ---- events ----
        foreach (var e in t.Events)
            EmitEvent(sb, t, e, inner, isInterface);

        // ---- fields ----
        foreach (var f in t.Fields.Where(Model.IsFieldVisible))
            EmitField(sb, f, inner);

        // ---- nested types ----
        foreach (var nt in t.NestedTypes.Where(Program.IsVisible))
            EmitType(sb, nt, inner);

        sb.Append(indent).AppendLine("}");
    }

    private static void EmitEnum(StringBuilder sb, TypeDefinition t, string indent)
    {
        sb.Append(indent).Append(Model.TypeAccessibility(t)).Append(" enum ").Append(t.Name);
        var underlying = t.Fields.FirstOrDefault(f => f.Name == "value__")?.FieldType;
        if (underlying != null && underlying.FullName != "System.Int32")
            sb.Append(" : ").Append(Naming.Stub(underlying));
        sb.AppendLine();
        sb.Append(indent).AppendLine("{");
        string inner = indent + "    ";
        foreach (var f in t.Fields.Where(f => f.IsLiteral && f.HasConstant))
        {
            sb.Append(inner).Append(Naming.Ident(f.Name)).Append(" = ")
              .Append(Convert.ToString(f.Constant, CultureInfo.InvariantCulture)).AppendLine(",");
        }
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitDelegate(StringBuilder sb, TypeDefinition t, string indent)
    {
        var invoke = t.Methods.FirstOrDefault(m => m.Name == "Invoke");
        sb.Append(indent).Append(Model.TypeAccessibility(t)).Append(" delegate ");
        sb.Append(invoke != null ? Naming.Stub(invoke.ReturnType) : "void").Append(' ');
        sb.Append(Model.DisplayName(t));
        sb.Append('(');
        if (invoke != null) sb.Append(RenderParams(invoke.Parameters));
        sb.Append(')');
        EmitGenericConstraints(sb, t.GenericParameters);
        sb.AppendLine(";");
    }

    private static void EmitConstructor(StringBuilder sb, TypeDefinition t, MethodDefinition m, string indent)
    {
        sb.Append(indent).Append(Model.MemberAccessibility(m)).Append(' ');
        sb.Append(Naming.StripArity(t.Name)).Append('(').Append(RenderParams(m.Parameters)).Append(')');
        string? baseCall = BaseCtorCall(t);
        if (baseCall != null) sb.Append(" : ").Append(baseCall);
        sb.AppendLine(" { throw new global::System.NotImplementedException(); }");
    }

    // If the base type has no accessible parameterless ctor, synthesize a base(...) call.
    private static string? BaseCtorCall(TypeDefinition t)
    {
        var baseRef = t.BaseType;
        if (baseRef == null) return null;
        TypeDefinition? baseDef;
        try { baseDef = baseRef.Resolve(); } catch { baseDef = null; }
        if (baseDef == null) return null; // external base — assume parameterless ctor exists

        var ctors = baseDef.Methods
            .Where(c => c.IsConstructor && !c.IsStatic)
            .Where(c => c.IsPublic || c.IsFamily || c.IsFamilyOrAssembly)
            .ToList();
        if (ctors.Count == 0) return null; // no accessible ctor info; let compiler try default
        if (ctors.Any(c => c.Parameters.Count == 0)) return null; // parameterless exists -> implicit

        // pick the ctor with fewest params and no by-ref params
        var chosen = ctors
            .Where(c => c.Parameters.All(p => p.ParameterType is not ByReferenceType))
            .OrderBy(c => c.Parameters.Count)
            .FirstOrDefault() ?? ctors.OrderBy(c => c.Parameters.Count).First();

        // If the base is a generic instance, substitute its type arguments into the ctor params.
        var map = BuildGenericMap(baseDef, baseRef);
        var args = chosen.Parameters.Select(p =>
        {
            var pt = Substitute(p.ParameterType, map);
            return $"default({Naming.Stub(pt)})";
        });
        return "base(" + string.Join(", ", args) + ")";
    }

    private static Dictionary<string, TypeReference> BuildGenericMap(TypeDefinition def, TypeReference reference)
    {
        var map = new Dictionary<string, TypeReference>(StringComparer.Ordinal);
        if (reference is GenericInstanceType gi)
            for (int i = 0; i < def.GenericParameters.Count && i < gi.GenericArguments.Count; i++)
                map[def.GenericParameters[i].Name] = gi.GenericArguments[i];
        return map;
    }

    // Recursively replace generic parameters with their instantiated arguments.
    private static TypeReference Substitute(TypeReference tr, Dictionary<string, TypeReference> map)
    {
        if (map.Count == 0) return tr;
        switch (tr)
        {
            case GenericParameter gp:
                return map.TryGetValue(gp.Name, out var rep) ? rep : tr;
            case GenericInstanceType git:
            {
                var n = new GenericInstanceType(git.ElementType);
                foreach (var a in git.GenericArguments) n.GenericArguments.Add(Substitute(a, map));
                return n;
            }
            case ArrayType at:
                return new ArrayType(Substitute(at.ElementType, map), at.Rank);
            case ByReferenceType bt:
                return new ByReferenceType(Substitute(bt.ElementType, map));
            default:
                return tr;
        }
    }

    private static void EmitMethod(StringBuilder sb, TypeDefinition t, MethodDefinition m, string indent, bool isInterface)
    {
        // explicit interface implementation
        if (Model.IsExplicitImpl(m))
        {
            var ov = m.Overrides[0];
            if (!IsVisibleInterface(ov.DeclaringType)) return; // internal plumbing interface — not part of public surface
            sb.Append(indent)
              .Append(Naming.Stub(m.ReturnType)).Append(' ')
              .Append(Naming.Stub(ov.DeclaringType)).Append('.').Append(Naming.Ident(LastSegment(StripAccessorPrefix(ov.Name))));
            AppendGenericParamList(sb, m.GenericParameters);
            sb.Append('(').Append(RenderParams(m.Parameters)).Append(')');
            EmitGenericConstraints(sb, m.GenericParameters);
            sb.AppendLine(" { throw new global::System.NotImplementedException(); }");
            return;
        }

        sb.Append(indent);

        // operator?
        string? op = OperatorSyntax(m);
        if (op != null)
        {
            sb.Append("public static ");
            if (op is "implicit" or "explicit")
                sb.Append(op).Append(" operator ").Append(Naming.Stub(m.ReturnType));
            else
                sb.Append(Naming.Stub(m.ReturnType)).Append(" operator ").Append(op);
            sb.Append('(').Append(RenderParams(m.Parameters)).Append(')');
            sb.AppendLine(" { throw new global::System.NotImplementedException(); }");
            return;
        }

        if (!isInterface) sb.Append(Model.MemberAccessibility(m)).Append(' ').Append(MethodModifiers(m));
        sb.Append(Naming.Stub(m.ReturnType)).Append(' ').Append(Naming.Ident(m.Name));
        AppendGenericParamList(sb, m.GenericParameters);
        sb.Append('(').Append(RenderParams(m.Parameters)).Append(')');
        EmitGenericConstraints(sb, m.GenericParameters);
        if (m.IsAbstract || isInterface) sb.AppendLine(";");
        else sb.AppendLine(" { throw new global::System.NotImplementedException(); }");
    }

    private static void EmitProperty(StringBuilder sb, TypeDefinition t, PropertyDefinition p, string indent, bool isInterface)
    {
        var get = p.GetMethod;
        var set = p.SetMethod;
        bool getVis = get != null && Model.IsMemberVisible(get);
        bool setVis = set != null && Model.IsMemberVisible(set);
        if (!getVis && !setVis) return;

        // explicit interface property impl
        bool explicitImpl = (get != null && Model.IsExplicitImpl(get)) || (set != null && Model.IsExplicitImpl(set));
        var primary = (getVis ? get : set)!;

        sb.Append(indent);
        if (explicitImpl)
        {
            var accessor = (get != null && Model.IsExplicitImpl(get)) ? get : set!;
            var ov = accessor.Overrides[0];
            if (!IsVisibleInterface(ov.DeclaringType)) return; // internal interface — not public surface
            sb.Append(Naming.Stub(p.PropertyType)).Append(' ')
              .Append(Naming.Stub(ov.DeclaringType)).Append('.');
            if (p.Parameters.Count > 0)
                sb.Append("this[").Append(RenderParams(p.Parameters)).Append(']');
            else
                sb.Append(Naming.Ident(LastSegment(StripAccessorPrefix(ov.Name))));
            sb.Append(" { ");
            if (getVis) sb.Append("get { throw new global::System.NotImplementedException(); } ");
            if (setVis) sb.Append("set { throw new global::System.NotImplementedException(); } ");
            sb.AppendLine("}");
            return;
        }

        string propAcc = BroaderAccessibility(getVis ? Model.MemberAccessibility(get!) : null,
                                              setVis ? Model.MemberAccessibility(set!) : null);
        if (!isInterface) sb.Append(propAcc).Append(' ').Append(MethodModifiers(primary));
        sb.Append(Naming.Stub(p.PropertyType)).Append(' ');
        AppendPropertyHead(sb, p, explicitImpl: false);

        bool abstractOrIface = primary.IsAbstract || isInterface;
        sb.Append(" { ");
        if (getVis)
        {
            string ga = AccessorModifier(propAcc, Model.MemberAccessibility(get!), isInterface);
            sb.Append(ga).Append(abstractOrIface ? "get; " : "get { throw new global::System.NotImplementedException(); } ");
        }
        if (setVis)
        {
            string sa = AccessorModifier(propAcc, Model.MemberAccessibility(set!), isInterface);
            sb.Append(sa).Append(abstractOrIface ? "set; " : "set { throw new global::System.NotImplementedException(); } ");
        }
        sb.AppendLine("}");
    }

    private static void AppendPropertyHead(StringBuilder sb, PropertyDefinition p, bool explicitImpl)
    {
        if (p.Parameters.Count > 0) // indexer
            sb.Append("this[").Append(RenderParams(p.Parameters)).Append(']');
        else
            sb.Append(Naming.Ident(p.Name));
    }

    private static void EmitEvent(StringBuilder sb, TypeDefinition t, EventDefinition e, string indent, bool isInterface)
    {
        var add = e.AddMethod;
        if (add == null || !Model.IsMemberVisible(add)) return;

        if (Model.IsExplicitImpl(add))
        {
            var ov = add.Overrides[0];
            if (!IsVisibleInterface(ov.DeclaringType)) return;
            sb.Append(indent).Append("event ").Append(Naming.Stub(e.EventType)).Append(' ')
              .Append(Naming.Stub(ov.DeclaringType)).Append('.').Append(Naming.Ident(LastSegment(StripAccessorPrefix(ov.Name))))
              .AppendLine(" { add { } remove { } }");
            return;
        }

        sb.Append(indent);
        if (!isInterface) sb.Append(Model.MemberAccessibility(add)).Append(' ').Append(MethodModifiers(add));
        sb.Append("event ").Append(Naming.Stub(e.EventType)).Append(' ').Append(Naming.Ident(e.Name)).AppendLine(";");
    }

    private static void EmitField(StringBuilder sb, FieldDefinition f, string indent)
    {
        sb.Append(indent).Append(Model.FieldAccessibility(f)).Append(' ');
        if (f.IsLiteral) sb.Append("const ");
        else
        {
            if (f.IsStatic) sb.Append("static ");
            if (f.IsInitOnly) sb.Append("readonly ");
        }
        sb.Append(Naming.Stub(f.FieldType)).Append(' ').Append(Naming.Ident(f.Name));
        if (f.IsLiteral && f.HasConstant)
        {
            string? lit = Literal(f.Constant, f.FieldType);
            sb.Append(" = ").Append(lit ?? "default");
        }
        sb.AppendLine(";");
    }

    // ----------------------------- helpers -----------------------------

    private static string MethodModifiers(MethodDefinition m)
    {
        if (m.IsStatic) return "static ";
        var sb = new StringBuilder();
        if (m.IsAbstract) sb.Append("abstract ");
        else if (m.IsVirtual && !m.IsNewSlot) sb.Append(m.IsFinal ? "sealed override " : "override ");
        else if (m.IsVirtual && m.IsNewSlot && !m.IsFinal) sb.Append("virtual ");
        // virtual+newslot+final == effectively non-virtual to consumers: emit nothing
        return sb.ToString();
    }

    private static void AppendGenericParamList(StringBuilder sb, IList<GenericParameter> gps)
    {
        if (gps.Count == 0) return;
        sb.Append('<').Append(string.Join(", ", gps.Select(g => g.Name))).Append('>');
    }

    private static void EmitGenericConstraints(StringBuilder sb, IList<GenericParameter> gps)
    {
        foreach (var gp in gps)
        {
            var cons = new List<string>();
            if (gp.HasReferenceTypeConstraint) cons.Add("class");
            if (gp.HasNotNullableValueTypeConstraint) cons.Add("struct");
            foreach (var c in gp.Constraints)
            {
                var ct = c.ConstraintType;
                if (ct.FullName == "System.ValueType") continue;
                if (ct.FullName == "System.Object") continue;
                cons.Add(Naming.Stub(ct));
            }
            if (gp.HasDefaultConstructorConstraint && !gp.HasNotNullableValueTypeConstraint) cons.Add("new()");
            if (cons.Count > 0)
                sb.Append(" where ").Append(gp.Name).Append(" : ").Append(string.Join(", ", cons));
        }
    }

    private static string RenderParams(IList<ParameterDefinition> ps)
    {
        // Determine trailing run of renderable defaults to keep optional-trailing rule valid.
        int n = ps.Count;
        var keepDefault = new bool[n];
        var litCache = new string?[n];
        for (int i = n - 1; i >= 0; i--)
        {
            var p = ps[i];
            if (!p.HasConstant) break;
            string? lit = p.Constant == null ? "default" : Literal(p.Constant, p.ParameterType);
            if (lit == null) break;
            litCache[i] = lit;
            keepDefault[i] = true;
        }

        var parts = new List<string>(n);
        for (int i = 0; i < n; i++)
        {
            var p = ps[i];
            var sb = new StringBuilder();
            if (Model.IsParamArray(p)) sb.Append("params ");
            else if (p.ParameterType is ByReferenceType)
            {
                if (p.IsOut) sb.Append("out ");
                else if (p.IsIn) sb.Append("in ");
                else sb.Append("ref ");
            }
            sb.Append(Naming.Stub(p.ParameterType)).Append(' ').Append(Naming.Ident(p.Name));
            if (keepDefault[i]) sb.Append(" = ").Append(litCache[i]);
            parts.Add(sb.ToString());
        }
        return string.Join(", ", parts);
    }

    private static readonly Dictionary<string, string> Operators = new(StringComparer.Ordinal)
    {
        ["op_Implicit"] = "implicit", ["op_Explicit"] = "explicit",
        ["op_Addition"] = "+", ["op_Subtraction"] = "-", ["op_Multiply"] = "*", ["op_Division"] = "/",
        ["op_Modulus"] = "%", ["op_BitwiseAnd"] = "&", ["op_BitwiseOr"] = "|", ["op_ExclusiveOr"] = "^",
        ["op_LeftShift"] = "<<", ["op_RightShift"] = ">>",
        ["op_Equality"] = "==", ["op_Inequality"] = "!=",
        ["op_LessThan"] = "<", ["op_GreaterThan"] = ">", ["op_LessThanOrEqual"] = "<=", ["op_GreaterThanOrEqual"] = ">=",
        ["op_UnaryNegation"] = "-", ["op_UnaryPlus"] = "+", ["op_LogicalNot"] = "!", ["op_OnesComplement"] = "~",
        ["op_Increment"] = "++", ["op_Decrement"] = "--", ["op_True"] = "true", ["op_False"] = "false",
    };

    private static string? OperatorSyntax(MethodDefinition m)
    {
        if (!m.IsSpecialName || !m.Name.StartsWith("op_", StringComparison.Ordinal)) return null;
        return Operators.TryGetValue(m.Name, out var s) ? s : null;
    }

    // An interface is part of the public surface only if it is itself public (or external/framework).
    private static bool IsVisibleInterface(TypeReference itf) => Model.IsVisibleInterface(itf);

    private static string LastSegment(string name)
    {
        int dot = name.LastIndexOf('.');
        return dot >= 0 ? name.Substring(dot + 1) : name;
    }

    private static string StripAccessorPrefix(string name)
    {
        if (name.StartsWith("get_", StringComparison.Ordinal) || name.StartsWith("set_", StringComparison.Ordinal)
            || name.StartsWith("add_", StringComparison.Ordinal) || name.StartsWith("remove_", StringComparison.Ordinal))
            return name.Substring(4);
        return name;
    }

    private static readonly Dictionary<string, int> AccRank = new(StringComparer.Ordinal)
    {
        ["public"] = 5, ["protected internal"] = 4, ["protected"] = 3, ["internal"] = 2, ["private protected"] = 1, ["private"] = 0
    };

    private static string BroaderAccessibility(string? a, string? b)
    {
        if (a == null) return b!;
        if (b == null) return a;
        return AccRank[a] >= AccRank[b] ? a : b;
    }

    // returns "" if accessor matches property accessibility, else "<modifier> "
    private static string AccessorModifier(string propAcc, string accAcc, bool isInterface)
    {
        if (isInterface) return "";
        if (accAcc == propAcc) return "";
        return accAcc + " ";
    }

    // C# literal for a constant; null if not safely renderable.
    private static string? Literal(object? value, TypeReference declaredType)
    {
        if (value == null) return "null";

        // enum-typed constant: cast underlying value to the enum type
        TypeDefinition? td = null;
        try { td = declaredType.Resolve(); } catch { }
        if (td != null && td.IsEnum)
            return "(" + Naming.Stub(declaredType) + ")(" + Convert.ToString(value, CultureInfo.InvariantCulture) + ")";

        switch (value)
        {
            case bool b: return b ? "true" : "false";
            case string s: return "\"" + Escape(s) + "\"";
            case char c: return "'\\u" + ((int)c).ToString("x4") + "'";
            case float f:
                if (float.IsNaN(f)) return "float.NaN";
                if (float.IsPositiveInfinity(f)) return "float.PositiveInfinity";
                if (float.IsNegativeInfinity(f)) return "float.NegativeInfinity";
                return f.ToString("R", CultureInfo.InvariantCulture) + "f";
            case double d:
                if (double.IsNaN(d)) return "double.NaN";
                if (double.IsPositiveInfinity(d)) return "double.PositiveInfinity";
                if (double.IsNegativeInfinity(d)) return "double.NegativeInfinity";
                return d.ToString("R", CultureInfo.InvariantCulture) + "d";
            case long l: return l.ToString(CultureInfo.InvariantCulture) + "L";
            case ulong ul: return ul.ToString(CultureInfo.InvariantCulture) + "UL";
            case uint ui: return ui.ToString(CultureInfo.InvariantCulture) + "U";
            case int i: return i.ToString(CultureInfo.InvariantCulture);
            case short sh: return "(short)" + sh.ToString(CultureInfo.InvariantCulture);
            case ushort ush: return "(ushort)" + ush.ToString(CultureInfo.InvariantCulture);
            case byte by: return "(byte)" + by.ToString(CultureInfo.InvariantCulture);
            case sbyte sb2: return "(sbyte)" + sb2.ToString(CultureInfo.InvariantCulture);
            default: return null;
        }
    }

    private static string Escape(string s)
    {
        var sb = new StringBuilder(s.Length + 2);
        foreach (char c in s)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\r': sb.Append("\\r"); break;
                case '\n': sb.Append("\\n"); break;
                case '\t': sb.Append("\\t"); break;
                case '\0': sb.Append("\\0"); break;
                default:
                    if (c < 0x20) sb.Append("\\u").Append(((int)c).ToString("x4"));
                    else sb.Append(c);
                    break;
            }
        }
        return sb.ToString();
    }
}
