// <auto-generated> clean-room System.Web API skeleton.
// Bodies are NotImplementedException; this proves signature completeness only.
#nullable disable
#pragma warning disable

namespace System.Web.Util
{
    public interface IWebPropertyAccessor
    {
        global::System.Object GetProperty(global::System.Object target);
        void SetProperty(global::System.Object target, global::System.Object value);
    }
    public class HttpEncoder
    {
        // Default singleton instance; lazily created.
        private static readonly global::System.Web.Util.HttpEncoder s_default = new global::System.Web.Util.HttpEncoder();
        // Backing field for the settable Current property; defaults to s_default.
        private static global::System.Web.Util.HttpEncoder s_current;

        public HttpEncoder() { }

        // Strips control chars (CR/LF and other <0x20 except tab, plus DEL) from
        // header name and value to defend against HTTP header (response splitting)
        // injection.
        protected internal virtual void HeaderNameValueEncode(global::System.String headerName, global::System.String headerValue, out global::System.String encodedHeaderName, out global::System.String encodedHeaderValue)
        {
            encodedHeaderName = StripHeaderControlChars(headerName);
            encodedHeaderValue = StripHeaderControlChars(headerValue);
        }

        private static global::System.String StripHeaderControlChars(global::System.String s)
        {
            if (string.IsNullOrEmpty(s))
            {
                return s;
            }
            global::System.Boolean needsStrip = false;
            for (global::System.Int32 i = 0; i < s.Length; i++)
            {
                global::System.Char c = s[i];
                if ((c < 0x20 && c != '\t') || c == 0x7F)
                {
                    needsStrip = true;
                    break;
                }
            }
            if (!needsStrip)
            {
                return s;
            }
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(s.Length);
            for (global::System.Int32 i = 0; i < s.Length; i++)
            {
                global::System.Char c = s[i];
                if ((c < 0x20 && c != '\t') || c == 0x7F)
                {
                    continue;
                }
                sb.Append(c);
            }
            return sb.ToString();
        }

        // Encodes a value for use inside an HTML attribute. Standard rule: encode
        // & < and the double-quote character; leave single quotes and > as-is
        // (matching .NET Framework attribute-encoding behavior).
        protected internal virtual void HtmlAttributeEncode(global::System.String value, global::System.IO.TextWriter output)
        {
            if (output == null)
            {
                throw new global::System.ArgumentNullException(nameof(output));
            }
            if (string.IsNullOrEmpty(value))
            {
                return;
            }
            for (global::System.Int32 i = 0; i < value.Length; i++)
            {
                global::System.Char c = value[i];
                switch (c)
                {
                    case '&':
                        output.Write("&amp;");
                        break;
                    case '"':
                        output.Write("&quot;");
                        break;
                    case '<':
                        output.Write("&lt;");
                        break;
                    default:
                        output.Write(c);
                        break;
                }
            }
        }

        // Decodes HTML named and numeric entities. Recognizes a conservative set
        // of named entities plus &#NN; / &#xHH; numeric forms; unknown entities
        // are emitted verbatim.
        protected internal virtual void HtmlDecode(global::System.String value, global::System.IO.TextWriter output)
        {
            if (output == null)
            {
                throw new global::System.ArgumentNullException(nameof(output));
            }
            if (string.IsNullOrEmpty(value))
            {
                return;
            }
            if (value.IndexOf('&') < 0)
            {
                output.Write(value);
                return;
            }
            global::System.Int32 len = value.Length;
            for (global::System.Int32 i = 0; i < len; i++)
            {
                global::System.Char c = value[i];
                if (c != '&')
                {
                    output.Write(c);
                    continue;
                }
                global::System.Int32 semi = value.IndexOf(';', i + 1);
                if (semi <= i + 1)
                {
                    output.Write(c);
                    continue;
                }
                global::System.String entity = value.Substring(i + 1, semi - i - 1);
                global::System.Boolean handled = false;
                if (entity.Length > 1 && entity[0] == '#')
                {
                    global::System.Int32 code = -1;
                    global::System.Boolean parsed;
                    if (entity[1] == 'x' || entity[1] == 'X')
                    {
                        parsed = global::System.Int32.TryParse(entity.Substring(2), global::System.Globalization.NumberStyles.HexNumber, global::System.Globalization.CultureInfo.InvariantCulture, out code);
                    }
                    else
                    {
                        parsed = global::System.Int32.TryParse(entity.Substring(1), global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out code);
                    }
                    if (parsed && code >= 0 && code <= 0x10FFFF)
                    {
                        if (code <= 0xFFFF)
                        {
                            output.Write((global::System.Char)code);
                        }
                        else
                        {
                            output.Write(global::System.Char.ConvertFromUtf32(code));
                        }
                        handled = true;
                    }
                }
                else
                {
                    global::System.Char named;
                    if (TryDecodeNamedEntity(entity, out named))
                    {
                        output.Write(named);
                        handled = true;
                    }
                }
                if (handled)
                {
                    i = semi;
                }
                else
                {
                    output.Write(c);
                }
            }
        }

        private static global::System.Boolean TryDecodeNamedEntity(global::System.String name, out global::System.Char result)
        {
            switch (name)
            {
                case "amp": result = '&'; return true;
                case "lt": result = '<'; return true;
                case "gt": result = '>'; return true;
                case "quot": result = '"'; return true;
                case "apos": result = '\''; return true;
                case "nbsp": result = (global::System.Char)0x00A0; return true;
                case "copy": result = (global::System.Char)0x00A9; return true;
                case "reg": result = (global::System.Char)0x00AE; return true;
                case "trade": result = (global::System.Char)0x2122; return true;
                default: result = '\0'; return false;
            }
        }

        // Encodes a string as HTML text. Encodes & < > " and any character above
        // 0x7F as a numeric character reference &#NN; (conservative, ASCII-safe
        // output).
        protected internal virtual void HtmlEncode(global::System.String value, global::System.IO.TextWriter output)
        {
            if (output == null)
            {
                throw new global::System.ArgumentNullException(nameof(output));
            }
            if (string.IsNullOrEmpty(value))
            {
                return;
            }
            for (global::System.Int32 i = 0; i < value.Length; i++)
            {
                global::System.Char c = value[i];
                switch (c)
                {
                    case '&':
                        output.Write("&amp;");
                        break;
                    case '<':
                        output.Write("&lt;");
                        break;
                    case '>':
                        output.Write("&gt;");
                        break;
                    case '"':
                        output.Write("&quot;");
                        break;
                    default:
                        if (c > 0x7F)
                        {
                            output.Write("&#");
                            output.Write(((global::System.Int32)c).ToString(global::System.Globalization.CultureInfo.InvariantCulture));
                            output.Write(';');
                        }
                        else
                        {
                            output.Write(c);
                        }
                        break;
                }
            }
        }

        // JavaScript string escaping: escapes the standard backslash sequences,
        // the double-quote, control characters, HTML-significant characters that
        // could break out of a <script> block, and characters >= 0x80 as \uXXXX.
        // Does NOT add surrounding quotes (matches the (value) overload semantics).
        protected internal virtual global::System.String JavaScriptStringEncode(global::System.String value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return global::System.String.Empty;
            }
            global::System.Text.StringBuilder sb = null;
            global::System.Int32 startIndex = 0;
            global::System.Int32 count = 0;
            for (global::System.Int32 i = 0; i < value.Length; i++)
            {
                global::System.Char c = value[i];
                if (CharRequiresJavaScriptEncoding(c))
                {
                    if (sb == null)
                    {
                        sb = new global::System.Text.StringBuilder(value.Length + 8);
                    }
                    if (count > 0)
                    {
                        sb.Append(value, startIndex, count);
                    }
                    startIndex = i + 1;
                    count = 0;
                    switch (c)
                    {
                        case '\b': sb.Append("\\b"); break;
                        case '\t': sb.Append("\\t"); break;
                        case '\n': sb.Append("\\n"); break;
                        case '\f': sb.Append("\\f"); break;
                        case '\r': sb.Append("\\r"); break;
                        case '"': sb.Append("\\\""); break;
                        case '\\': sb.Append("\\\\"); break;
                        default:
                            sb.Append("\\u");
                            sb.Append(((global::System.Int32)c).ToString("x4", global::System.Globalization.CultureInfo.InvariantCulture));
                            break;
                    }
                }
                else
                {
                    count++;
                }
            }
            if (sb == null)
            {
                return value;
            }
            if (count > 0)
            {
                sb.Append(value, startIndex, count);
            }
            return sb.ToString();
        }

        private static global::System.Boolean CharRequiresJavaScriptEncoding(global::System.Char c)
        {
            // Escape quote, backslash, '/', all control chars (< 0x20), HTML-significant
            // chars that can break out of a <script> block, and non-ASCII (>= 0x80).
            return c == '"'
                || c == '\\'
                || c == '/'
                || c == '<'
                || c == '>'
                || c == '&'
                || c == '\''
                || c < 0x20
                || c > 0x7F;
        }

        // Percent-encodes a byte slice for use in a URL. Unreserved characters
        // (A-Z a-z 0-9 and a few legacy-safe chars) are passed through; space
        // becomes '+'; everything else becomes %HH (uppercase hex).
        protected internal virtual global::System.Byte[] UrlEncode(global::System.Byte[] bytes, global::System.Int32 offset, global::System.Int32 count)
        {
            if (bytes == null)
            {
                if (count == 0)
                {
                    return null;
                }
                throw new global::System.ArgumentNullException(nameof(bytes));
            }
            if (offset < 0 || offset > bytes.Length)
            {
                throw new global::System.ArgumentOutOfRangeException(nameof(offset));
            }
            if (count < 0 || offset + count > bytes.Length)
            {
                throw new global::System.ArgumentOutOfRangeException(nameof(count));
            }

            global::System.Int32 expandCount = 0;
            for (global::System.Int32 i = 0; i < count; i++)
            {
                global::System.Byte b = bytes[offset + i];
                global::System.Char ch = (global::System.Char)b;
                if (ch != ' ' && !IsUrlSafeByte(b))
                {
                    expandCount++;
                }
            }

            global::System.Byte[] result = new global::System.Byte[count + (expandCount * 2)];
            global::System.Int32 pos = 0;
            for (global::System.Int32 i = 0; i < count; i++)
            {
                global::System.Byte b = bytes[offset + i];
                global::System.Char ch = (global::System.Char)b;
                if (IsUrlSafeByte(b))
                {
                    result[pos++] = b;
                }
                else if (ch == ' ')
                {
                    result[pos++] = (global::System.Byte)'+';
                }
                else
                {
                    result[pos++] = (global::System.Byte)'%';
                    result[pos++] = (global::System.Byte)IntToHexUpper((b >> 4) & 0x0F);
                    result[pos++] = (global::System.Byte)IntToHexUpper(b & 0x0F);
                }
            }
            return result;
        }

        private static global::System.Boolean IsUrlSafeByte(global::System.Byte b)
        {
            global::System.Char c = (global::System.Char)b;
            if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9'))
            {
                return true;
            }
            switch (c)
            {
                case '-':
                case '_':
                case '.':
                case '!':
                case '*':
                case '(':
                case ')':
                    return true;
                default:
                    return false;
            }
        }

        private static global::System.Char IntToHexUpper(global::System.Int32 n)
        {
            if (n <= 9)
            {
                return (global::System.Char)(n + '0');
            }
            return (global::System.Char)(n - 10 + 'A');
        }

        // Encodes a URL path: leaves path structure ('/') and the query portion
        // (after '?') intact, percent-encoding (UTF-8 %HH) only characters that
        // are not valid in a path segment. Spaces become %20.
        protected internal virtual global::System.String UrlPathEncode(global::System.String value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return value;
            }
            global::System.Int32 queryIndex = value.IndexOf('?');
            global::System.String path;
            global::System.String query;
            if (queryIndex >= 0)
            {
                path = value.Substring(0, queryIndex);
                query = value.Substring(queryIndex);
            }
            else
            {
                path = value;
                query = global::System.String.Empty;
            }

            global::System.Boolean needsEncoding = false;
            for (global::System.Int32 i = 0; i < path.Length; i++)
            {
                if (!IsUrlPathSafe(path[i]))
                {
                    needsEncoding = true;
                    break;
                }
            }
            if (!needsEncoding)
            {
                return value;
            }

            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(path.Length);
            for (global::System.Int32 i = 0; i < path.Length; i++)
            {
                global::System.Char c = path[i];
                if (IsUrlPathSafe(c))
                {
                    sb.Append(c);
                }
                else if (c == ' ')
                {
                    sb.Append("%20");
                }
                else
                {
                    global::System.Byte[] enc = global::System.Text.Encoding.UTF8.GetBytes(c.ToString());
                    for (global::System.Int32 j = 0; j < enc.Length; j++)
                    {
                        global::System.Byte b = enc[j];
                        sb.Append('%');
                        sb.Append(IntToHexUpper((b >> 4) & 0x0F));
                        sb.Append(IntToHexUpper(b & 0x0F));
                    }
                }
            }
            sb.Append(query);
            return sb.ToString();
        }

        private static global::System.Boolean IsUrlPathSafe(global::System.Char c)
        {
            if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9'))
            {
                return true;
            }
            switch (c)
            {
                // Path-structural and unreserved/sub-delimiter chars left intact.
                case '/':
                case '-':
                case '_':
                case '.':
                case '~':
                case '!':
                case '*':
                case '(':
                case ')':
                case '$':
                case '&':
                case '+':
                case ',':
                case ':':
                case ';':
                case '=':
                case '@':
                case '\'':
                    return true;
                default:
                    return false;
            }
        }

        public static global::System.Web.Util.HttpEncoder Current
        {
            get
            {
                global::System.Web.Util.HttpEncoder cur = s_current;
                if (cur == null)
                {
                    return s_default;
                }
                return cur;
            }
            set
            {
                if (value == null)
                {
                    throw new global::System.ArgumentNullException(nameof(value));
                }
                s_current = value;
            }
        }

        public static global::System.Web.Util.HttpEncoder Default
        {
            get { return s_default; }
        }
    }
    public interface IWebObjectFactory
    {
        global::System.Object CreateInstance();
    }
    public enum RequestValidationSource
    {
        QueryString = 0,
        Form = 1,
        Cookies = 2,
        Files = 3,
        RawUrl = 4,
        Path = 5,
        PathInfo = 6,
        Headers = 7,
    }
    public class RequestValidator
    {
        // Default instance backing the settable Current property.
        private static readonly global::System.Web.Util.RequestValidator s_default = new global::System.Web.Util.RequestValidator();
        private static global::System.Web.Util.RequestValidator s_current;

        public RequestValidator() { }

        // Public entry point used by the framework; simply delegates to the
        // protected virtual hook so derived validators can override behavior.
        public global::System.Boolean InvokeIsValidRequestString(global::System.Web.HttpContext context, global::System.String value, global::System.Web.Util.RequestValidationSource requestValidationSource, global::System.String collectionKey, out global::System.Int32 validationFailureIndex)
        {
            return IsValidRequestString(context, value, requestValidationSource, collectionKey, out validationFailureIndex);
        }

        // Conservative dangerous-string scan. Flags the two patterns that the
        // classic ASP.NET request validator treats as potentially-malicious markup:
        //   * '<' immediately followed by a letter or '!' (an opening tag), and
        //   * the literal "&#" (a numeric character-reference prefix).
        // Returns true (valid) when no dangerous sequence is found; otherwise sets
        // validationFailureIndex to the position of the offending character and
        // returns false. This is intentionally narrow and documented; full HTML
        // threat modeling is out of Tier-1 scope.
        protected internal virtual global::System.Boolean IsValidRequestString(global::System.Web.HttpContext context, global::System.String value, global::System.Web.Util.RequestValidationSource requestValidationSource, global::System.String collectionKey, out global::System.Int32 validationFailureIndex)
        {
            validationFailureIndex = 0;
            if (string.IsNullOrEmpty(value))
            {
                return true;
            }
            global::System.Int32 len = value.Length;
            for (global::System.Int32 i = 0; i < len; i++)
            {
                global::System.Char c = value[i];
                if (c == '<')
                {
                    // "<x", "</", "<!" are treated as the start of markup.
                    if (i + 1 < len)
                    {
                        global::System.Char next = value[i + 1];
                        if (IsAsciiLetter(next) || next == '!' || next == '/' || next == '?')
                        {
                            validationFailureIndex = i;
                            return false;
                        }
                    }
                }
                else if (c == '&')
                {
                    // "&#" begins a numeric character reference.
                    if (i + 1 < len && value[i + 1] == '#')
                    {
                        validationFailureIndex = i;
                        return false;
                    }
                }
            }
            return true;
        }

        private static global::System.Boolean IsAsciiLetter(global::System.Char c)
        {
            return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z');
        }

        public static global::System.Web.Util.RequestValidator Current
        {
            get
            {
                global::System.Web.Util.RequestValidator cur = s_current;
                if (cur == null)
                {
                    return s_default;
                }
                return cur;
            }
            set
            {
                if (value == null)
                {
                    throw new global::System.ArgumentNullException(nameof(value));
                }
                s_current = value;
            }
        }
    }
    public delegate void TransactedCallback();
    public class Transactions
    {
        public Transactions() { }

        // net8 cross-platform shim: distributed/COM+ transaction semantics
        // (System.EnterpriseServices) are not supported here, so we simply invoke
        // the callback synchronously. The 'mode' is accepted for signature
        // compatibility but does not enroll the work in an ambient transaction.
        public static void InvokeTransacted(global::System.Web.Util.TransactedCallback callback, global::System.EnterpriseServices.TransactionOption mode)
        {
            global::System.Boolean aborted = false;
            InvokeTransacted(callback, mode, ref aborted);
        }

        // See the (callback, mode) overload. transactionAborted is set to false
        // because no real transaction is created on net8; the callback either runs
        // to completion or throws (which propagates to the caller).
        public static void InvokeTransacted(global::System.Web.Util.TransactedCallback callback, global::System.EnterpriseServices.TransactionOption mode, ref global::System.Boolean transactionAborted)
        {
            if (callback == null)
            {
                throw new global::System.ArgumentNullException(nameof(callback));
            }
            transactionAborted = false;
            callback();
        }
    }
    public delegate void WorkItemCallback();
    public class WorkItem
    {
        public WorkItem() { }

        // Cross-platform implementation: queue the callback onto the CLR thread
        // pool. The classic implementation marshaled onto a dedicated ASP.NET
        // worker; on net8 the shared thread pool is the appropriate equivalent.
        public static void Post(global::System.Web.Util.WorkItemCallback callback)
        {
            if (callback == null)
            {
                throw new global::System.ArgumentNullException(nameof(callback));
            }
            global::System.Threading.ThreadPool.QueueUserWorkItem(
                delegate (global::System.Object state)
                {
                    global::System.Web.Util.WorkItemCallback cb = (global::System.Web.Util.WorkItemCallback)state;
                    cb();
                },
                callback);
        }
    }
}