// <auto-generated> clean-room System.Web API skeleton.
// Bodies are NotImplementedException; this proves signature completeness only.
#nullable disable
#pragma warning disable

namespace System.Web.Hosting
{
    public interface IApplicationMonitor : global::System.IDisposable
    {
        void Start();
        void Stop();
    }
    public sealed class ApplicationMonitors
    {
        internal ApplicationMonitors() { throw new global::System.NotImplementedException(); }
        public global::System.Web.Hosting.IApplicationMonitor MemoryMonitor { get { throw new global::System.NotImplementedException(); } set { throw new global::System.NotImplementedException(); } }
    }
    public enum RecycleLimitNotificationFrequency
    {
        High = 0,
        Medium = 1,
        Low = 2,
    }
    public sealed class RecycleLimitInfo
    {
        public RecycleLimitInfo(global::System.Int64 currentPrivateBytes, global::System.Int64 recycleLimit, global::System.Web.Hosting.RecycleLimitNotificationFrequency recycleLimitNearFrequency) { throw new global::System.NotImplementedException(); }
        public global::System.Int64 CurrentPrivateBytes { get { throw new global::System.NotImplementedException(); } }
        public global::System.Int64 RecycleLimit { get { throw new global::System.NotImplementedException(); } }
        public global::System.Web.Hosting.RecycleLimitNotificationFrequency TrimFrequency { get { throw new global::System.NotImplementedException(); } }
        public global::System.Boolean RequestGC { get { throw new global::System.NotImplementedException(); } set { throw new global::System.NotImplementedException(); } }
    }
    public sealed class LowPhysicalMemoryInfo
    {
        public LowPhysicalMemoryInfo(global::System.Int32 currentPercentUsed, global::System.Int32 percentLimit) { throw new global::System.NotImplementedException(); }
        public global::System.Int32 CurrentPercentUsed { get { throw new global::System.NotImplementedException(); } }
        public global::System.Int32 PercentLimit { get { throw new global::System.NotImplementedException(); } }
        public global::System.Boolean RequestGC { get { throw new global::System.NotImplementedException(); } set { throw new global::System.NotImplementedException(); } }
    }
    public sealed class AspNetMemoryMonitor : global::System.Web.Hosting.IApplicationMonitor, global::System.IDisposable, global::System.IObservable<global::System.Web.Hosting.RecycleLimitInfo>, global::System.IObservable<global::System.Web.Hosting.LowPhysicalMemoryInfo>
    {
        internal AspNetMemoryMonitor() { throw new global::System.NotImplementedException(); }
        public global::System.IDisposable Subscribe(global::System.IObserver<global::System.Web.Hosting.LowPhysicalMemoryInfo> observer) { throw new global::System.NotImplementedException(); }
        public global::System.IDisposable Subscribe(global::System.IObserver<global::System.Web.Hosting.RecycleLimitInfo> observer) { throw new global::System.NotImplementedException(); }
        public void Start() { throw new global::System.NotImplementedException(); }
        public void Stop() { throw new global::System.NotImplementedException(); }
        public void Dispose() { throw new global::System.NotImplementedException(); }
        public global::System.IObserver<global::System.Web.Hosting.LowPhysicalMemoryInfo> DefaultLowPhysicalMemoryObserver { get { throw new global::System.NotImplementedException(); } set { throw new global::System.NotImplementedException(); } }
        public global::System.IObserver<global::System.Web.Hosting.RecycleLimitInfo> DefaultRecycleLimitObserver { get { throw new global::System.NotImplementedException(); } set { throw new global::System.NotImplementedException(); } }
    }
    public class RecycleLimitObserver : global::System.IObserver<global::System.Web.Hosting.RecycleLimitInfo>
    {
        public RecycleLimitObserver() { throw new global::System.NotImplementedException(); }
        public void OnCompleted() { throw new global::System.NotImplementedException(); }
        public void OnError(global::System.Exception error) { throw new global::System.NotImplementedException(); }
        public void OnNext(global::System.Web.Hosting.RecycleLimitInfo recycleLimitInfo) { throw new global::System.NotImplementedException(); }
    }
    public class RecycleLimitMonitor : global::System.MarshalByRefObject
    {
        internal RecycleLimitMonitor() { throw new global::System.NotImplementedException(); }
        public void Dispose() { throw new global::System.NotImplementedException(); }
        public override global::System.Object InitializeLifetimeService() { throw new global::System.NotImplementedException(); }
        public class RecycleLimitMonitorSingleton : global::System.MarshalByRefObject
        {
            internal RecycleLimitMonitorSingleton() { throw new global::System.NotImplementedException(); }
            public static void EnsureCreated() { throw new global::System.NotImplementedException(); }
            public void RegisterProxyAndStart(global::System.Web.Hosting.RecycleLimitMonitor proxy, global::System.String applicationID) { throw new global::System.NotImplementedException(); }
            public void UnregisterProxyAndStop(global::System.Web.Hosting.RecycleLimitMonitor proxy) { throw new global::System.NotImplementedException(); }
            public void Dispose() { throw new global::System.NotImplementedException(); }
            public override global::System.Object InitializeLifetimeService() { throw new global::System.NotImplementedException(); }
        }
    }
    public class LowPhysicalMemoryObserver : global::System.IObserver<global::System.Web.Hosting.LowPhysicalMemoryInfo>
    {
        public LowPhysicalMemoryObserver() { throw new global::System.NotImplementedException(); }
        public void OnCompleted() { throw new global::System.NotImplementedException(); }
        public void OnError(global::System.Exception error) { throw new global::System.NotImplementedException(); }
        public void OnNext(global::System.Web.Hosting.LowPhysicalMemoryInfo lowMemoryInfo) { throw new global::System.NotImplementedException(); }
    }
    public interface ISuspendibleRegisteredObject : global::System.Web.Hosting.IRegisteredObject
    {
        global::System.Action Suspend();
    }
    public interface IProcessHostSupportFunctions
    {
        void GetApplicationProperties(global::System.String appId, out global::System.String virtualPath, out global::System.String physicalPath, out global::System.String siteName, out global::System.String siteId);
        void MapPath(global::System.String appId, global::System.String virtualPath, out global::System.String physicalPath);
        global::System.IntPtr GetConfigToken(global::System.String appId);
        global::System.String GetAppHostConfigFilename();
        global::System.String GetRootWebConfigFilename();
        global::System.IntPtr GetNativeConfigurationSystem();
    }
    public interface IProcessPingCallback
    {
        void Respond();
    }
    public interface IListenerChannelCallback
    {
        void ReportStarted();
        void ReportStopped(global::System.Int32 hr);
        void ReportMessageReceived();
        global::System.Int32 GetId();
        global::System.Int32 GetBlobLength();
        void GetBlob(global::System.Byte[] buffer, ref global::System.Int32 bufferSize);
    }
    public interface IStopListeningRegisteredObject : global::System.Web.Hosting.IRegisteredObject
    {
        void StopListening();
    }
    public interface IAppDomainFactory
    {
        global::System.Object Create(global::System.String module, global::System.String typeName, global::System.String appId, global::System.String appPath, global::System.String strUrlOfAppOrigin, global::System.Int32 iZone);
    }
    public sealed class AppDomainFactory : global::System.Web.Hosting.IAppDomainFactory
    {
        public AppDomainFactory() { throw new global::System.NotImplementedException(); }
        public global::System.Object Create(global::System.String module, global::System.String typeName, global::System.String appId, global::System.String appPath, global::System.String strUrlOfAppOrigin, global::System.Int32 iZone) { throw new global::System.NotImplementedException(); }
    }
    public interface IAppManagerAppDomainFactory
    {
        global::System.Object Create(global::System.String appId, global::System.String appPath);
        void Stop();
    }
    public sealed class AppManagerAppDomainFactory : global::System.Web.Hosting.IAppManagerAppDomainFactory
    {
        public AppManagerAppDomainFactory() { throw new global::System.NotImplementedException(); }
        public global::System.Object Create(global::System.String appId, global::System.String appPath) { throw new global::System.NotImplementedException(); }
        public void Stop() { throw new global::System.NotImplementedException(); }
    }
    public abstract class AppDomainProtocolHandler : global::System.MarshalByRefObject, global::System.Web.Hosting.IRegisteredObject
    {
        protected AppDomainProtocolHandler() { throw new global::System.NotImplementedException(); }
        public override global::System.Object InitializeLifetimeService() { throw new global::System.NotImplementedException(); }
        public abstract void StartListenerChannel(global::System.Web.Hosting.IListenerChannelCallback listenerChannelCallback);
        public abstract void StopListenerChannel(global::System.Int32 listenerChannelId, global::System.Boolean immediate);
        public abstract void StopProtocol(global::System.Boolean immediate);
        public virtual void Stop(global::System.Boolean immediate) { throw new global::System.NotImplementedException(); }
    }
    public sealed class ApplicationHost
    {
        internal ApplicationHost() { throw new global::System.NotImplementedException(); }
        public static global::System.Object CreateApplicationHost(global::System.Type hostType, global::System.String virtualDir, global::System.String physicalDir) { throw new global::System.NotImplementedException(); }
    }
    public sealed class ApplicationInfo
    {
        internal ApplicationInfo() { throw new global::System.NotImplementedException(); }
        public global::System.String ID { get { throw new global::System.NotImplementedException(); } }
        public global::System.String VirtualPath { get { throw new global::System.NotImplementedException(); } }
        public global::System.String PhysicalPath { get { throw new global::System.NotImplementedException(); } }
    }
    public enum HostSecurityPolicyResults
    {
        DefaultPolicy = 0,
        FullTrust = 1,
        AppDomainTrust = 2,
        Nothing = 3,
    }
    public class HostSecurityPolicyResolver
    {
        public HostSecurityPolicyResolver() { throw new global::System.NotImplementedException(); }
        public virtual global::System.Web.Hosting.HostSecurityPolicyResults ResolvePolicy(global::System.Security.Policy.Evidence evidence) { throw new global::System.NotImplementedException(); }
    }
    public sealed class ApplicationManager : global::System.MarshalByRefObject
    {
        internal ApplicationManager() { throw new global::System.NotImplementedException(); }
        public override global::System.Object InitializeLifetimeService() { throw new global::System.NotImplementedException(); }
        public static global::System.Web.Hosting.ApplicationManager GetApplicationManager() { throw new global::System.NotImplementedException(); }
        public void Open() { throw new global::System.NotImplementedException(); }
        public void Close() { throw new global::System.NotImplementedException(); }
        public global::System.Web.Hosting.IRegisteredObject CreateObject(global::System.Web.Hosting.IApplicationHost appHost, global::System.Type type) { throw new global::System.NotImplementedException(); }
        public global::System.Web.Hosting.IRegisteredObject CreateObject(global::System.String appId, global::System.Type type, global::System.String virtualPath, global::System.String physicalPath, global::System.Boolean failIfExists) { throw new global::System.NotImplementedException(); }
        public global::System.Web.Hosting.IRegisteredObject CreateObject(global::System.String appId, global::System.Type type, global::System.String virtualPath, global::System.String physicalPath, global::System.Boolean failIfExists, global::System.Boolean throwOnError) { throw new global::System.NotImplementedException(); }
        public global::System.Web.Hosting.IRegisteredObject GetObject(global::System.String appId, global::System.Type type) { throw new global::System.NotImplementedException(); }
        public global::System.AppDomain GetAppDomain(global::System.String appId) { throw new global::System.NotImplementedException(); }
        public global::System.AppDomain GetAppDomain(global::System.Web.Hosting.IApplicationHost appHost) { throw new global::System.NotImplementedException(); }
        public void StopObject(global::System.String appId, global::System.Type type) { throw new global::System.NotImplementedException(); }
        public global::System.Boolean IsIdle() { throw new global::System.NotImplementedException(); }
        public void ShutdownApplication(global::System.String appId) { throw new global::System.NotImplementedException(); }
        public void ShutdownAll() { throw new global::System.NotImplementedException(); }
        public global::System.Web.Hosting.ApplicationInfo[] GetRunningApplications() { throw new global::System.NotImplementedException(); }
    }
    public sealed class HostingEnvironment : global::System.MarshalByRefObject
    {
        public HostingEnvironment() { throw new global::System.NotImplementedException(); }
        public override global::System.Object InitializeLifetimeService() { throw new global::System.NotImplementedException(); }
        public static void RegisterObject(global::System.Web.Hosting.IRegisteredObject obj) { throw new global::System.NotImplementedException(); }
        public static void UnregisterObject(global::System.Web.Hosting.IRegisteredObject obj) { throw new global::System.NotImplementedException(); }
        public static void QueueBackgroundWorkItem(global::System.Action<global::System.Threading.CancellationToken> workItem) { throw new global::System.NotImplementedException(); }
        public static void QueueBackgroundWorkItem(global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task> workItem) { throw new global::System.NotImplementedException(); }
        public static void IncrementBusyCount() { throw new global::System.NotImplementedException(); }
        public static void DecrementBusyCount() { throw new global::System.NotImplementedException(); }
        public static void MessageReceived() { throw new global::System.NotImplementedException(); }
        public static void InitiateShutdown() { throw new global::System.NotImplementedException(); }
        public static global::System.String MapPath(global::System.String virtualPath) { throw new global::System.NotImplementedException(); }
        public static global::System.IDisposable Impersonate() { throw new global::System.NotImplementedException(); }
        public static global::System.IDisposable Impersonate(global::System.IntPtr token) { throw new global::System.NotImplementedException(); }
        public static global::System.IDisposable Impersonate(global::System.IntPtr userToken, global::System.String virtualPath) { throw new global::System.NotImplementedException(); }
        public static global::System.IDisposable SetCultures() { throw new global::System.NotImplementedException(); }
        public static global::System.IDisposable SetCultures(global::System.String virtualPath) { throw new global::System.NotImplementedException(); }
        public static void RegisterVirtualPathProvider(global::System.Web.Hosting.VirtualPathProvider virtualPathProvider) { throw new global::System.NotImplementedException(); }
        public static global::System.Exception InitializationException { get { throw new global::System.NotImplementedException(); } }
        public static global::System.Boolean InClientBuildManager { get { throw new global::System.NotImplementedException(); } }
        public static global::System.Boolean IsHosted { get { throw new global::System.NotImplementedException(); } }
        public static global::System.Web.Hosting.IApplicationHost ApplicationHost { get { throw new global::System.NotImplementedException(); } }
        public static global::System.Web.Hosting.ApplicationMonitors ApplicationMonitors { get { throw new global::System.NotImplementedException(); } }
        public static global::System.String ApplicationID { get { throw new global::System.NotImplementedException(); } }
        public static global::System.String ApplicationPhysicalPath { get { throw new global::System.NotImplementedException(); } }
        public static global::System.String ApplicationVirtualPath { get { throw new global::System.NotImplementedException(); } }
        public static global::System.String SiteName { get { throw new global::System.NotImplementedException(); } }
        public static global::System.Boolean IsDevelopmentEnvironment { get { throw new global::System.NotImplementedException(); } }
        public static global::System.Web.Caching.Cache Cache { get { throw new global::System.NotImplementedException(); } }
        public static global::System.Web.ApplicationShutdownReason ShutdownReason { get { throw new global::System.NotImplementedException(); } }
        public static global::System.Web.Hosting.VirtualPathProvider VirtualPathProvider { get { throw new global::System.NotImplementedException(); } }
        public static global::System.Int32 MaxConcurrentRequestsPerCPU { get { throw new global::System.NotImplementedException(); } set { throw new global::System.NotImplementedException(); } }
        public static global::System.Int32 MaxConcurrentThreadsPerCPU { get { throw new global::System.NotImplementedException(); } set { throw new global::System.NotImplementedException(); } }
        public static event global::System.EventHandler StopListening;
    }
    public interface IApplicationHost
    {
        global::System.String GetVirtualPath();
        global::System.String GetPhysicalPath();
        global::System.Web.Configuration.IConfigMapPathFactory GetConfigMapPathFactory();
        global::System.IntPtr GetConfigToken();
        global::System.String GetSiteName();
        global::System.String GetSiteID();
        void MessageReceived();
    }
    public interface IProcessHostPreloadClient
    {
        void Preload(global::System.String[] parameters);
    }
    public interface IRegisteredObject
    {
        void Stop(global::System.Boolean immediate);
    }
    public interface IISAPIRuntime
    {
        void StartProcessing();
        void StopProcessing();
        global::System.Int32 ProcessRequest(global::System.IntPtr ecb, global::System.Int32 useProcessModel);
        void DoGCCollect();
    }
    public sealed class ISAPIRuntime : global::System.MarshalByRefObject, global::System.Web.Hosting.IISAPIRuntime, global::System.Web.Hosting.IRegisteredObject
    {
        public ISAPIRuntime() { throw new global::System.NotImplementedException(); }
        public override global::System.Object InitializeLifetimeService() { throw new global::System.NotImplementedException(); }
        public void StartProcessing() { throw new global::System.NotImplementedException(); }
        public void StopProcessing() { throw new global::System.NotImplementedException(); }
        public global::System.Int32 ProcessRequest(global::System.IntPtr ecb, global::System.Int32 iWRType) { throw new global::System.NotImplementedException(); }
        public void DoGCCollect() { throw new global::System.NotImplementedException(); }
        void global::System.Web.Hosting.IRegisteredObject.Stop(global::System.Boolean immediate) { throw new global::System.NotImplementedException(); }
    }
    public interface IProcessHost
    {
        void StartApplication(global::System.String appId, global::System.String appPath, out global::System.Object runtimeInterface);
        void ShutdownApplication(global::System.String appId);
        void Shutdown();
        void EnumerateAppDomains(out global::System.Web.Hosting.IAppDomainInfoEnum appDomainInfoEnum);
    }
    public interface IAdphManager
    {
        void StartAppDomainProtocolListenerChannel(global::System.String appId, global::System.String protocolId, global::System.Web.Hosting.IListenerChannelCallback listenerChannelCallback);
        void StopAppDomainProtocolListenerChannel(global::System.String appId, global::System.String protocolId, global::System.Int32 listenerChannelId, global::System.Boolean immediate);
        void StopAppDomainProtocol(global::System.String appId, global::System.String protocolId, global::System.Boolean immediate);
    }
    public interface IPphManager
    {
        void StartProcessProtocolListenerChannel(global::System.String protocolId, global::System.Web.Hosting.IListenerChannelCallback listenerChannelCallback);
        void StopProcessProtocolListenerChannel(global::System.String protocolId, global::System.Int32 listenerChannelId, global::System.Boolean immediate);
        void StopProcessProtocol(global::System.String protocolId, global::System.Boolean immediate);
    }
    public interface IProcessHostIdleAndHealthCheck
    {
        global::System.Boolean IsIdle();
        void Ping(global::System.Web.Hosting.IProcessPingCallback callback);
    }
    public interface IAppDomainInfo
    {
        global::System.String GetId();
        global::System.String GetVirtualPath();
        global::System.String GetPhysicalPath();
        global::System.Int32 GetSiteId();
        global::System.Boolean IsIdle();
    }
    public interface IAppDomainInfoEnum
    {
        global::System.Web.Hosting.IAppDomainInfo GetData();
        global::System.Int32 Count();
        global::System.Boolean MoveNext();
        void Reset();
    }
    public class AppDomainInfoEnum : global::System.Web.Hosting.IAppDomainInfoEnum
    {
        internal AppDomainInfoEnum() { throw new global::System.NotImplementedException(); }
        public global::System.Int32 Count() { throw new global::System.NotImplementedException(); }
        public global::System.Web.Hosting.IAppDomainInfo GetData() { throw new global::System.NotImplementedException(); }
        public global::System.Boolean MoveNext() { throw new global::System.NotImplementedException(); }
        public void Reset() { throw new global::System.NotImplementedException(); }
    }
    public class AppDomainInfo : global::System.Web.Hosting.IAppDomainInfo
    {
        internal AppDomainInfo() { throw new global::System.NotImplementedException(); }
        public global::System.String GetId() { throw new global::System.NotImplementedException(); }
        public global::System.String GetVirtualPath() { throw new global::System.NotImplementedException(); }
        public global::System.String GetPhysicalPath() { throw new global::System.NotImplementedException(); }
        public global::System.Int32 GetSiteId() { throw new global::System.NotImplementedException(); }
        public global::System.Boolean IsIdle() { throw new global::System.NotImplementedException(); }
    }
    public interface IApplicationPreloadManager
    {
        void SetApplicationPreloadUtil(global::System.Web.Hosting.IApplicationPreloadUtil preloadUtil);
        void SetApplicationPreloadState(global::System.String context, global::System.String appId, global::System.Boolean enabled);
    }
    public interface IApplicationPreloadUtil
    {
        void GetApplicationPreloadInfo(global::System.String context, out global::System.Boolean enabled, out global::System.String startupObjType, out global::System.String[] parametersForStartupObj);
        void ReportApplicationPreloadFailure(global::System.String context, global::System.Int32 errorCode, global::System.String errorMessage);
    }
    public sealed class ProcessHost : global::System.MarshalByRefObject, global::System.Web.Hosting.IProcessHost, global::System.Web.Hosting.IAdphManager, global::System.Web.Hosting.IPphManager, global::System.Web.Hosting.IProcessHostIdleAndHealthCheck, global::System.Web.Hosting.IApplicationPreloadManager
    {
        internal ProcessHost() { throw new global::System.NotImplementedException(); }
        public override global::System.Object InitializeLifetimeService() { throw new global::System.NotImplementedException(); }
        public void StartProcessProtocolListenerChannel(global::System.String protocolId, global::System.Web.Hosting.IListenerChannelCallback listenerChannelCallback) { throw new global::System.NotImplementedException(); }
        public void StopProcessProtocolListenerChannel(global::System.String protocolId, global::System.Int32 listenerChannelId, global::System.Boolean immediate) { throw new global::System.NotImplementedException(); }
        public void StopProcessProtocol(global::System.String protocolId, global::System.Boolean immediate) { throw new global::System.NotImplementedException(); }
        public void StartAppDomainProtocolListenerChannel(global::System.String appId, global::System.String protocolId, global::System.Web.Hosting.IListenerChannelCallback listenerChannelCallback) { throw new global::System.NotImplementedException(); }
        public void StopAppDomainProtocolListenerChannel(global::System.String appId, global::System.String protocolId, global::System.Int32 listenerChannelId, global::System.Boolean immediate) { throw new global::System.NotImplementedException(); }
        public void StopAppDomainProtocol(global::System.String appId, global::System.String protocolId, global::System.Boolean immediate) { throw new global::System.NotImplementedException(); }
        public void StartApplication(global::System.String appId, global::System.String appPath, out global::System.Object runtimeInterface) { throw new global::System.NotImplementedException(); }
        public void ShutdownApplication(global::System.String appId) { throw new global::System.NotImplementedException(); }
        public void Shutdown() { throw new global::System.NotImplementedException(); }
        public void EnumerateAppDomains(out global::System.Web.Hosting.IAppDomainInfoEnum appDomainInfoEnum) { throw new global::System.NotImplementedException(); }
        public global::System.Boolean IsIdle() { throw new global::System.NotImplementedException(); }
        public void Ping(global::System.Web.Hosting.IProcessPingCallback callback) { throw new global::System.NotImplementedException(); }
        public void SetApplicationPreloadUtil(global::System.Web.Hosting.IApplicationPreloadUtil applicationPreloadUtil) { throw new global::System.NotImplementedException(); }
        public void SetApplicationPreloadState(global::System.String context, global::System.String appId, global::System.Boolean enabled) { throw new global::System.NotImplementedException(); }
    }
    public interface IProcessHostFactoryHelper
    {
        global::System.Object GetProcessHost(global::System.Web.Hosting.IProcessHostSupportFunctions functions);
    }
    public sealed class ProcessHostFactoryHelper : global::System.MarshalByRefObject, global::System.Web.Hosting.IProcessHostFactoryHelper
    {
        public ProcessHostFactoryHelper() { throw new global::System.NotImplementedException(); }
        public override global::System.Object InitializeLifetimeService() { throw new global::System.NotImplementedException(); }
        public global::System.Object GetProcessHost(global::System.Web.Hosting.IProcessHostSupportFunctions functions) { throw new global::System.NotImplementedException(); }
    }
    public abstract class ProcessProtocolHandler : global::System.MarshalByRefObject
    {
        protected ProcessProtocolHandler() { throw new global::System.NotImplementedException(); }
        public override global::System.Object InitializeLifetimeService() { throw new global::System.NotImplementedException(); }
        public abstract void StartListenerChannel(global::System.Web.Hosting.IListenerChannelCallback listenerChannelCallback, global::System.Web.Hosting.IAdphManager AdphManager);
        public abstract void StopListenerChannel(global::System.Int32 listenerChannelId, global::System.Boolean immediate);
        public abstract void StopProtocol(global::System.Boolean immediate);
    }
    public class SimpleWorkerRequest : global::System.Web.HttpWorkerRequest
    {
        public SimpleWorkerRequest(global::System.String page, global::System.String query, global::System.IO.TextWriter output) { throw new global::System.NotImplementedException(); }
        public SimpleWorkerRequest(global::System.String appVirtualDir, global::System.String appPhysicalDir, global::System.String page, global::System.String query, global::System.IO.TextWriter output) { throw new global::System.NotImplementedException(); }
        public override global::System.String GetUriPath() { throw new global::System.NotImplementedException(); }
        public override global::System.String GetQueryString() { throw new global::System.NotImplementedException(); }
        public override global::System.String GetRawUrl() { throw new global::System.NotImplementedException(); }
        public override global::System.String GetHttpVerbName() { throw new global::System.NotImplementedException(); }
        public override global::System.String GetHttpVersion() { throw new global::System.NotImplementedException(); }
        public override global::System.String GetRemoteAddress() { throw new global::System.NotImplementedException(); }
        public override global::System.Int32 GetRemotePort() { throw new global::System.NotImplementedException(); }
        public override global::System.String GetLocalAddress() { throw new global::System.NotImplementedException(); }
        public override global::System.Int32 GetLocalPort() { throw new global::System.NotImplementedException(); }
        public override global::System.IntPtr GetUserToken() { throw new global::System.NotImplementedException(); }
        public override global::System.String GetFilePath() { throw new global::System.NotImplementedException(); }
        public override global::System.String GetFilePathTranslated() { throw new global::System.NotImplementedException(); }
        public override global::System.String GetPathInfo() { throw new global::System.NotImplementedException(); }
        public override global::System.String GetAppPath() { throw new global::System.NotImplementedException(); }
        public override global::System.String GetAppPathTranslated() { throw new global::System.NotImplementedException(); }
        public override global::System.String GetServerVariable(global::System.String name) { throw new global::System.NotImplementedException(); }
        public override global::System.String MapPath(global::System.String path) { throw new global::System.NotImplementedException(); }
        public override void SendStatus(global::System.Int32 statusCode, global::System.String statusDescription) { throw new global::System.NotImplementedException(); }
        public override void SendKnownResponseHeader(global::System.Int32 index, global::System.String value) { throw new global::System.NotImplementedException(); }
        public override void SendUnknownResponseHeader(global::System.String name, global::System.String value) { throw new global::System.NotImplementedException(); }
        public override void SendResponseFromMemory(global::System.Byte[] data, global::System.Int32 length) { throw new global::System.NotImplementedException(); }
        public override void SendResponseFromFile(global::System.String filename, global::System.Int64 offset, global::System.Int64 length) { throw new global::System.NotImplementedException(); }
        public override void SendResponseFromFile(global::System.IntPtr handle, global::System.Int64 offset, global::System.Int64 length) { throw new global::System.NotImplementedException(); }
        public override void FlushResponse(global::System.Boolean finalFlush) { throw new global::System.NotImplementedException(); }
        public override void EndOfRequest() { throw new global::System.NotImplementedException(); }
        public override global::System.String MachineConfigPath { get { throw new global::System.NotImplementedException(); } }
        public override global::System.String RootWebConfigPath { get { throw new global::System.NotImplementedException(); } }
        public override global::System.String MachineInstallDirectory { get { throw new global::System.NotImplementedException(); } }
    }
    public abstract class VirtualPathProvider : global::System.MarshalByRefObject
    {
        protected VirtualPathProvider() { throw new global::System.NotImplementedException(); }
        public override global::System.Object InitializeLifetimeService() { throw new global::System.NotImplementedException(); }
        protected virtual void Initialize() { throw new global::System.NotImplementedException(); }
        public virtual global::System.String GetFileHash(global::System.String virtualPath, global::System.Collections.IEnumerable virtualPathDependencies) { throw new global::System.NotImplementedException(); }
        public virtual global::System.Web.Caching.CacheDependency GetCacheDependency(global::System.String virtualPath, global::System.Collections.IEnumerable virtualPathDependencies, global::System.DateTime utcStart) { throw new global::System.NotImplementedException(); }
        public virtual global::System.Boolean FileExists(global::System.String virtualPath) { throw new global::System.NotImplementedException(); }
        public virtual global::System.Boolean DirectoryExists(global::System.String virtualDir) { throw new global::System.NotImplementedException(); }
        public virtual global::System.Web.Hosting.VirtualFile GetFile(global::System.String virtualPath) { throw new global::System.NotImplementedException(); }
        public virtual global::System.Web.Hosting.VirtualDirectory GetDirectory(global::System.String virtualDir) { throw new global::System.NotImplementedException(); }
        public virtual global::System.String GetCacheKey(global::System.String virtualPath) { throw new global::System.NotImplementedException(); }
        public virtual global::System.String CombineVirtualPaths(global::System.String basePath, global::System.String relativePath) { throw new global::System.NotImplementedException(); }
        public static global::System.IO.Stream OpenFile(global::System.String virtualPath) { throw new global::System.NotImplementedException(); }
        protected internal global::System.Web.Hosting.VirtualPathProvider Previous { get { throw new global::System.NotImplementedException(); } }
    }
    public abstract class VirtualFileBase : global::System.MarshalByRefObject
    {
        protected VirtualFileBase() { throw new global::System.NotImplementedException(); }
        public override global::System.Object InitializeLifetimeService() { throw new global::System.NotImplementedException(); }
        public virtual global::System.String Name { get { throw new global::System.NotImplementedException(); } }
        public global::System.String VirtualPath { get { throw new global::System.NotImplementedException(); } }
        public abstract global::System.Boolean IsDirectory { get; }
    }
    public abstract class VirtualFile : global::System.Web.Hosting.VirtualFileBase
    {
        protected VirtualFile(global::System.String virtualPath) { throw new global::System.NotImplementedException(); }
        public abstract global::System.IO.Stream Open();
        public override global::System.Boolean IsDirectory { get { throw new global::System.NotImplementedException(); } }
    }
    public abstract class VirtualDirectory : global::System.Web.Hosting.VirtualFileBase
    {
        protected VirtualDirectory(global::System.String virtualPath) { throw new global::System.NotImplementedException(); }
        public override global::System.Boolean IsDirectory { get { throw new global::System.NotImplementedException(); } }
        public abstract global::System.Collections.IEnumerable Directories { get; }
        public abstract global::System.Collections.IEnumerable Files { get; }
        public abstract global::System.Collections.IEnumerable Children { get; }
    }
}
