// <auto-generated> clean-room System.Web API skeleton.
// System.Web.Routing implemented from public surface + documented behavior (clean-room).
#nullable disable
#pragma warning disable

namespace System.Web.Routing
{
    public class HttpMethodConstraint : global::System.Web.Routing.IRouteConstraint
    {
        private readonly global::System.Collections.Generic.ICollection<global::System.String> _allowedMethods;
        public HttpMethodConstraint(params global::System.String[] allowedMethods)
        {
            if (allowedMethods == null) { throw new global::System.ArgumentNullException("allowedMethods"); }
            global::System.Collections.Generic.List<global::System.String> list =
                new global::System.Collections.Generic.List<global::System.String>();
            for (global::System.Int32 i = 0; i < allowedMethods.Length; i++) { list.Add(allowedMethods[i]); }
            _allowedMethods = list;
        }
        protected virtual global::System.Boolean Match(global::System.Web.HttpContextBase httpContext, global::System.Web.Routing.Route route, global::System.String parameterName, global::System.Web.Routing.RouteValueDictionary values, global::System.Web.Routing.RouteDirection routeDirection)
        {
            if (httpContext == null) { throw new global::System.ArgumentNullException("httpContext"); }
            if (route == null) { throw new global::System.ArgumentNullException("route"); }
            if (parameterName == null) { throw new global::System.ArgumentNullException("parameterName"); }
            if (values == null) { throw new global::System.ArgumentNullException("values"); }
            switch (routeDirection)
            {
                case global::System.Web.Routing.RouteDirection.IncomingRequest:
                    global::System.Web.HttpRequestBase req = httpContext.Request;
                    global::System.String verb = req == null ? null : req.HttpMethod;
                    return MethodAllowed(verb);
                case global::System.Web.Routing.RouteDirection.UrlGeneration:
                    global::System.Object methodValue;
                    if (!values.TryGetValue(parameterName, out methodValue)) { return true; }
                    return MethodAllowed(global::System.Convert.ToString(methodValue));
                default:
                    return true;
            }
        }
        private global::System.Boolean MethodAllowed(global::System.String verb)
        {
            if (verb == null) { return false; }
            foreach (global::System.String m in _allowedMethods)
            {
                if (global::System.String.Equals(m, verb, global::System.StringComparison.OrdinalIgnoreCase)) { return true; }
            }
            return false;
        }
        global::System.Boolean global::System.Web.Routing.IRouteConstraint.Match(global::System.Web.HttpContextBase httpContext, global::System.Web.Routing.Route route, global::System.String parameterName, global::System.Web.Routing.RouteValueDictionary values, global::System.Web.Routing.RouteDirection routeDirection)
        {
            return Match(httpContext, route, parameterName, values, routeDirection);
        }
        public global::System.Collections.Generic.ICollection<global::System.String> AllowedMethods { get { return _allowedMethods; } }
    }
    public interface IRouteConstraint
    {
        global::System.Boolean Match(global::System.Web.HttpContextBase httpContext, global::System.Web.Routing.Route route, global::System.String parameterName, global::System.Web.Routing.RouteValueDictionary values, global::System.Web.Routing.RouteDirection routeDirection);
    }
    public interface IRouteHandler
    {
        global::System.Web.IHttpHandler GetHttpHandler(global::System.Web.Routing.RequestContext requestContext);
    }
    public class RequestContext
    {
        private global::System.Web.HttpContextBase _httpContext;
        private global::System.Web.Routing.RouteData _routeData;
        public RequestContext() { }
        public RequestContext(global::System.Web.HttpContextBase httpContext, global::System.Web.Routing.RouteData routeData)
        {
            if (httpContext == null) { throw new global::System.ArgumentNullException("httpContext"); }
            if (routeData == null) { throw new global::System.ArgumentNullException("routeData"); }
            _httpContext = httpContext;
            _routeData = routeData;
        }
        public virtual global::System.Web.HttpContextBase HttpContext
        {
            get { return _httpContext; }
            set { _httpContext = value; }
        }
        public virtual global::System.Web.Routing.RouteData RouteData
        {
            get { return _routeData; }
            set { _routeData = value; }
        }
    }
    public class Route : global::System.Web.Routing.RouteBase
    {
        private global::System.String _url;
        private global::System.Web.Routing.ParsedRoute _parsedRoute;
        private global::System.Web.Routing.RouteValueDictionary _defaults;
        private global::System.Web.Routing.RouteValueDictionary _constraints;
        private global::System.Web.Routing.RouteValueDictionary _dataTokens;
        private global::System.Web.Routing.IRouteHandler _routeHandler;

        public Route(global::System.String url, global::System.Web.Routing.IRouteHandler routeHandler)
            : this(url, null, null, null, routeHandler) { }
        public Route(global::System.String url, global::System.Web.Routing.RouteValueDictionary defaults, global::System.Web.Routing.IRouteHandler routeHandler)
            : this(url, defaults, null, null, routeHandler) { }
        public Route(global::System.String url, global::System.Web.Routing.RouteValueDictionary defaults, global::System.Web.Routing.RouteValueDictionary constraints, global::System.Web.Routing.IRouteHandler routeHandler)
            : this(url, defaults, constraints, null, routeHandler) { }
        public Route(global::System.String url, global::System.Web.Routing.RouteValueDictionary defaults, global::System.Web.Routing.RouteValueDictionary constraints, global::System.Web.Routing.RouteValueDictionary dataTokens, global::System.Web.Routing.IRouteHandler routeHandler)
        {
            Url = url;
            Defaults = defaults;
            Constraints = constraints;
            DataTokens = dataTokens;
            RouteHandler = routeHandler;
        }

        public override global::System.Web.Routing.RouteData GetRouteData(global::System.Web.HttpContextBase httpContext)
        {
            if (httpContext == null) { throw new global::System.ArgumentNullException("httpContext"); }
            global::System.Web.HttpRequestBase request = httpContext.Request;
            if (request == null) { return null; }
            global::System.String virtualPath = request.AppRelativeCurrentExecutionFilePath;
            global::System.String pathInfo = request.PathInfo;
            if (virtualPath == null) { return null; }
            // Strip the leading "~/" so we compare against the route's segment pattern.
            global::System.String requestPath;
            if (virtualPath.Length >= 2 && virtualPath[0] == '~' && virtualPath[1] == '/')
            {
                requestPath = virtualPath.Substring(2);
            }
            else if (virtualPath.Length >= 1 && virtualPath[0] == '~')
            {
                requestPath = virtualPath.Substring(1);
            }
            else
            {
                requestPath = virtualPath;
            }
            if (!global::System.String.IsNullOrEmpty(pathInfo))
            {
                requestPath = requestPath + pathInfo;
            }

            global::System.Web.Routing.RouteValueDictionary values = _parsedRoute.Match(requestPath, _defaults);
            if (values == null) { return null; }

            if (!ProcessConstraints(httpContext, values, global::System.Web.Routing.RouteDirection.IncomingRequest))
            {
                return null;
            }

            global::System.Web.Routing.RouteData routeData = new global::System.Web.Routing.RouteData(this, _routeHandler);
            foreach (global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object> kvp in values)
            {
                routeData.Values[kvp.Key] = kvp.Value;
            }
            if (_dataTokens != null)
            {
                foreach (global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object> kvp in _dataTokens)
                {
                    routeData.DataTokens[kvp.Key] = kvp.Value;
                }
            }
            return routeData;
        }

        public override global::System.Web.Routing.VirtualPathData GetVirtualPath(global::System.Web.Routing.RequestContext requestContext, global::System.Web.Routing.RouteValueDictionary values)
        {
            if (requestContext == null) { throw new global::System.ArgumentNullException("requestContext"); }
            global::System.Web.Routing.RouteData currentRouteData =
                requestContext.RouteData == null ? null : requestContext.RouteData;
            global::System.Web.Routing.RouteValueDictionary currentValues =
                currentRouteData == null ? new global::System.Web.Routing.RouteValueDictionary() : currentRouteData.Values;

            global::System.Web.Routing.BoundUrl bound = _parsedRoute.Bind(currentValues, values, _defaults);
            if (bound == null) { return null; }

            if (!ProcessConstraints(requestContext.HttpContext, bound.Values, global::System.Web.Routing.RouteDirection.UrlGeneration))
            {
                return null;
            }

            global::System.String url = bound.Url;
            global::System.Web.Routing.VirtualPathData data = new global::System.Web.Routing.VirtualPathData(this, url);
            if (_dataTokens != null)
            {
                foreach (global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object> kvp in _dataTokens)
                {
                    data.DataTokens[kvp.Key] = kvp.Value;
                }
            }
            return data;
        }

        private global::System.Boolean ProcessConstraints(global::System.Web.HttpContextBase httpContext, global::System.Web.Routing.RouteValueDictionary values, global::System.Web.Routing.RouteDirection routeDirection)
        {
            if (_constraints != null)
            {
                foreach (global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object> kvp in _constraints)
                {
                    if (!ProcessConstraint(httpContext, kvp.Value, kvp.Key, values, routeDirection))
                    {
                        return false;
                    }
                }
            }
            return true;
        }

        protected virtual global::System.Boolean ProcessConstraint(global::System.Web.HttpContextBase httpContext, global::System.Object constraint, global::System.String parameterName, global::System.Web.Routing.RouteValueDictionary values, global::System.Web.Routing.RouteDirection routeDirection)
        {
            global::System.Web.Routing.IRouteConstraint customConstraint = constraint as global::System.Web.Routing.IRouteConstraint;
            if (customConstraint != null)
            {
                return customConstraint.Match(httpContext, this, parameterName, values, routeDirection);
            }
            global::System.String constraintsRule = constraint as global::System.String;
            if (constraintsRule == null)
            {
                throw new global::System.InvalidOperationException(
                    "The constraint entry '" + parameterName + "' on the route with URL '" + Url +
                    "' must have a string value or be of a type which implements IRouteConstraint.");
            }
            global::System.Object parameterValue;
            values.TryGetValue(parameterName, out parameterValue);
            global::System.String parameterValueString = global::System.Convert.ToString(parameterValue, global::System.Globalization.CultureInfo.InvariantCulture);
            global::System.String constraintsRegEx = "^(" + constraintsRule + ")$";
            return global::System.Text.RegularExpressions.Regex.IsMatch(
                parameterValueString, constraintsRegEx,
                global::System.Text.RegularExpressions.RegexOptions.CultureInvariant |
                global::System.Text.RegularExpressions.RegexOptions.IgnoreCase);
        }

        public global::System.Web.Routing.RouteValueDictionary Constraints
        {
            get { return _constraints; }
            set { _constraints = value; }
        }
        public global::System.Web.Routing.RouteValueDictionary DataTokens
        {
            get { return _dataTokens; }
            set { _dataTokens = value; }
        }
        public global::System.Web.Routing.RouteValueDictionary Defaults
        {
            get { return _defaults; }
            set { _defaults = value; }
        }
        public global::System.Web.Routing.IRouteHandler RouteHandler
        {
            get { return _routeHandler; }
            set { _routeHandler = value; }
        }
        public global::System.String Url
        {
            get { return _url == null ? global::System.String.Empty : _url; }
            set
            {
                _parsedRoute = global::System.Web.Routing.ParsedRoute.Parse(value);
                _url = value;
            }
        }
    }
    public abstract class RouteBase
    {
        private global::System.Boolean _routeExistingFiles = true;
        protected RouteBase() { }
        public abstract global::System.Web.Routing.RouteData GetRouteData(global::System.Web.HttpContextBase httpContext);
        public abstract global::System.Web.Routing.VirtualPathData GetVirtualPath(global::System.Web.Routing.RequestContext requestContext, global::System.Web.Routing.RouteValueDictionary values);
        public global::System.Boolean RouteExistingFiles
        {
            get { return _routeExistingFiles; }
            set { _routeExistingFiles = value; }
        }
    }
    public class RouteCollection : global::System.Collections.ObjectModel.Collection<global::System.Web.Routing.RouteBase>
    {
        private readonly global::System.Collections.Generic.Dictionary<global::System.String, global::System.Web.Routing.RouteBase> _namedMap =
            new global::System.Collections.Generic.Dictionary<global::System.String, global::System.Web.Routing.RouteBase>(global::System.StringComparer.OrdinalIgnoreCase);
        private readonly global::System.Threading.ReaderWriterLockSlim _rwLock = new global::System.Threading.ReaderWriterLockSlim();
        private global::System.Boolean _appendTrailingSlash;
        private global::System.Boolean _lowercaseUrls;
        private global::System.Boolean _routeExistingFiles;

        public RouteCollection() { }
        public RouteCollection(global::System.Web.Hosting.VirtualPathProvider virtualPathProvider) { }

        public void Add(global::System.String name, global::System.Web.Routing.RouteBase item)
        {
            if (item == null) { throw new global::System.ArgumentNullException("item"); }
            if (!global::System.String.IsNullOrEmpty(name) && _namedMap.ContainsKey(name))
            {
                throw new global::System.ArgumentException(
                    "A route named '" + name + "' is already in the route collection. Route names must be unique.", "name");
            }
            Add(item);
            if (!global::System.String.IsNullOrEmpty(name))
            {
                _namedMap[name] = item;
            }
        }

        public global::System.Web.Routing.Route MapPageRoute(global::System.String routeName, global::System.String routeUrl, global::System.String physicalFile)
        {
            return MapPageRoute(routeName, routeUrl, physicalFile, true, null, null, null);
        }
        public global::System.Web.Routing.Route MapPageRoute(global::System.String routeName, global::System.String routeUrl, global::System.String physicalFile, global::System.Boolean checkPhysicalUrlAccess)
        {
            return MapPageRoute(routeName, routeUrl, physicalFile, checkPhysicalUrlAccess, null, null, null);
        }
        public global::System.Web.Routing.Route MapPageRoute(global::System.String routeName, global::System.String routeUrl, global::System.String physicalFile, global::System.Boolean checkPhysicalUrlAccess, global::System.Web.Routing.RouteValueDictionary defaults)
        {
            return MapPageRoute(routeName, routeUrl, physicalFile, checkPhysicalUrlAccess, defaults, null, null);
        }
        public global::System.Web.Routing.Route MapPageRoute(global::System.String routeName, global::System.String routeUrl, global::System.String physicalFile, global::System.Boolean checkPhysicalUrlAccess, global::System.Web.Routing.RouteValueDictionary defaults, global::System.Web.Routing.RouteValueDictionary constraints)
        {
            return MapPageRoute(routeName, routeUrl, physicalFile, checkPhysicalUrlAccess, defaults, constraints, null);
        }
        public global::System.Web.Routing.Route MapPageRoute(global::System.String routeName, global::System.String routeUrl, global::System.String physicalFile, global::System.Boolean checkPhysicalUrlAccess, global::System.Web.Routing.RouteValueDictionary defaults, global::System.Web.Routing.RouteValueDictionary constraints, global::System.Web.Routing.RouteValueDictionary dataTokens)
        {
            if (routeUrl == null) { throw new global::System.ArgumentNullException("routeUrl"); }
            global::System.Web.Routing.Route route = new global::System.Web.Routing.Route(
                routeUrl, defaults, constraints, dataTokens,
                new global::System.Web.Routing.PageRouteHandler(physicalFile, checkPhysicalUrlAccess));
            Add(routeName, route);
            return route;
        }

        protected override void ClearItems()
        {
            _namedMap.Clear();
            base.ClearItems();
        }
        public global::System.IDisposable GetReadLock()
        {
            _rwLock.EnterReadLock();
            return new global::System.Web.Routing.RouteCollection.ReadLockDisposable(_rwLock);
        }
        public global::System.IDisposable GetWriteLock()
        {
            _rwLock.EnterWriteLock();
            return new global::System.Web.Routing.RouteCollection.WriteLockDisposable(_rwLock);
        }

        public global::System.Web.Routing.RouteData GetRouteData(global::System.Web.HttpContextBase httpContext)
        {
            if (httpContext == null) { throw new global::System.ArgumentNullException("httpContext"); }
            if (httpContext.Request == null)
            {
                throw new global::System.ArgumentException("The context does not contain any request data.", "httpContext");
            }
            if (Count == 0) { return null; }
            global::System.Boolean isRouteToExistingFile = false;
            global::System.Boolean checkedExistence = false;
            using (GetReadLock())
            {
                global::System.Int32 n = Count;
                for (global::System.Int32 i = 0; i < n; i++)
                {
                    global::System.Web.Routing.RouteBase route = this[i];
                    if (route == null) { continue; }
                    global::System.Web.Routing.RouteData routeData = route.GetRouteData(httpContext);
                    if (routeData != null)
                    {
                        if (!route.RouteExistingFiles)
                        {
                            if (!checkedExistence)
                            {
                                isRouteToExistingFile = IsRouteToExistingFile(httpContext);
                                checkedExistence = true;
                            }
                            if (isRouteToExistingFile)
                            {
                                return null;
                            }
                        }
                        return routeData;
                    }
                }
            }
            return null;
        }

        private global::System.Boolean IsRouteToExistingFile(global::System.Web.HttpContextBase httpContext)
        {
            if (_routeExistingFiles) { return false; }
            global::System.Web.HttpRequestBase request = httpContext.Request;
            global::System.String path = request.AppRelativeCurrentExecutionFilePath;
            if (global::System.String.IsNullOrEmpty(path) || path == "~/") { return false; }
            try
            {
                global::System.String mapped = request.MapPath(path);
                if (global::System.String.IsNullOrEmpty(mapped)) { return false; }
                return global::System.IO.File.Exists(mapped) || global::System.IO.Directory.Exists(mapped);
            }
            catch
            {
                return false;
            }
        }

        public global::System.Web.Routing.VirtualPathData GetVirtualPath(global::System.Web.Routing.RequestContext requestContext, global::System.Web.Routing.RouteValueDictionary values)
        {
            return GetVirtualPath(requestContext, null, values);
        }
        public global::System.Web.Routing.VirtualPathData GetVirtualPath(global::System.Web.Routing.RequestContext requestContext, global::System.String name, global::System.Web.Routing.RouteValueDictionary values)
        {
            if (requestContext == null) { throw new global::System.ArgumentNullException("requestContext"); }
            using (GetReadLock())
            {
                global::System.Web.Routing.VirtualPathData data = null;
                if (!global::System.String.IsNullOrEmpty(name))
                {
                    global::System.Web.Routing.RouteBase namedRoute;
                    if (!_namedMap.TryGetValue(name, out namedRoute))
                    {
                        throw new global::System.ArgumentException(
                            "A route named '" + name + "' could not be found in the route collection.", "name");
                    }
                    data = namedRoute.GetVirtualPath(requestContext, values);
                }
                else
                {
                    global::System.Int32 n = Count;
                    for (global::System.Int32 i = 0; i < n; i++)
                    {
                        global::System.Web.Routing.RouteBase route = this[i];
                        if (route == null) { continue; }
                        global::System.Web.Routing.VirtualPathData vpd = route.GetVirtualPath(requestContext, values);
                        if (vpd != null) { data = vpd; break; }
                    }
                }
                if (data == null) { return null; }
                data.VirtualPath = NormalizeVirtualPath(requestContext, data.VirtualPath);
                return data;
            }
        }

        private global::System.String NormalizeVirtualPath(global::System.Web.Routing.RequestContext requestContext, global::System.String virtualPath)
        {
            if (virtualPath == null) { return null; }
            global::System.String url = virtualPath;
            if (_lowercaseUrls)
            {
                global::System.Int32 q = url.IndexOf('?');
                if (q >= 0)
                {
                    url = url.Substring(0, q).ToLowerInvariant() + url.Substring(q);
                }
                else
                {
                    url = url.ToLowerInvariant();
                }
            }
            if (_appendTrailingSlash)
            {
                global::System.Int32 q = url.IndexOf('?');
                global::System.String pathPart = q >= 0 ? url.Substring(0, q) : url;
                global::System.String queryPart = q >= 0 ? url.Substring(q) : global::System.String.Empty;
                if (pathPart.Length > 0 && !pathPart.EndsWith("/", global::System.StringComparison.Ordinal))
                {
                    pathPart = pathPart + "/";
                }
                url = pathPart + queryPart;
            }
            // Make the route-relative url application-absolute ("~/foo" -> "/app/foo").
            global::System.String appPath = null;
            if (requestContext != null && requestContext.HttpContext != null && requestContext.HttpContext.Request != null)
            {
                appPath = requestContext.HttpContext.Request.ApplicationPath;
            }
            if (appPath == null) { appPath = "/"; }
            if (url.StartsWith("~/", global::System.StringComparison.Ordinal))
            {
                global::System.String rest = url.Substring(2);
                if (appPath.EndsWith("/", global::System.StringComparison.Ordinal))
                {
                    url = appPath + rest;
                }
                else
                {
                    url = appPath + "/" + rest;
                }
            }
            return url;
        }

        public void Ignore(global::System.String url)
        {
            Ignore(url, null);
        }
        public void Ignore(global::System.String url, global::System.Object constraints)
        {
            if (url == null) { throw new global::System.ArgumentNullException("url"); }
            global::System.Web.Routing.Route route = new global::System.Web.Routing.Route(url, new global::System.Web.Routing.StopRoutingHandler());
            route.Constraints = new global::System.Web.Routing.RouteValueDictionary(constraints);
            Add(route);
        }

        protected override void InsertItem(global::System.Int32 index, global::System.Web.Routing.RouteBase item)
        {
            if (item == null) { throw new global::System.ArgumentNullException("item"); }
            if (base.Contains(item))
            {
                throw new global::System.ArgumentException("The route already exists in the route collection.", "item");
            }
            base.InsertItem(index, item);
        }
        protected override void RemoveItem(global::System.Int32 index)
        {
            RemoveFromNamedMap(this[index]);
            base.RemoveItem(index);
        }
        protected override void SetItem(global::System.Int32 index, global::System.Web.Routing.RouteBase item)
        {
            if (item == null) { throw new global::System.ArgumentNullException("item"); }
            RemoveFromNamedMap(this[index]);
            base.SetItem(index, item);
        }
        private void RemoveFromNamedMap(global::System.Web.Routing.RouteBase route)
        {
            if (route == null) { return; }
            global::System.String found = null;
            foreach (global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Web.Routing.RouteBase> kvp in _namedMap)
            {
                if (object.ReferenceEquals(kvp.Value, route)) { found = kvp.Key; break; }
            }
            if (found != null) { _namedMap.Remove(found); }
        }

        public global::System.Boolean AppendTrailingSlash
        {
            get { return _appendTrailingSlash; }
            set { _appendTrailingSlash = value; }
        }
        public global::System.Boolean LowercaseUrls
        {
            get { return _lowercaseUrls; }
            set { _lowercaseUrls = value; }
        }
        public global::System.Boolean RouteExistingFiles
        {
            get { return _routeExistingFiles; }
            set { _routeExistingFiles = value; }
        }
        public global::System.Web.Routing.RouteBase this[global::System.String name]
        {
            get
            {
                if (global::System.String.IsNullOrEmpty(name)) { return null; }
                global::System.Web.Routing.RouteBase route;
                _namedMap.TryGetValue(name, out route);
                return route;
            }
        }

        private sealed class ReadLockDisposable : global::System.IDisposable
        {
            private readonly global::System.Threading.ReaderWriterLockSlim _lock;
            public ReadLockDisposable(global::System.Threading.ReaderWriterLockSlim l) { _lock = l; }
            public void Dispose() { _lock.ExitReadLock(); }
        }
        private sealed class WriteLockDisposable : global::System.IDisposable
        {
            private readonly global::System.Threading.ReaderWriterLockSlim _lock;
            public WriteLockDisposable(global::System.Threading.ReaderWriterLockSlim l) { _lock = l; }
            public void Dispose() { _lock.ExitWriteLock(); }
        }
    }
    public class RouteData
    {
        private global::System.Web.Routing.RouteBase _route;
        private global::System.Web.Routing.IRouteHandler _routeHandler;
        private readonly global::System.Web.Routing.RouteValueDictionary _values = new global::System.Web.Routing.RouteValueDictionary();
        private readonly global::System.Web.Routing.RouteValueDictionary _dataTokens = new global::System.Web.Routing.RouteValueDictionary();

        public RouteData() { }
        public RouteData(global::System.Web.Routing.RouteBase route, global::System.Web.Routing.IRouteHandler routeHandler)
        {
            _route = route;
            _routeHandler = routeHandler;
        }
        public global::System.String GetRequiredString(global::System.String valueName)
        {
            global::System.Object value;
            if (_values.TryGetValue(valueName, out value))
            {
                global::System.String s = value as global::System.String;
                if (!global::System.String.IsNullOrEmpty(s))
                {
                    return s;
                }
            }
            throw new global::System.InvalidOperationException(
                "The RouteData must contain an item named '" + valueName + "' with a string value.");
        }
        public global::System.Web.Routing.RouteValueDictionary DataTokens { get { return _dataTokens; } }
        public global::System.Web.Routing.RouteBase Route { get { return _route; } set { _route = value; } }
        public global::System.Web.Routing.IRouteHandler RouteHandler { get { return _routeHandler; } set { _routeHandler = value; } }
        public global::System.Web.Routing.RouteValueDictionary Values { get { return _values; } }
    }
    public enum RouteDirection
    {
        IncomingRequest = 0,
        UrlGeneration = 1,
    }
    public class RouteTable
    {
        private static readonly global::System.Web.Routing.RouteCollection s_routes = new global::System.Web.Routing.RouteCollection();
        public RouteTable() { }
        public static global::System.Web.Routing.RouteCollection Routes { get { return s_routes; } }
    }
    public class RouteValueDictionary : global::System.Collections.Generic.IDictionary<global::System.String, global::System.Object>, global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>>, global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>>, global::System.Collections.IEnumerable
    {
        private readonly global::System.Collections.Generic.Dictionary<global::System.String, global::System.Object> _dictionary;
        public RouteValueDictionary()
        {
            _dictionary = new global::System.Collections.Generic.Dictionary<global::System.String, global::System.Object>(global::System.StringComparer.OrdinalIgnoreCase);
        }
        public RouteValueDictionary(global::System.Object values)
        {
            _dictionary = new global::System.Collections.Generic.Dictionary<global::System.String, global::System.Object>(global::System.StringComparer.OrdinalIgnoreCase);
            if (values != null)
            {
                global::System.Collections.Generic.IDictionary<global::System.String, global::System.Object> asDict =
                    values as global::System.Collections.Generic.IDictionary<global::System.String, global::System.Object>;
                if (asDict != null)
                {
                    foreach (global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object> kvp in asDict)
                    {
                        _dictionary.Add(kvp.Key, kvp.Value);
                    }
                }
                else
                {
                    foreach (global::System.ComponentModel.PropertyDescriptor prop in
                        global::System.ComponentModel.TypeDescriptor.GetProperties(values))
                    {
                        global::System.Object val = prop.GetValue(values);
                        _dictionary.Add(prop.Name, val);
                    }
                }
            }
        }
        public RouteValueDictionary(global::System.Collections.Generic.IDictionary<global::System.String, global::System.Object> dictionary)
        {
            if (dictionary != null)
            {
                _dictionary = new global::System.Collections.Generic.Dictionary<global::System.String, global::System.Object>(dictionary, global::System.StringComparer.OrdinalIgnoreCase);
            }
            else
            {
                _dictionary = new global::System.Collections.Generic.Dictionary<global::System.String, global::System.Object>(global::System.StringComparer.OrdinalIgnoreCase);
            }
        }
        public void Add(global::System.String key, global::System.Object value) { _dictionary.Add(key, value); }
        public void Clear() { _dictionary.Clear(); }
        public global::System.Boolean ContainsKey(global::System.String key) { return _dictionary.ContainsKey(key); }
        public global::System.Boolean ContainsValue(global::System.Object value) { return _dictionary.ContainsValue(value); }
        public global::System.Collections.Generic.Dictionary<global::System.String, global::System.Object>.Enumerator GetEnumerator() { return _dictionary.GetEnumerator(); }
        public global::System.Boolean Remove(global::System.String key) { return _dictionary.Remove(key); }
        public global::System.Boolean TryGetValue(global::System.String key, out global::System.Object value) { return _dictionary.TryGetValue(key, out value); }
        void global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>>.Add(global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object> item)
        {
            ((global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>>)_dictionary).Add(item);
        }
        global::System.Boolean global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>>.Contains(global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object> item)
        {
            return ((global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>>)_dictionary).Contains(item);
        }
        void global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>>.CopyTo(global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>[] array, global::System.Int32 arrayIndex)
        {
            ((global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>>)_dictionary).CopyTo(array, arrayIndex);
        }
        global::System.Boolean global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>>.Remove(global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object> item)
        {
            return ((global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>>)_dictionary).Remove(item);
        }
        global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>> global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>>.GetEnumerator()
        {
            return _dictionary.GetEnumerator();
        }
        global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator()
        {
            return _dictionary.GetEnumerator();
        }
        public global::System.Int32 Count { get { return _dictionary.Count; } }
        public global::System.Collections.Generic.Dictionary<global::System.String, global::System.Object>.KeyCollection Keys { get { return _dictionary.Keys; } }
        public global::System.Collections.Generic.Dictionary<global::System.String, global::System.Object>.ValueCollection Values { get { return _dictionary.Values; } }
        public global::System.Object this[global::System.String key]
        {
            get { global::System.Object value; _dictionary.TryGetValue(key, out value); return value; }
            set { _dictionary[key] = value; }
        }
        global::System.Collections.Generic.ICollection<global::System.String> global::System.Collections.Generic.IDictionary<global::System.String, global::System.Object>.Keys { get { return _dictionary.Keys; } }
        global::System.Collections.Generic.ICollection<global::System.Object> global::System.Collections.Generic.IDictionary<global::System.String, global::System.Object>.Values { get { return _dictionary.Values; } }
        global::System.Boolean global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>>.IsReadOnly
        {
            get { return ((global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>>)_dictionary).IsReadOnly; }
        }
    }
    public class StopRoutingHandler : global::System.Web.Routing.IRouteHandler
    {
        public StopRoutingHandler() { }
        protected virtual global::System.Web.IHttpHandler GetHttpHandler(global::System.Web.Routing.RequestContext requestContext)
        {
            // Sentinel handler: presence of a StopRoutingHandler tells UrlRoutingModule to bypass
            // routing entirely for this request. It is never actually executed.
            throw new global::System.NotSupportedException();
        }
        global::System.Web.IHttpHandler global::System.Web.Routing.IRouteHandler.GetHttpHandler(global::System.Web.Routing.RequestContext requestContext)
        {
            return GetHttpHandler(requestContext);
        }
    }
    public abstract class UrlRoutingHandler : global::System.Web.IHttpHandler
    {
        private global::System.Web.Routing.RouteCollection _routeCollection;
        protected UrlRoutingHandler() { }
        protected virtual void ProcessRequest(global::System.Web.HttpContext httpContext)
        {
            if (httpContext == null) { throw new global::System.ArgumentNullException("httpContext"); }
            ProcessRequest(global::System.Web.Routing.RoutingHttpContextWrapper.Wrap(httpContext));
        }
        protected virtual void ProcessRequest(global::System.Web.HttpContextBase httpContext)
        {
            if (httpContext == null) { throw new global::System.ArgumentNullException("httpContext"); }
            global::System.Web.Routing.RouteData routeData = RouteCollection.GetRouteData(httpContext);
            if (routeData == null)
            {
                throw new global::System.Web.HttpException(404, "The incoming request does not match any route.");
            }
            global::System.Web.Routing.IRouteHandler routeHandler = routeData.RouteHandler;
            if (routeHandler == null)
            {
                throw new global::System.InvalidOperationException("The matched route does not have a route handler.");
            }
            if (routeHandler is global::System.Web.Routing.StopRoutingHandler)
            {
                throw new global::System.InvalidOperationException("A StopRoutingHandler was matched.");
            }
            global::System.Web.Routing.RequestContext requestContext =
                new global::System.Web.Routing.RequestContext(httpContext, routeData);
            global::System.Web.IHttpHandler httpHandler = routeHandler.GetHttpHandler(requestContext);
            if (httpHandler == null)
            {
                throw new global::System.InvalidOperationException("The route handler returned a null HTTP handler.");
            }
            VerifyAndProcessRequest(httpHandler, httpContext);
        }
        protected abstract void VerifyAndProcessRequest(global::System.Web.IHttpHandler httpHandler, global::System.Web.HttpContextBase httpContext);
        void global::System.Web.IHttpHandler.ProcessRequest(global::System.Web.HttpContext context)
        {
            ProcessRequest(context);
        }
        protected virtual global::System.Boolean IsReusable { get { return false; } }
        public global::System.Web.Routing.RouteCollection RouteCollection
        {
            get
            {
                if (_routeCollection == null)
                {
                    _routeCollection = global::System.Web.Routing.RouteTable.Routes;
                }
                return _routeCollection;
            }
            set { _routeCollection = value; }
        }
        global::System.Boolean global::System.Web.IHttpHandler.IsReusable { get { return IsReusable; } }
    }
    public class UrlRoutingModule : global::System.Web.IHttpModule
    {
        private global::System.Web.Routing.RouteCollection _routeCollection;
        public UrlRoutingModule() { }
        protected virtual void Dispose() { }
        protected virtual void Init(global::System.Web.HttpApplication application)
        {
            if (application == null) { throw new global::System.ArgumentNullException("application"); }
            application.PostResolveRequestCache += OnApplicationPostResolveRequestCache;
        }
        private void OnApplicationPostResolveRequestCache(global::System.Object sender, global::System.EventArgs e)
        {
            global::System.Web.HttpApplication app = (global::System.Web.HttpApplication)sender;
            global::System.Web.HttpContext context = app.Context;
            if (context == null) { return; }
            PostResolveRequestCache(global::System.Web.Routing.RoutingHttpContextWrapper.Wrap(context));
        }
        public virtual void PostMapRequestHandler(global::System.Web.HttpContextBase context) { }
        public virtual void PostResolveRequestCache(global::System.Web.HttpContextBase context)
        {
            if (context == null) { throw new global::System.ArgumentNullException("context"); }
            global::System.Web.Routing.RouteData routeData = RouteCollection.GetRouteData(context);
            if (routeData == null) { return; }
            global::System.Web.Routing.IRouteHandler routeHandler = routeData.RouteHandler;
            if (routeHandler == null)
            {
                throw new global::System.InvalidOperationException(
                    "A route handler was not assigned to the matched route. Make sure that every Route has a RouteHandler.");
            }
            if (routeHandler is global::System.Web.Routing.StopRoutingHandler)
            {
                // Routing explicitly disabled for this request: leave the handler unmapped.
                return;
            }
            global::System.Web.Routing.RequestContext requestContext =
                new global::System.Web.Routing.RequestContext(context, routeData);
            // Surface the RouteData to the rest of the request through Request.RequestContext.
            global::System.Web.Routing.RoutingHttpContextWrapper.AttachRequestContext(context, requestContext);
            global::System.Web.IHttpHandler httpHandler = routeHandler.GetHttpHandler(requestContext);
            if (httpHandler == null)
            {
                throw new global::System.InvalidOperationException(
                    "The route handler '" + routeHandler.GetType().FullName + "' did not return an IHttpHandler.");
            }
            context.RemapHandler(httpHandler);
        }
        void global::System.Web.IHttpModule.Dispose() { Dispose(); }
        void global::System.Web.IHttpModule.Init(global::System.Web.HttpApplication application) { Init(application); }
        public global::System.Web.Routing.RouteCollection RouteCollection
        {
            get
            {
                if (_routeCollection == null)
                {
                    _routeCollection = global::System.Web.Routing.RouteTable.Routes;
                }
                return _routeCollection;
            }
            set { _routeCollection = value; }
        }
    }
    public class VirtualPathData
    {
        private global::System.Web.Routing.RouteBase _route;
        private global::System.String _virtualPath;
        private readonly global::System.Web.Routing.RouteValueDictionary _dataTokens = new global::System.Web.Routing.RouteValueDictionary();
        public VirtualPathData(global::System.Web.Routing.RouteBase route, global::System.String virtualPath)
        {
            _route = route;
            _virtualPath = virtualPath;
        }
        public global::System.Web.Routing.RouteValueDictionary DataTokens { get { return _dataTokens; } }
        public global::System.Web.Routing.RouteBase Route { get { return _route; } set { _route = value; } }
        public global::System.String VirtualPath
        {
            get { return _virtualPath == null ? global::System.String.Empty : _virtualPath; }
            set { _virtualPath = value; }
        }
    }
    public class PageRouteHandler : global::System.Web.Routing.IRouteHandler
    {
        private readonly global::System.String _virtualPath;
        private readonly global::System.Boolean _checkPhysicalUrlAccess;
        public PageRouteHandler(global::System.String virtualPath) : this(virtualPath, true) { }
        public PageRouteHandler(global::System.String virtualPath, global::System.Boolean checkPhysicalUrlAccess)
        {
            if (global::System.String.IsNullOrEmpty(virtualPath) || !virtualPath.StartsWith("~/", global::System.StringComparison.OrdinalIgnoreCase))
            {
                throw new global::System.ArgumentException(
                    "The virtual path must be rooted; it must begin with \"~/\".", "virtualPath");
            }
            _virtualPath = virtualPath;
            _checkPhysicalUrlAccess = checkPhysicalUrlAccess;
        }
        public virtual global::System.Web.IHttpHandler GetHttpHandler(global::System.Web.Routing.RequestContext requestContext)
        {
            if (requestContext == null) { throw new global::System.ArgumentNullException("requestContext"); }
            global::System.String virtualPath = GetSubstitutedVirtualPath(requestContext);
            global::System.Object handler = global::System.Web.Compilation.BuildManager.CreateInstanceFromVirtualPath(
                virtualPath, typeof(global::System.Web.IHttpHandler));
            return handler as global::System.Web.IHttpHandler;
        }
        public global::System.String GetSubstitutedVirtualPath(global::System.Web.Routing.RequestContext requestContext)
        {
            if (requestContext == null) { throw new global::System.ArgumentNullException("requestContext"); }
            // The page virtual path may itself contain {parameter} tokens; substitute from route values.
            if (_virtualPath.IndexOf('{') < 0) { return _virtualPath; }
            global::System.Web.Routing.RouteData routeData = requestContext.RouteData;
            if (routeData == null) { return _virtualPath; }
            global::System.Web.Routing.Route route = routeData.Route as global::System.Web.Routing.Route;
            if (route == null) { return _virtualPath; }
            global::System.Web.Routing.VirtualPathData vpd = route.GetVirtualPath(requestContext, routeData.Values);
            if (vpd == null) { return _virtualPath; }
            // GetVirtualPath returns the bound url; for substituted page paths we reuse the configured
            // physical path with parameters replaced from current route values.
            global::System.String result = _virtualPath;
            foreach (global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object> kvp in routeData.Values)
            {
                result = result.Replace("{" + kvp.Key + "}", global::System.Convert.ToString(kvp.Value, global::System.Globalization.CultureInfo.InvariantCulture));
            }
            return result;
        }
        public global::System.String VirtualPath { get { return _virtualPath; } }
        public global::System.Boolean CheckPhysicalUrlAccess { get { return _checkPhysicalUrlAccess; } }
    }

    // ----- Internal routing engine: URL pattern parsing, matching, and binding -----

    // A lightweight HttpContextBase wrapper used by routing to operate on a real HttpContext when
    // crossing the HttpContextBase-typed routing surface. Only the members routing relies on are
    // implemented; everything else inherits the (throwing) base behavior.
    internal sealed class RoutingHttpContextWrapper : global::System.Web.HttpContextBase
    {
        private readonly global::System.Web.HttpContext _context;
        private readonly global::System.Web.Routing.RoutingHttpRequestWrapper _request;
        private RoutingHttpContextWrapper(global::System.Web.HttpContext context)
        {
            _context = context;
            _request = new global::System.Web.Routing.RoutingHttpRequestWrapper(context == null ? null : context.Request);
        }
        internal static global::System.Web.HttpContextBase Wrap(global::System.Web.HttpContext context)
        {
            return new global::System.Web.Routing.RoutingHttpContextWrapper(context);
        }
        internal static void AttachRequestContext(global::System.Web.HttpContextBase context, global::System.Web.Routing.RequestContext requestContext)
        {
            global::System.Web.Routing.RoutingHttpContextWrapper wrapper = context as global::System.Web.Routing.RoutingHttpContextWrapper;
            global::System.Web.HttpContext real = wrapper != null ? wrapper._context : null;
            if (real == null) { real = global::System.Web.HttpContext.Current; }
            if (real != null && real.Request != null)
            {
                real.Request.RequestContext = requestContext;
            }
        }
        public override global::System.Web.HttpRequestBase Request { get { return _request; } }
        public override void RemapHandler(global::System.Web.IHttpHandler handler)
        {
            if (_context != null) { _context.RemapHandler(handler); }
        }
        public override global::System.Collections.IDictionary Items
        {
            get { return _context == null ? null : _context.Items; }
        }
        public override global::System.Object GetService(global::System.Type serviceType)
        {
            return _context == null ? null : ((global::System.IServiceProvider)_context).GetService(serviceType);
        }
    }

    internal sealed class RoutingHttpRequestWrapper : global::System.Web.HttpRequestBase
    {
        private readonly global::System.Web.HttpRequest _request;
        internal RoutingHttpRequestWrapper(global::System.Web.HttpRequest request) { _request = request; }
        public override global::System.String AppRelativeCurrentExecutionFilePath
        {
            get { return _request == null ? null : _request.AppRelativeCurrentExecutionFilePath; }
        }
        public override global::System.String PathInfo
        {
            get { return _request == null ? global::System.String.Empty : _request.PathInfo; }
        }
        public override global::System.String ApplicationPath
        {
            get { return _request == null ? null : _request.ApplicationPath; }
        }
        public override global::System.String HttpMethod
        {
            get { return _request == null ? null : _request.HttpMethod; }
        }
        public override global::System.String MapPath(global::System.String virtualPath)
        {
            return _request == null ? null : _request.MapPath(virtualPath);
        }
        public override global::System.Web.Routing.RequestContext RequestContext
        {
            get { return _request == null ? null : _request.RequestContext; }
            set { if (_request != null) { _request.RequestContext = value; } }
        }
    }

    // Parsed representation of a route URL pattern, e.g. "products/{category}/{id}" or
    // "files/{*path}". Segments are separated by '/'. Each segment is either a literal or a
    // single parameter ("{name}" or catch-all "{*name}").
    internal sealed class ParsedRoute
    {
        private readonly global::System.Collections.Generic.List<global::System.Web.Routing.PathSegment> _segments;
        private ParsedRoute(global::System.Collections.Generic.List<global::System.Web.Routing.PathSegment> segments)
        {
            _segments = segments;
        }

        internal static global::System.Web.Routing.ParsedRoute Parse(global::System.String url)
        {
            if (url == null) { url = global::System.String.Empty; }
            if (url.StartsWith("~/", global::System.StringComparison.Ordinal)) { url = url.Substring(2); }
            else if (url.StartsWith("/", global::System.StringComparison.Ordinal)) { url = url.Substring(1); }
            if (url.StartsWith("~", global::System.StringComparison.Ordinal))
            {
                throw new global::System.ArgumentException("The route URL cannot start with a '~' character.", "url");
            }
            if (url.IndexOf('?') >= 0)
            {
                throw new global::System.ArgumentException("The route URL cannot contain a '?' character.", "url");
            }

            global::System.Collections.Generic.List<global::System.Web.Routing.PathSegment> segments =
                new global::System.Collections.Generic.List<global::System.Web.Routing.PathSegment>();
            if (url.Length > 0)
            {
                global::System.String[] parts = url.Split('/');
                for (global::System.Int32 i = 0; i < parts.Length; i++)
                {
                    global::System.String part = parts[i];
                    global::System.Web.Routing.PathSegment seg = new global::System.Web.Routing.PathSegment();
                    if (part.Length >= 2 && part[0] == '{' && part[part.Length - 1] == '}')
                    {
                        global::System.String name = part.Substring(1, part.Length - 2);
                        if (name.Length > 0 && name[0] == '*')
                        {
                            seg.IsCatchAll = true;
                            seg.ParameterName = name.Substring(1);
                        }
                        else
                        {
                            seg.ParameterName = name;
                        }
                        seg.IsParameter = true;
                        if (global::System.String.IsNullOrEmpty(seg.ParameterName))
                        {
                            throw new global::System.ArgumentException("An empty URL parameter name is not allowed.", "url");
                        }
                    }
                    else
                    {
                        seg.Literal = part;
                    }
                    segments.Add(seg);
                }
            }
            return new global::System.Web.Routing.ParsedRoute(segments);
        }

        // Returns null when no match; otherwise a dictionary of captured values merged with defaults.
        internal global::System.Web.Routing.RouteValueDictionary Match(global::System.String requestPath, global::System.Web.Routing.RouteValueDictionary defaults)
        {
            if (requestPath == null) { requestPath = global::System.String.Empty; }
            global::System.String[] requestSegments = requestPath.Length == 0
                ? global::System.Array.Empty<global::System.String>()
                : requestPath.Split('/');

            global::System.Web.Routing.RouteValueDictionary values = new global::System.Web.Routing.RouteValueDictionary();

            global::System.Int32 r = 0;
            for (global::System.Int32 s = 0; s < _segments.Count; s++)
            {
                global::System.Web.Routing.PathSegment seg = _segments[s];
                if (seg.IsCatchAll)
                {
                    // Capture all remaining segments (may be empty).
                    if (r < requestSegments.Length)
                    {
                        global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder();
                        for (global::System.Int32 k = r; k < requestSegments.Length; k++)
                        {
                            if (k > r) { sb.Append('/'); }
                            sb.Append(requestSegments[k]);
                        }
                        values[seg.ParameterName] = sb.ToString();
                    }
                    else
                    {
                        values[seg.ParameterName] = GetDefault(defaults, seg.ParameterName);
                    }
                    r = requestSegments.Length;
                    return MergeDefaults(values, defaults);
                }

                if (r < requestSegments.Length && requestSegments[r].Length > 0)
                {
                    if (seg.IsParameter)
                    {
                        values[seg.ParameterName] = requestSegments[r];
                    }
                    else
                    {
                        if (!global::System.String.Equals(seg.Literal, requestSegments[r], global::System.StringComparison.OrdinalIgnoreCase))
                        {
                            return null;
                        }
                    }
                    r++;
                }
                else
                {
                    // No request segment present at this position.
                    if (seg.IsParameter)
                    {
                        if (HasDefault(defaults, seg.ParameterName))
                        {
                            values[seg.ParameterName] = GetDefault(defaults, seg.ParameterName);
                        }
                        else
                        {
                            return null;
                        }
                        if (r < requestSegments.Length) { r++; }
                    }
                    else
                    {
                        return null;
                    }
                }
            }

            // Any leftover request segments mean the path is longer than the pattern: no match.
            if (r < requestSegments.Length)
            {
                for (global::System.Int32 k = r; k < requestSegments.Length; k++)
                {
                    if (requestSegments[k].Length > 0) { return null; }
                }
            }
            return MergeDefaults(values, defaults);
        }

        private global::System.Web.Routing.RouteValueDictionary MergeDefaults(global::System.Web.Routing.RouteValueDictionary values, global::System.Web.Routing.RouteValueDictionary defaults)
        {
            if (defaults != null)
            {
                foreach (global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object> kvp in defaults)
                {
                    if (!values.ContainsKey(kvp.Key))
                    {
                        values[kvp.Key] = kvp.Value;
                    }
                }
            }
            return values;
        }
        private static global::System.Boolean HasDefault(global::System.Web.Routing.RouteValueDictionary defaults, global::System.String key)
        {
            return defaults != null && defaults.ContainsKey(key);
        }
        private static global::System.Object GetDefault(global::System.Web.Routing.RouteValueDictionary defaults, global::System.String key)
        {
            if (defaults == null) { return null; }
            global::System.Object v;
            defaults.TryGetValue(key, out v);
            return v;
        }

        // Builds a URL from the provided values (merged over the ambient/current values), applying
        // defaults. Returns null when a required parameter cannot be supplied.
        internal global::System.Web.Routing.BoundUrl Bind(global::System.Web.Routing.RouteValueDictionary currentValues, global::System.Web.Routing.RouteValueDictionary values, global::System.Web.Routing.RouteValueDictionary defaults)
        {
            global::System.Web.Routing.RouteValueDictionary acceptedValues = new global::System.Web.Routing.RouteValueDictionary();
            global::System.Web.Routing.RouteValueDictionary suppliedValues =
                values == null ? new global::System.Web.Routing.RouteValueDictionary() : values;

            global::System.Text.StringBuilder url = new global::System.Text.StringBuilder();
            global::System.Boolean pendingEmpty = false;

            for (global::System.Int32 s = 0; s < _segments.Count; s++)
            {
                global::System.Web.Routing.PathSegment seg = _segments[s];
                if (!seg.IsParameter)
                {
                    if (url.Length > 0 || s > 0) { url.Append('/'); }
                    url.Append(seg.Literal);
                    pendingEmpty = false;
                    continue;
                }

                global::System.Object value;
                global::System.Boolean haveValue = suppliedValues.TryGetValue(seg.ParameterName, out value);
                if (!haveValue && currentValues != null)
                {
                    haveValue = currentValues.TryGetValue(seg.ParameterName, out value);
                }
                global::System.Boolean haveDefault = HasDefault(defaults, seg.ParameterName);
                global::System.Object defaultValue = GetDefault(defaults, seg.ParameterName);

                if (!haveValue)
                {
                    if (haveDefault)
                    {
                        value = defaultValue;
                        haveValue = true;
                    }
                    else if (seg.IsCatchAll)
                    {
                        // Catch-all with no value is allowed and contributes nothing.
                        continue;
                    }
                    else
                    {
                        return null;
                    }
                }
                else
                {
                    acceptedValues[seg.ParameterName] = value;
                }

                global::System.String valueString = global::System.Convert.ToString(value, global::System.Globalization.CultureInfo.InvariantCulture);
                if (global::System.String.IsNullOrEmpty(valueString))
                {
                    // Trailing empty optional segment: drop it (and any following separators).
                    pendingEmpty = true;
                    continue;
                }
                if (url.Length > 0 || s > 0) { url.Append('/'); }
                if (seg.IsCatchAll)
                {
                    url.Append(valueString);
                }
                else
                {
                    url.Append(global::System.Uri.EscapeUriString(valueString));
                }
                pendingEmpty = false;
            }

            // Any explicitly supplied value that is not part of the pattern and differs from its
            // default becomes a query-string argument.
            global::System.Collections.Generic.List<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>> extra =
                new global::System.Collections.Generic.List<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object>>();
            foreach (global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object> kvp in suppliedValues)
            {
                if (IsParameterInPattern(kvp.Key)) { continue; }
                global::System.Object def = GetDefault(defaults, kvp.Key);
                if (def != null && global::System.String.Equals(global::System.Convert.ToString(def), global::System.Convert.ToString(kvp.Value), global::System.StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }
                if (kvp.Value == null) { continue; }
                extra.Add(kvp);
            }

            global::System.String result = url.ToString();
            if (result.Length == 0) { result = global::System.String.Empty; }
            global::System.String finalUrl = "~/" + result;

            if (extra.Count > 0)
            {
                global::System.Text.StringBuilder qs = new global::System.Text.StringBuilder();
                global::System.Boolean first = true;
                foreach (global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object> kvp in extra)
                {
                    qs.Append(first ? '?' : '&');
                    first = false;
                    qs.Append(global::System.Uri.EscapeDataString(kvp.Key));
                    qs.Append('=');
                    qs.Append(global::System.Uri.EscapeDataString(global::System.Convert.ToString(kvp.Value, global::System.Globalization.CultureInfo.InvariantCulture)));
                }
                finalUrl = finalUrl + qs.ToString();
            }

            global::System.Web.Routing.BoundUrl bound = new global::System.Web.Routing.BoundUrl();
            bound.Url = finalUrl;
            bound.Values = MergeForConstraints(suppliedValues, currentValues, defaults);
            return bound;
        }

        private global::System.Web.Routing.RouteValueDictionary MergeForConstraints(global::System.Web.Routing.RouteValueDictionary supplied, global::System.Web.Routing.RouteValueDictionary current, global::System.Web.Routing.RouteValueDictionary defaults)
        {
            global::System.Web.Routing.RouteValueDictionary merged = new global::System.Web.Routing.RouteValueDictionary();
            if (defaults != null)
            {
                foreach (global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object> kvp in defaults) { merged[kvp.Key] = kvp.Value; }
            }
            if (current != null)
            {
                foreach (global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object> kvp in current) { merged[kvp.Key] = kvp.Value; }
            }
            if (supplied != null)
            {
                foreach (global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.Object> kvp in supplied) { merged[kvp.Key] = kvp.Value; }
            }
            return merged;
        }

        private global::System.Boolean IsParameterInPattern(global::System.String name)
        {
            for (global::System.Int32 i = 0; i < _segments.Count; i++)
            {
                global::System.Web.Routing.PathSegment seg = _segments[i];
                if (seg.IsParameter && global::System.String.Equals(seg.ParameterName, name, global::System.StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }
            return false;
        }
    }

    internal sealed class PathSegment
    {
        internal global::System.Boolean IsParameter;
        internal global::System.Boolean IsCatchAll;
        internal global::System.String ParameterName;
        internal global::System.String Literal;
    }

    internal sealed class BoundUrl
    {
        internal global::System.String Url;
        internal global::System.Web.Routing.RouteValueDictionary Values;
    }
}
