// <auto-generated> clean-room System.Web API skeleton.
// Bodies are NotImplementedException; this proves signature completeness only.
#nullable disable
#pragma warning disable

namespace System.Web.Compilation
{
    public abstract class ControlBuilderInterceptor
    {
        protected ControlBuilderInterceptor() { throw new global::System.NotImplementedException(); }
        public virtual void PreControlBuilderInit(global::System.Web.UI.ControlBuilder controlBuilder, global::System.Web.UI.TemplateParser parser, global::System.Web.UI.ControlBuilder parentBuilder, global::System.Type type, global::System.String tagName, global::System.String id, global::System.Collections.IDictionary attributes, global::System.Collections.IDictionary additionalState) { throw new global::System.NotImplementedException(); }
        public virtual void OnProcessGeneratedCode(global::System.Web.UI.ControlBuilder controlBuilder, global::System.CodeDom.CodeCompileUnit codeCompileUnit, global::System.CodeDom.CodeTypeDeclaration baseType, global::System.CodeDom.CodeTypeDeclaration derivedType, global::System.CodeDom.CodeMemberMethod buildMethod, global::System.CodeDom.CodeMemberMethod dataBindingMethod, global::System.Collections.IDictionary additionalState) { throw new global::System.NotImplementedException(); }
    }
    public class AppSettingsExpressionBuilder : global::System.Web.Compilation.ExpressionBuilder
    {
        public AppSettingsExpressionBuilder() { throw new global::System.NotImplementedException(); }
        public override global::System.CodeDom.CodeExpression GetCodeExpression(global::System.Web.UI.BoundPropertyEntry entry, global::System.Object parsedData, global::System.Web.Compilation.ExpressionBuilderContext context) { throw new global::System.NotImplementedException(); }
        public override global::System.Object EvaluateExpression(global::System.Object target, global::System.Web.UI.BoundPropertyEntry entry, global::System.Object parsedData, global::System.Web.Compilation.ExpressionBuilderContext context) { throw new global::System.NotImplementedException(); }
        public static global::System.Object GetAppSetting(global::System.String key) { throw new global::System.NotImplementedException(); }
        public static global::System.Object GetAppSetting(global::System.String key, global::System.Type targetType, global::System.String propertyName) { throw new global::System.NotImplementedException(); }
        public override global::System.Boolean SupportsEvaluate { get { throw new global::System.NotImplementedException(); } }
    }
    public class AssemblyBuilder
    {
        internal AssemblyBuilder() { throw new global::System.NotImplementedException(); }
        public void AddAssemblyReference(global::System.Reflection.Assembly a) { throw new global::System.NotImplementedException(); }
        public global::System.IO.TextWriter CreateCodeFile(global::System.Web.Compilation.BuildProvider buildProvider) { throw new global::System.NotImplementedException(); }
        public void AddCodeCompileUnit(global::System.Web.Compilation.BuildProvider buildProvider, global::System.CodeDom.CodeCompileUnit compileUnit) { throw new global::System.NotImplementedException(); }
        public void GenerateTypeFactory(global::System.String typeName) { throw new global::System.NotImplementedException(); }
        public global::System.IO.Stream CreateEmbeddedResource(global::System.Web.Compilation.BuildProvider buildProvider, global::System.String name) { throw new global::System.NotImplementedException(); }
        public global::System.String GetTempFilePhysicalPath(global::System.String extension) { throw new global::System.NotImplementedException(); }
        public global::System.CodeDom.Compiler.CodeDomProvider CodeDomProvider { get { throw new global::System.NotImplementedException(); } }
    }
    public sealed class BuildDependencySet
    {
        internal BuildDependencySet() { throw new global::System.NotImplementedException(); }
        public global::System.String HashCode { get { throw new global::System.NotImplementedException(); } }
        public global::System.Collections.IEnumerable VirtualPaths { get { throw new global::System.NotImplementedException(); } }
    }
    public sealed class BuildManager
    {
        internal BuildManager() { throw new global::System.NotImplementedException(); }
        public static void AddReferencedAssembly(global::System.Reflection.Assembly assembly) { global::System.Web.Compilation.BuildManagerEngine.AddReferencedAssembly(assembly); }
        public static global::System.Collections.ICollection GetReferencedAssemblies() { return global::System.Web.Compilation.BuildManagerEngine.GetReferencedAssemblies(); }
        public static void AddCompilationDependency(global::System.String dependency) { /* dependency tracking is a document-stub */ }
        public static global::System.Type GetType(global::System.String typeName, global::System.Boolean throwOnError) { return GetType(typeName, throwOnError, false); }
        public static global::System.Type GetType(global::System.String typeName, global::System.Boolean throwOnError, global::System.Boolean ignoreCase)
        {
            if (typeName == null) { if (throwOnError) { throw new global::System.ArgumentNullException("typeName"); } return null; }
            global::System.Type t = global::System.Type.GetType(typeName, false, ignoreCase);
            if (t == null)
            {
                global::System.Reflection.Assembly[] asms = global::System.AppDomain.CurrentDomain.GetAssemblies();
                for (global::System.Int32 i = 0; i < asms.Length; i++)
                {
                    try { t = asms[i].GetType(typeName, false, ignoreCase); } catch (global::System.Exception) { t = null; }
                    if (t != null) { break; }
                }
            }
            if (t == null && throwOnError) { throw new global::System.Web.HttpException("Could not load type '" + typeName + "'."); }
            return t;
        }
        public static global::System.Type GetGlobalAsaxType()
        {
            global::System.Type t = global::System.Web.Compilation.BuildManagerEngine.GetGlobalAsaxType();
            return t != null ? t : typeof(global::System.Web.HttpApplication);
        }
        public static global::System.Collections.ICollection GetVirtualPathDependencies(global::System.String virtualPath) { return new global::System.Collections.ArrayList(); }
        public static global::System.Type GetCompiledType(global::System.String virtualPath) { return global::System.Web.Compilation.BuildManagerEngine.GetCompiledType(virtualPath); }
        public static global::System.Object CreateInstanceFromVirtualPath(global::System.String virtualPath, global::System.Type requiredBaseType) { return global::System.Web.Compilation.BuildManagerEngine.CreateInstanceFromVirtualPath(virtualPath, requiredBaseType); }
        public static global::System.Web.Util.IWebObjectFactory GetObjectFactory(global::System.String virtualPath, global::System.Boolean throwIfNotFound) { throw new global::System.NotImplementedException(); }
        public static global::System.Reflection.Assembly GetCompiledAssembly(global::System.String virtualPath) { return global::System.Web.Compilation.BuildManagerEngine.GetCompiledAssembly(virtualPath); }
        public static global::System.String GetCompiledCustomString(global::System.String virtualPath) { return global::System.Web.Compilation.BuildManagerEngine.GetCompiledCustomString(virtualPath); }
        public static global::System.Web.Compilation.BuildDependencySet GetCachedBuildDependencySet(global::System.Web.HttpContext context, global::System.String virtualPath) { throw new global::System.NotImplementedException(); }
        public static global::System.Web.Compilation.BuildDependencySet GetCachedBuildDependencySet(global::System.Web.HttpContext context, global::System.String virtualPath, global::System.Boolean ensureIsUpToDate) { throw new global::System.NotImplementedException(); }
        public static global::System.IO.Stream CreateCachedFile(global::System.String fileName) { throw new global::System.NotImplementedException(); }
        public static global::System.IO.Stream ReadCachedFile(global::System.String fileName) { throw new global::System.NotImplementedException(); }
        public static global::System.Collections.IList CodeAssemblies { get { throw new global::System.NotImplementedException(); } }
        public static global::System.Nullable<global::System.Boolean> BatchCompilationEnabled { get { throw new global::System.NotImplementedException(); } set { throw new global::System.NotImplementedException(); } }
        public static global::System.Boolean IsPrecompiledApp { get { throw new global::System.NotImplementedException(); } }
        public static global::System.Boolean IsUpdatablePrecompiledApp { get { throw new global::System.NotImplementedException(); } }
        public static global::System.Runtime.Versioning.FrameworkName TargetFramework { get { throw new global::System.NotImplementedException(); } }
    }
    public enum BuildProviderResultFlags
    {
        Default = 0,
        ShutdownAppDomainOnChange = 1,
    }
    public abstract class BuildProvider
    {
        private global::System.String _virtualPath;
        private global::System.String _physicalPath;
        private global::System.Collections.ArrayList _referencedAssemblies;
        private static readonly global::System.Collections.Hashtable s_registered =
            new global::System.Collections.Hashtable(global::System.StringComparer.OrdinalIgnoreCase);

        protected BuildProvider() { }

        // Internal hook so the BuildManager/host can configure the source path before GenerateCode.
        internal void SetVirtualPath(global::System.String virtualPath, global::System.String physicalPath)
        {
            _virtualPath = virtualPath;
            _physicalPath = physicalPath;
        }

        public virtual void GenerateCode(global::System.Web.Compilation.AssemblyBuilder assemblyBuilder) { }
        public virtual global::System.Type GetGeneratedType(global::System.CodeDom.Compiler.CompilerResults results) { return null; }
        public virtual global::System.String GetCustomString(global::System.CodeDom.Compiler.CompilerResults results) { return null; }
        public virtual global::System.Web.Compilation.BuildProviderResultFlags GetResultFlags(global::System.CodeDom.Compiler.CompilerResults results) { return global::System.Web.Compilation.BuildProviderResultFlags.Default; }
        public virtual void ProcessCompileErrors(global::System.CodeDom.Compiler.CompilerResults results) { }
        protected global::System.IO.Stream OpenStream() { return OpenStream(_virtualPath); }
        protected global::System.IO.Stream OpenStream(global::System.String virtualPath)
        {
            global::System.String path = ResolvePhysical(virtualPath);
            if (path == null || !global::System.IO.File.Exists(path)) { return global::System.IO.Stream.Null; }
            return new global::System.IO.FileStream(path, global::System.IO.FileMode.Open, global::System.IO.FileAccess.Read, global::System.IO.FileShare.Read);
        }
        protected global::System.IO.TextReader OpenReader() { return OpenReader(_virtualPath); }
        protected global::System.IO.TextReader OpenReader(global::System.String virtualPath)
        {
            global::System.IO.Stream s = OpenStream(virtualPath);
            return new global::System.IO.StreamReader(s, global::System.Text.Encoding.UTF8, true);
        }
        private global::System.String ResolvePhysical(global::System.String virtualPath)
        {
            if (_physicalPath != null && (virtualPath == null || global::System.String.Equals(virtualPath, _virtualPath, global::System.StringComparison.OrdinalIgnoreCase)))
            {
                return _physicalPath;
            }
            // Best-effort: treat virtualPath as a relative/absolute filesystem path.
            if (virtualPath != null && global::System.IO.File.Exists(virtualPath)) { return virtualPath; }
            return _physicalPath;
        }
        public static void RegisterBuildProvider(global::System.String extension, global::System.Type providerType)
        {
            if (extension == null) { throw new global::System.ArgumentNullException("extension"); }
            s_registered[extension] = providerType;
        }
        internal static global::System.Type GetRegisteredProviderType(global::System.String extension)
        {
            if (extension == null) { return null; }
            return s_registered[extension] as global::System.Type;
        }
        protected global::System.Web.Compilation.CompilerType GetDefaultCompilerTypeForLanguage(global::System.String language) { return null; }
        protected global::System.Web.Compilation.CompilerType GetDefaultCompilerType() { return null; }
        protected internal virtual global::System.CodeDom.CodeCompileUnit GetCodeCompileUnit(out global::System.Collections.IDictionary linePragmasTable)
        {
            linePragmasTable = new global::System.Collections.Hashtable();
            return null;
        }
        public virtual global::System.Web.Compilation.CompilerType CodeCompilerType { get { return null; } }
        public virtual global::System.Collections.ICollection VirtualPathDependencies { get { return new global::System.Collections.ArrayList(); } }
        protected internal global::System.String VirtualPath { get { return _virtualPath; } }
        protected global::System.Collections.ICollection ReferencedAssemblies
        {
            get
            {
                if (_referencedAssemblies == null) { _referencedAssemblies = new global::System.Collections.ArrayList(); }
                return _referencedAssemblies;
            }
        }
    }
    // Internal build providers that wire the template parser to a virtual path. The codegen +
    // compilation steps live in a later tier; these capture the parsed builder tree + directive
    // metadata so that tier can consume them.
    internal class PageBuildProvider : global::System.Web.Compilation.BuildProvider
    {
        internal PageBuildProvider() { }
        internal global::System.Web.UI.PageParser CreateParser(global::System.String virtualPath)
        {
            global::System.Web.UI.PageParser parser = new global::System.Web.UI.PageParser();
            global::System.IO.TextReader reader = OpenReader(virtualPath != null ? virtualPath : VirtualPath);
            global::System.String text = reader != null ? reader.ReadToEnd() : global::System.String.Empty;
            parser.ParsePageText(text, virtualPath != null ? virtualPath : VirtualPath);
            return parser;
        }
    }
    internal class UserControlBuildProvider : global::System.Web.Compilation.BuildProvider
    {
        internal UserControlBuildProvider() { }
    }
    public enum BuildProviderAppliesTo
    {
        Web = 1,
        Code = 2,
        Resources = 4,
        All = 7,
    }
    public sealed class BuildProviderAppliesToAttribute : global::System.Attribute
    {
        public BuildProviderAppliesToAttribute(global::System.Web.Compilation.BuildProviderAppliesTo appliesTo) { throw new global::System.NotImplementedException(); }
        public global::System.Web.Compilation.BuildProviderAppliesTo AppliesTo { get { throw new global::System.NotImplementedException(); } }
    }
    public enum PrecompilationFlags
    {
        Default = 0,
        Updatable = 1,
        OverwriteTarget = 2,
        ForceDebug = 4,
        Clean = 8,
        CodeAnalysis = 16,
        AllowPartiallyTrustedCallers = 32,
        DelaySign = 64,
        FixedNames = 128,
        IgnoreBadImageFormatException = 256,
    }
    public class ClientBuildManagerParameter
    {
        public ClientBuildManagerParameter() { throw new global::System.NotImplementedException(); }
        public global::System.Collections.Generic.List<global::System.String> ExcludedVirtualPaths { get { throw new global::System.NotImplementedException(); } }
        public global::System.Web.Compilation.PrecompilationFlags PrecompilationFlags { get { throw new global::System.NotImplementedException(); } set { throw new global::System.NotImplementedException(); } }
        public global::System.String StrongNameKeyFile { get { throw new global::System.NotImplementedException(); } set { throw new global::System.NotImplementedException(); } }
        public global::System.String StrongNameKeyContainer { get { throw new global::System.NotImplementedException(); } set { throw new global::System.NotImplementedException(); } }
    }
    public sealed class ClientBuildManager : global::System.MarshalByRefObject, global::System.IDisposable
    {
        public ClientBuildManager(global::System.String appVirtualDir, global::System.String appPhysicalSourceDir) { throw new global::System.NotImplementedException(); }
        public ClientBuildManager(global::System.String appVirtualDir, global::System.String appPhysicalSourceDir, global::System.String appPhysicalTargetDir) { throw new global::System.NotImplementedException(); }
        public ClientBuildManager(global::System.String appVirtualDir, global::System.String appPhysicalSourceDir, global::System.String appPhysicalTargetDir, global::System.Web.Compilation.ClientBuildManagerParameter parameter) { throw new global::System.NotImplementedException(); }
        public ClientBuildManager(global::System.String appVirtualDir, global::System.String appPhysicalSourceDir, global::System.String appPhysicalTargetDir, global::System.Web.Compilation.ClientBuildManagerParameter parameter, global::System.ComponentModel.TypeDescriptionProvider typeDescriptionProvider) { throw new global::System.NotImplementedException(); }
        public global::System.Web.Hosting.IRegisteredObject CreateObject(global::System.Type type, global::System.Boolean failIfExists) { throw new global::System.NotImplementedException(); }
        public global::System.String[] GetAppDomainShutdownDirectories() { throw new global::System.NotImplementedException(); }
        public void CompileApplicationDependencies() { throw new global::System.NotImplementedException(); }
        public global::System.Collections.IDictionary GetBrowserDefinitions() { throw new global::System.NotImplementedException(); }
        public global::System.String GetGeneratedSourceFile(global::System.String virtualPath) { throw new global::System.NotImplementedException(); }
        public global::System.String GetGeneratedFileVirtualPath(global::System.String filePath) { throw new global::System.NotImplementedException(); }
        public global::System.String[] GetVirtualCodeDirectories() { throw new global::System.NotImplementedException(); }
        public global::System.String[] GetTopLevelAssemblyReferences(global::System.String virtualPath) { throw new global::System.NotImplementedException(); }
        public void GetCodeDirectoryInformation(global::System.String virtualCodeDir, out global::System.Type codeDomProviderType, out global::System.CodeDom.Compiler.CompilerParameters compilerParameters, out global::System.String generatedFilesDir) { throw new global::System.NotImplementedException(); }
        public void GetCompilerParameters(global::System.String virtualPath, out global::System.Type codeDomProviderType, out global::System.CodeDom.Compiler.CompilerParameters compilerParameters) { throw new global::System.NotImplementedException(); }
        public global::System.CodeDom.CodeCompileUnit GenerateCodeCompileUnit(global::System.String virtualPath, out global::System.Type codeDomProviderType, out global::System.CodeDom.Compiler.CompilerParameters compilerParameters, out global::System.Collections.IDictionary linePragmasTable) { throw new global::System.NotImplementedException(); }
        public global::System.CodeDom.CodeCompileUnit GenerateCodeCompileUnit(global::System.String virtualPath, global::System.String virtualFileString, out global::System.Type codeDomProviderType, out global::System.CodeDom.Compiler.CompilerParameters compilerParameters, out global::System.Collections.IDictionary linePragmasTable) { throw new global::System.NotImplementedException(); }
        public global::System.String GenerateCode(global::System.String virtualPath, global::System.String virtualFileString, out global::System.Collections.IDictionary linePragmasTable) { throw new global::System.NotImplementedException(); }
        public global::System.Type GetCompiledType(global::System.String virtualPath) { throw new global::System.NotImplementedException(); }
        public void CompileFile(global::System.String virtualPath) { throw new global::System.NotImplementedException(); }
        public void CompileFile(global::System.String virtualPath, global::System.Web.Compilation.ClientBuildManagerCallback callback) { throw new global::System.NotImplementedException(); }
        public global::System.Boolean IsCodeAssembly(global::System.String assemblyName) { throw new global::System.NotImplementedException(); }
        public global::System.Boolean Unload() { throw new global::System.NotImplementedException(); }
        public void PrecompileApplication() { throw new global::System.NotImplementedException(); }
        public void PrecompileApplication(global::System.Web.Compilation.ClientBuildManagerCallback callback) { throw new global::System.NotImplementedException(); }
        public void PrecompileApplication(global::System.Web.Compilation.ClientBuildManagerCallback callback, global::System.Boolean forceCleanBuild) { throw new global::System.NotImplementedException(); }
        public override global::System.Object InitializeLifetimeService() { throw new global::System.NotImplementedException(); }
        void global::System.IDisposable.Dispose() { throw new global::System.NotImplementedException(); }
        public global::System.String CodeGenDir { get { throw new global::System.NotImplementedException(); } }
        public global::System.Boolean IsHostCreated { get { throw new global::System.NotImplementedException(); } }
        public event global::System.Web.Compilation.BuildManagerHostUnloadEventHandler AppDomainUnloaded;
        public event global::System.EventHandler AppDomainStarted;
        public event global::System.Web.Compilation.BuildManagerHostUnloadEventHandler AppDomainShutdown;
    }
    public class BuildManagerHostUnloadEventArgs : global::System.EventArgs
    {
        public BuildManagerHostUnloadEventArgs(global::System.Web.ApplicationShutdownReason reason) { throw new global::System.NotImplementedException(); }
        public global::System.Web.ApplicationShutdownReason Reason { get { throw new global::System.NotImplementedException(); } }
    }
    public delegate void BuildManagerHostUnloadEventHandler(global::System.Object sender, global::System.Web.Compilation.BuildManagerHostUnloadEventArgs e);
    public sealed class LinePragmaCodeInfo
    {
        public LinePragmaCodeInfo() { throw new global::System.NotImplementedException(); }
        public LinePragmaCodeInfo(global::System.Int32 startLine, global::System.Int32 startColumn, global::System.Int32 startGeneratedColumn, global::System.Int32 codeLength, global::System.Boolean isCodeNugget) { throw new global::System.NotImplementedException(); }
        public global::System.Int32 StartLine { get { throw new global::System.NotImplementedException(); } }
        public global::System.Int32 StartColumn { get { throw new global::System.NotImplementedException(); } }
        public global::System.Int32 StartGeneratedColumn { get { throw new global::System.NotImplementedException(); } }
        public global::System.Int32 CodeLength { get { throw new global::System.NotImplementedException(); } }
        public global::System.Boolean IsCodeNugget { get { throw new global::System.NotImplementedException(); } }
    }
    public class ClientBuildManagerCallback : global::System.MarshalByRefObject
    {
        public ClientBuildManagerCallback() { throw new global::System.NotImplementedException(); }
        public virtual void ReportCompilerError(global::System.CodeDom.Compiler.CompilerError error) { throw new global::System.NotImplementedException(); }
        public virtual void ReportParseError(global::System.Web.ParserError error) { throw new global::System.NotImplementedException(); }
        public virtual void ReportProgress(global::System.String message) { throw new global::System.NotImplementedException(); }
        public override global::System.Object InitializeLifetimeService() { throw new global::System.NotImplementedException(); }
    }
    public sealed class CompilerType
    {
        internal CompilerType() { throw new global::System.NotImplementedException(); }
        public override global::System.Int32 GetHashCode() { throw new global::System.NotImplementedException(); }
        public override global::System.Boolean Equals(global::System.Object o) { throw new global::System.NotImplementedException(); }
        public global::System.Type CodeDomProviderType { get { throw new global::System.NotImplementedException(); } }
        public global::System.CodeDom.Compiler.CompilerParameters CompilerParameters { get { throw new global::System.NotImplementedException(); } }
    }
    public class ConnectionStringsExpressionBuilder : global::System.Web.Compilation.ExpressionBuilder
    {
        public ConnectionStringsExpressionBuilder() { throw new global::System.NotImplementedException(); }
        public override global::System.Object ParseExpression(global::System.String expression, global::System.Type propertyType, global::System.Web.Compilation.ExpressionBuilderContext context) { throw new global::System.NotImplementedException(); }
        public override global::System.CodeDom.CodeExpression GetCodeExpression(global::System.Web.UI.BoundPropertyEntry entry, global::System.Object parsedData, global::System.Web.Compilation.ExpressionBuilderContext context) { throw new global::System.NotImplementedException(); }
        public override global::System.Object EvaluateExpression(global::System.Object target, global::System.Web.UI.BoundPropertyEntry entry, global::System.Object parsedData, global::System.Web.Compilation.ExpressionBuilderContext context) { throw new global::System.NotImplementedException(); }
        public static global::System.String GetConnectionStringProviderName(global::System.String connectionStringName) { throw new global::System.NotImplementedException(); }
        public static global::System.String GetConnectionString(global::System.String connectionStringName) { throw new global::System.NotImplementedException(); }
        public override global::System.Boolean SupportsEvaluate { get { throw new global::System.NotImplementedException(); } }
    }
    public sealed class DesignTimeResourceProviderFactoryAttribute : global::System.Attribute
    {
        public DesignTimeResourceProviderFactoryAttribute(global::System.Type factoryType) { throw new global::System.NotImplementedException(); }
        public DesignTimeResourceProviderFactoryAttribute(global::System.String factoryTypeName) { throw new global::System.NotImplementedException(); }
        public override global::System.Boolean IsDefaultAttribute() { throw new global::System.NotImplementedException(); }
        public global::System.String FactoryTypeName { get { throw new global::System.NotImplementedException(); } }
    }
    public abstract class ExpressionBuilder
    {
        protected ExpressionBuilder() { throw new global::System.NotImplementedException(); }
        public virtual global::System.Object ParseExpression(global::System.String expression, global::System.Type propertyType, global::System.Web.Compilation.ExpressionBuilderContext context) { throw new global::System.NotImplementedException(); }
        public abstract global::System.CodeDom.CodeExpression GetCodeExpression(global::System.Web.UI.BoundPropertyEntry entry, global::System.Object parsedData, global::System.Web.Compilation.ExpressionBuilderContext context);
        public virtual global::System.Object EvaluateExpression(global::System.Object target, global::System.Web.UI.BoundPropertyEntry entry, global::System.Object parsedData, global::System.Web.Compilation.ExpressionBuilderContext context) { throw new global::System.NotImplementedException(); }
        public virtual global::System.Boolean SupportsEvaluate { get { throw new global::System.NotImplementedException(); } }
    }
    public sealed class ExpressionBuilderContext
    {
        public ExpressionBuilderContext(global::System.String virtualPath) { throw new global::System.NotImplementedException(); }
        public ExpressionBuilderContext(global::System.Web.UI.TemplateControl templateControl) { throw new global::System.NotImplementedException(); }
        public global::System.Web.UI.TemplateControl TemplateControl { get { throw new global::System.NotImplementedException(); } }
        public global::System.String VirtualPath { get { throw new global::System.NotImplementedException(); } }
    }
    public sealed class ExpressionEditorAttribute : global::System.Attribute
    {
        public ExpressionEditorAttribute(global::System.Type type) { throw new global::System.NotImplementedException(); }
        public ExpressionEditorAttribute(global::System.String typeName) { throw new global::System.NotImplementedException(); }
        public override global::System.Boolean Equals(global::System.Object obj) { throw new global::System.NotImplementedException(); }
        public override global::System.Int32 GetHashCode() { throw new global::System.NotImplementedException(); }
        public global::System.String EditorTypeName { get { throw new global::System.NotImplementedException(); } }
    }
    public sealed class ExpressionPrefixAttribute : global::System.Attribute
    {
        public ExpressionPrefixAttribute(global::System.String expressionPrefix) { throw new global::System.NotImplementedException(); }
        public global::System.String ExpressionPrefix { get { throw new global::System.NotImplementedException(); } }
    }
    public enum FolderLevelBuildProviderAppliesTo
    {
        None = 0,
        Code = 1,
        WebReferences = 2,
        LocalResources = 4,
        GlobalResources = 8,
    }
    public sealed class FolderLevelBuildProviderAppliesToAttribute : global::System.Attribute
    {
        public FolderLevelBuildProviderAppliesToAttribute(global::System.Web.Compilation.FolderLevelBuildProviderAppliesTo appliesTo) { throw new global::System.NotImplementedException(); }
        public global::System.Web.Compilation.FolderLevelBuildProviderAppliesTo AppliesTo { get { throw new global::System.NotImplementedException(); } }
    }
    public interface IAssemblyPostProcessor : global::System.IDisposable
    {
        void PostProcessAssembly(global::System.String path);
    }
    public interface IImplicitResourceProvider
    {
        global::System.Object GetObject(global::System.Web.Compilation.ImplicitResourceKey key, global::System.Globalization.CultureInfo culture);
        global::System.Collections.ICollection GetImplicitResourceKeys(global::System.String keyPrefix);
    }
    public sealed class ImplicitResourceKey
    {
        public ImplicitResourceKey() { throw new global::System.NotImplementedException(); }
        public ImplicitResourceKey(global::System.String filter, global::System.String keyPrefix, global::System.String property) { throw new global::System.NotImplementedException(); }
        public global::System.String Filter { get { throw new global::System.NotImplementedException(); } set { throw new global::System.NotImplementedException(); } }
        public global::System.String KeyPrefix { get { throw new global::System.NotImplementedException(); } set { throw new global::System.NotImplementedException(); } }
        public global::System.String Property { get { throw new global::System.NotImplementedException(); } set { throw new global::System.NotImplementedException(); } }
    }
    public interface IResourceProvider
    {
        global::System.Object GetObject(global::System.String resourceKey, global::System.Globalization.CultureInfo culture);
        global::System.Resources.IResourceReader ResourceReader { get; }
    }
    public class ResourceExpressionBuilder : global::System.Web.Compilation.ExpressionBuilder
    {
        public ResourceExpressionBuilder() { throw new global::System.NotImplementedException(); }
        public static global::System.Web.Compilation.ResourceExpressionFields ParseExpression(global::System.String expression) { throw new global::System.NotImplementedException(); }
        public override global::System.Object ParseExpression(global::System.String expression, global::System.Type propertyType, global::System.Web.Compilation.ExpressionBuilderContext context) { throw new global::System.NotImplementedException(); }
        public override global::System.CodeDom.CodeExpression GetCodeExpression(global::System.Web.UI.BoundPropertyEntry entry, global::System.Object parsedData, global::System.Web.Compilation.ExpressionBuilderContext context) { throw new global::System.NotImplementedException(); }
        public override global::System.Object EvaluateExpression(global::System.Object target, global::System.Web.UI.BoundPropertyEntry entry, global::System.Object parsedData, global::System.Web.Compilation.ExpressionBuilderContext context) { throw new global::System.NotImplementedException(); }
        public override global::System.Boolean SupportsEvaluate { get { throw new global::System.NotImplementedException(); } }
    }
    public sealed class ResourceExpressionFields
    {
        internal ResourceExpressionFields() { throw new global::System.NotImplementedException(); }
        public global::System.String ClassKey { get { throw new global::System.NotImplementedException(); } }
        public global::System.String ResourceKey { get { throw new global::System.NotImplementedException(); } }
    }
    public abstract class ResourceProviderFactory
    {
        protected ResourceProviderFactory() { throw new global::System.NotImplementedException(); }
        public abstract global::System.Web.Compilation.IResourceProvider CreateGlobalResourceProvider(global::System.String classKey);
        public abstract global::System.Web.Compilation.IResourceProvider CreateLocalResourceProvider(global::System.String virtualPath);
    }
    public class RouteUrlExpressionBuilder : global::System.Web.Compilation.ExpressionBuilder
    {
        public RouteUrlExpressionBuilder() { throw new global::System.NotImplementedException(); }
        public override global::System.CodeDom.CodeExpression GetCodeExpression(global::System.Web.UI.BoundPropertyEntry entry, global::System.Object parsedData, global::System.Web.Compilation.ExpressionBuilderContext context) { throw new global::System.NotImplementedException(); }
        public override global::System.Object EvaluateExpression(global::System.Object target, global::System.Web.UI.BoundPropertyEntry entry, global::System.Object parsedData, global::System.Web.Compilation.ExpressionBuilderContext context) { throw new global::System.NotImplementedException(); }
        public static global::System.Boolean TryParseRouteExpression(global::System.String expression, global::System.Web.Routing.RouteValueDictionary routeValues, out global::System.String routeName) { throw new global::System.NotImplementedException(); }
        public static global::System.String GetRouteUrl(global::System.Web.UI.Control control, global::System.String expression) { throw new global::System.NotImplementedException(); }
        public override global::System.Boolean SupportsEvaluate { get { throw new global::System.NotImplementedException(); } }
    }
    public class RouteValueExpressionBuilder : global::System.Web.Compilation.ExpressionBuilder
    {
        public RouteValueExpressionBuilder() { throw new global::System.NotImplementedException(); }
        public override global::System.CodeDom.CodeExpression GetCodeExpression(global::System.Web.UI.BoundPropertyEntry entry, global::System.Object parsedData, global::System.Web.Compilation.ExpressionBuilderContext context) { throw new global::System.NotImplementedException(); }
        public override global::System.Object EvaluateExpression(global::System.Object target, global::System.Web.UI.BoundPropertyEntry entry, global::System.Object parsedData, global::System.Web.Compilation.ExpressionBuilderContext context) { throw new global::System.NotImplementedException(); }
        public static global::System.Object GetRouteValue(global::System.Web.UI.Page page, global::System.String key, global::System.Type controlType, global::System.String propertyName) { throw new global::System.NotImplementedException(); }
        public override global::System.Boolean SupportsEvaluate { get { throw new global::System.NotImplementedException(); } }
    }
}
