// <auto-generated> clean-room System.Web API skeleton.
// Tier 5a: HtmlControls implementation (clean-room, from public signatures + documented behavior).
#nullable disable
#pragma warning disable

namespace System.Web.UI.HtmlControls
{
    public abstract class HtmlControl : global::System.Web.UI.Control, global::System.Web.UI.IAttributeAccessor
    {
        private global::System.String _tagName;
        private global::System.Web.UI.AttributeCollection _attributes;

        protected HtmlControl() : this("span") { }
        protected HtmlControl(global::System.String tag) { _tagName = tag; }
        internal void SetTagNameInternal(global::System.String tag) { _tagName = tag; }

        protected override global::System.Web.UI.ControlCollection CreateControlCollection()
        {
            return new global::System.Web.UI.EmptyControlCollection(this);
        }
        protected internal override void Render(global::System.Web.UI.HtmlTextWriter writer)
        {
            RenderBeginTag(writer);
        }
        protected virtual void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            if (ID != null) { writer.WriteAttribute("id", ClientID); }
            Attributes.Render(writer);
        }
        protected virtual void RenderBeginTag(global::System.Web.UI.HtmlTextWriter writer)
        {
            writer.WriteBeginTag(TagName);
            RenderAttributes(writer);
            writer.Write(global::System.Web.UI.HtmlTextWriter.TagRightChar);
        }
        global::System.String global::System.Web.UI.IAttributeAccessor.GetAttribute(global::System.String name) { return GetAttribute(name); }
        protected virtual global::System.String GetAttribute(global::System.String name) { return Attributes[name]; }
        void global::System.Web.UI.IAttributeAccessor.SetAttribute(global::System.String name, global::System.String value) { SetAttribute(name, value); }
        protected virtual void SetAttribute(global::System.String name, global::System.String value) { Attributes[name] = value; }
        public global::System.Web.UI.AttributeCollection Attributes
        {
            get
            {
                if (_attributes == null) { _attributes = new global::System.Web.UI.AttributeCollection(ViewState); }
                return _attributes;
            }
        }
        public global::System.Web.UI.CssStyleCollection Style { get { return Attributes.CssStyle; } }
        public virtual global::System.String TagName { get { return _tagName; } }
        public global::System.Boolean Disabled
        {
            get { global::System.String s = Attributes["disabled"]; return s != null && global::System.String.Equals(s, "disabled", global::System.StringComparison.OrdinalIgnoreCase); }
            set { if (value) { Attributes["disabled"] = "disabled"; } else { Attributes.Remove("disabled"); } }
        }
        protected override global::System.Boolean ViewStateIgnoresCase { get { return true; } }
    }
    public abstract class HtmlContainerControl : global::System.Web.UI.HtmlControls.HtmlControl
    {
        protected HtmlContainerControl() : this("span") { }
        public HtmlContainerControl(global::System.String tag) : base(tag) { }

        protected override global::System.Web.UI.ControlCollection CreateControlCollection()
        {
            return new global::System.Web.UI.ControlCollection(this);
        }
        protected override void LoadViewState(global::System.Object savedState)
        {
            if (savedState != null)
            {
                global::System.Web.UI.Pair p = savedState as global::System.Web.UI.Pair;
                if (p != null)
                {
                    base.LoadViewState(p.First);
                    if (p.Second != null) { InnerHtml = (global::System.String)p.Second; }
                    return;
                }
            }
            base.LoadViewState(savedState);
        }
        protected internal override void Render(global::System.Web.UI.HtmlTextWriter writer)
        {
            RenderBeginTag(writer);
            RenderChildren(writer);
            RenderEndTag(writer);
        }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            base.RenderAttributes(writer);
        }
        protected virtual void RenderEndTag(global::System.Web.UI.HtmlTextWriter writer)
        {
            writer.WriteEndTag(TagName);
        }
        public virtual global::System.String InnerHtml
        {
            get
            {
                if (HasControls() && Controls.Count == 1)
                {
                    global::System.Web.UI.LiteralControl lit = Controls[0] as global::System.Web.UI.LiteralControl;
                    if (lit != null) { return lit.Text; }
                }
                if (!HasControls()) { return global::System.String.Empty; }
                throw new global::System.Web.HttpException("Cannot get inner content of " + TagName + " because the contents are not literal.");
            }
            set
            {
                Controls.Clear();
                Controls.Add(new global::System.Web.UI.LiteralControl(value));
                ViewState["innerhtml"] = value;
            }
        }
        public virtual global::System.String InnerText
        {
            get { return global::System.Web.HttpUtility.HtmlDecode(InnerHtml); }
            set { InnerHtml = global::System.Web.HttpUtility.HtmlEncode(value); }
        }
    }
    public class HtmlGenericControl : global::System.Web.UI.HtmlControls.HtmlContainerControl
    {
        public HtmlGenericControl() : this("span") { }
        public HtmlGenericControl(global::System.String tag) : base(tag == null || tag.Length == 0 ? "span" : tag) { }
        public new global::System.String TagName
        {
            get { return base.TagName; }
            set { SetTagNameInternal(value); }
        }
    }
    public class HtmlHeadBuilder : global::System.Web.UI.ControlBuilder
    {
        public HtmlHeadBuilder() { }
        public override global::System.Type GetChildControlType(global::System.String tagName, global::System.Collections.IDictionary attribs)
        {
            if (tagName != null)
            {
                if (global::System.String.Equals(tagName, "title", global::System.StringComparison.OrdinalIgnoreCase)) { return typeof(global::System.Web.UI.HtmlControls.HtmlTitle); }
                if (global::System.String.Equals(tagName, "link", global::System.StringComparison.OrdinalIgnoreCase)) { return typeof(global::System.Web.UI.HtmlControls.HtmlLink); }
                if (global::System.String.Equals(tagName, "meta", global::System.StringComparison.OrdinalIgnoreCase)) { return typeof(global::System.Web.UI.HtmlControls.HtmlMeta); }
            }
            return null;
        }
        public override global::System.Boolean AllowWhitespaceLiterals() { return false; }
    }
    public sealed class HtmlHead : global::System.Web.UI.HtmlControls.HtmlGenericControl
    {
        private global::System.String _title;
        private global::System.String _description;
        private global::System.String _keywords;
        private global::System.Web.UI.HtmlControls.HtmlTitle _titleControl;
        private global::System.Web.UI.HtmlControls.HtmlMeta _descriptionMeta;
        private global::System.Web.UI.HtmlControls.HtmlMeta _keywordsMeta;

        public HtmlHead() : base("head") { }
        public HtmlHead(global::System.String tag) : base(tag) { }
        protected internal override void AddedControl(global::System.Web.UI.Control control, global::System.Int32 index)
        {
            global::System.Web.UI.HtmlControls.HtmlTitle t = control as global::System.Web.UI.HtmlControls.HtmlTitle;
            if (t != null) { _titleControl = t; }
            base.AddedControl(control, index);
        }
        protected internal override void OnInit(global::System.EventArgs e)
        {
            base.OnInit(e);
        }
        protected internal override void RemovedControl(global::System.Web.UI.Control control)
        {
            if (control == _titleControl) { _titleControl = null; }
            base.RemovedControl(control);
        }
        protected internal override void RenderChildren(global::System.Web.UI.HtmlTextWriter writer)
        {
            base.RenderChildren(writer);
        }
        public global::System.Web.UI.IStyleSheet StyleSheet { get { return null; } }
        public global::System.String Title
        {
            get { if (_titleControl != null) { return _titleControl.Text; } return _title == null ? global::System.String.Empty : _title; }
            set { _title = value; if (_titleControl != null) { _titleControl.Text = value; } }
        }
        public global::System.String Description
        {
            get { return _description == null ? global::System.String.Empty : _description; }
            set { _description = value; }
        }
        public global::System.String Keywords
        {
            get { return _keywords == null ? global::System.String.Empty : _keywords; }
            set { _keywords = value; }
        }
    }
    public sealed class HtmlEmptyTagControlBuilder : global::System.Web.UI.ControlBuilder
    {
        public HtmlEmptyTagControlBuilder() { }
        public override global::System.Boolean HasBody() { return false; }
    }
    public abstract class HtmlInputControl : global::System.Web.UI.HtmlControls.HtmlControl
    {
        private global::System.String _type;
        protected HtmlInputControl(global::System.String type) : base("input")
        {
            _type = type;
            if (type != null) { Attributes["type"] = type; }
        }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            if (Type != null)
            {
                writer.WriteAttribute("name", RenderedNameAttribute);
                Attributes.Remove("name");
            }
            if (Page != null) { /* value preserved across postback via ViewState/Value */ }
            RenderValueAttribute(writer);
            base.RenderAttributes(writer);
            writer.Write(' ');
            writer.Write('/');
        }
        internal virtual void RenderValueAttribute(global::System.Web.UI.HtmlTextWriter writer)
        {
            global::System.String value = Attributes["value"];
            if (value != null) { writer.WriteAttribute("value", value); Attributes.Remove("value"); }
        }
        internal virtual global::System.String RenderedNameAttribute { get { return Name; } }
        public virtual global::System.String Name
        {
            get { return UniqueID; }
            set { /* Name follows UniqueID for server controls; setter is a no-op compatibility shim */ }
        }
        public virtual global::System.String Value
        {
            get { global::System.String s = Attributes["value"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["value"] = value; }
        }
        public global::System.String Type { get { return _type; } }
    }
    public class HtmlInputText : global::System.Web.UI.HtmlControls.HtmlInputControl, global::System.Web.UI.IPostBackDataHandler
    {
        private static readonly global::System.Object EventServerChange = new global::System.Object();
        public HtmlInputText() : base("text") { }
        public HtmlInputText(global::System.String type) : base(type) { }
        protected virtual void OnServerChange(global::System.EventArgs e)
        {
            global::System.EventHandler h = (global::System.EventHandler)Events[EventServerChange];
            if (h != null) { h(this, e); }
        }
        protected internal override void OnPreRender(global::System.EventArgs e)
        {
            base.OnPreRender(e);
            if (Events[EventServerChange] != null && Page != null) { Page.RegisterRequiresPostBack(this); }
        }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            base.RenderAttributes(writer);
        }
        internal override void RenderValueAttribute(global::System.Web.UI.HtmlTextWriter writer)
        {
            if (global::System.String.Equals(Type, "password", global::System.StringComparison.OrdinalIgnoreCase)) { Attributes.Remove("value"); return; }
            base.RenderValueAttribute(writer);
        }
        global::System.Boolean global::System.Web.UI.IPostBackDataHandler.LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection) { return LoadPostData(postDataKey, postCollection); }
        protected virtual global::System.Boolean LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection)
        {
            global::System.String current = Value;
            global::System.String posted = postCollection[postDataKey];
            if (posted != null && !global::System.String.Equals(current, posted, global::System.StringComparison.Ordinal))
            {
                Value = posted;
                return true;
            }
            return false;
        }
        void global::System.Web.UI.IPostBackDataHandler.RaisePostDataChangedEvent() { RaisePostDataChangedEvent(); }
        protected virtual void RaisePostDataChangedEvent() { OnServerChange(global::System.EventArgs.Empty); }
        public global::System.Int32 MaxLength
        {
            get { global::System.String s = Attributes["maxlength"]; return s == null ? -1 : global::System.Int32.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture); }
            set { if (value < 0) { Attributes.Remove("maxlength"); } else { Attributes["maxlength"] = value.ToString(global::System.Globalization.CultureInfo.InvariantCulture); } }
        }
        public global::System.Int32 Size
        {
            get { global::System.String s = Attributes["size"]; return s == null ? -1 : global::System.Int32.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture); }
            set { if (value < 0) { Attributes.Remove("size"); } else { Attributes["size"] = value.ToString(global::System.Globalization.CultureInfo.InvariantCulture); } }
        }
        public override global::System.String Value { get { return base.Value; } set { base.Value = value; } }
        public event global::System.EventHandler ServerChange { add { Events.AddHandler(EventServerChange, value); } remove { Events.RemoveHandler(EventServerChange, value); } }
    }
    public class HtmlInputPassword : global::System.Web.UI.HtmlControls.HtmlInputText, global::System.Web.UI.IPostBackDataHandler
    {
        public HtmlInputPassword() : base("password") { }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            base.RenderAttributes(writer);
        }
    }
    public class HtmlInputButton : global::System.Web.UI.HtmlControls.HtmlInputControl, global::System.Web.UI.IPostBackEventHandler
    {
        private static readonly global::System.Object EventServerClick = new global::System.Object();
        public HtmlInputButton() : base("button") { }
        public HtmlInputButton(global::System.String type) : base(type) { }
        protected internal override void OnPreRender(global::System.EventArgs e)
        {
            base.OnPreRender(e);
        }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            if (Page != null && Events[EventServerClick] != null && CausesValidation == false)
            {
                // emit onclick postback if a server handler is attached and no client onclick present
            }
            global::System.String onclick = Attributes["onclick"];
            if (Events[EventServerClick] != null && Page != null)
            {
                global::System.String pb = Page.ClientScript.GetPostBackEventReference(this, global::System.String.Empty);
                if (string.IsNullOrEmpty(onclick)) { Attributes["onclick"] = pb + ";"; }
                else { Attributes["onclick"] = onclick + " " + pb + ";"; }
            }
            base.RenderAttributes(writer);
        }
        protected virtual void OnServerClick(global::System.EventArgs e)
        {
            global::System.EventHandler h = (global::System.EventHandler)Events[EventServerClick];
            if (h != null) { h(this, e); }
        }
        void global::System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(global::System.String eventArgument) { RaisePostBackEvent(eventArgument); }
        protected virtual void RaisePostBackEvent(global::System.String eventArgument)
        {
            if (CausesValidation && Page != null) { Page.Validate(ValidationGroup); }
            OnServerClick(global::System.EventArgs.Empty);
        }
        public virtual global::System.Boolean CausesValidation
        {
            get { global::System.Object o = ViewState["CausesValidation"]; return o == null ? true : (global::System.Boolean)o; }
            set { ViewState["CausesValidation"] = value; }
        }
        public virtual global::System.String ValidationGroup
        {
            get { global::System.String s = (global::System.String)ViewState["ValidationGroup"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["ValidationGroup"] = value; }
        }
        public event global::System.EventHandler ServerClick { add { Events.AddHandler(EventServerClick, value); } remove { Events.RemoveHandler(EventServerClick, value); } }
    }
    public class HtmlInputSubmit : global::System.Web.UI.HtmlControls.HtmlInputButton, global::System.Web.UI.IPostBackEventHandler
    {
        public HtmlInputSubmit() : base("submit") { }
        public HtmlInputSubmit(global::System.String type) : base(type) { }
    }
    public class HtmlInputReset : global::System.Web.UI.HtmlControls.HtmlInputButton
    {
        public HtmlInputReset() : base("reset") { }
        public HtmlInputReset(global::System.String type) : base(type) { }
        public override global::System.Boolean CausesValidation
        {
            get { return false; }
            set { }
        }
        public override global::System.String ValidationGroup { get { return global::System.String.Empty; } set { } }
        public new event global::System.EventHandler ServerClick { add { } remove { } }
    }
    public class HtmlInputHidden : global::System.Web.UI.HtmlControls.HtmlInputControl, global::System.Web.UI.IPostBackDataHandler
    {
        private static readonly global::System.Object EventServerChange = new global::System.Object();
        public HtmlInputHidden() : base("hidden") { }
        protected virtual void OnServerChange(global::System.EventArgs e)
        {
            global::System.EventHandler h = (global::System.EventHandler)Events[EventServerChange];
            if (h != null) { h(this, e); }
        }
        protected internal override void OnPreRender(global::System.EventArgs e)
        {
            base.OnPreRender(e);
            if (Events[EventServerChange] != null && Page != null) { Page.RegisterRequiresPostBack(this); }
        }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            base.RenderAttributes(writer);
        }
        global::System.Boolean global::System.Web.UI.IPostBackDataHandler.LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection) { return LoadPostData(postDataKey, postCollection); }
        protected virtual global::System.Boolean LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection)
        {
            global::System.String current = Value;
            global::System.String posted = postCollection[postDataKey];
            if (posted != null && !global::System.String.Equals(current, posted, global::System.StringComparison.Ordinal))
            {
                Value = posted;
                return true;
            }
            return false;
        }
        void global::System.Web.UI.IPostBackDataHandler.RaisePostDataChangedEvent() { RaisePostDataChangedEvent(); }
        protected virtual void RaisePostDataChangedEvent() { OnServerChange(global::System.EventArgs.Empty); }
        public event global::System.EventHandler ServerChange { add { Events.AddHandler(EventServerChange, value); } remove { Events.RemoveHandler(EventServerChange, value); } }
    }
    public class HtmlInputCheckBox : global::System.Web.UI.HtmlControls.HtmlInputControl, global::System.Web.UI.IPostBackDataHandler
    {
        private static readonly global::System.Object EventServerChange = new global::System.Object();
        public HtmlInputCheckBox() : base("checkbox") { }
        protected internal override void OnPreRender(global::System.EventArgs e)
        {
            base.OnPreRender(e);
            if (Page != null) { Page.RegisterRequiresPostBack(this); }
        }
        protected virtual void OnServerChange(global::System.EventArgs e)
        {
            global::System.EventHandler h = (global::System.EventHandler)Events[EventServerChange];
            if (h != null) { h(this, e); }
        }
        global::System.Boolean global::System.Web.UI.IPostBackDataHandler.LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection) { return LoadPostData(postDataKey, postCollection); }
        protected virtual global::System.Boolean LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection)
        {
            global::System.Boolean wasChecked = Checked;
            global::System.String posted = postCollection[postDataKey];
            global::System.Boolean nowChecked = posted != null;
            Checked = nowChecked;
            return nowChecked != wasChecked;
        }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            if (Checked) { Attributes["checked"] = "checked"; }
            else { Attributes.Remove("checked"); }
            base.RenderAttributes(writer);
        }
        void global::System.Web.UI.IPostBackDataHandler.RaisePostDataChangedEvent() { RaisePostDataChangedEvent(); }
        protected virtual void RaisePostDataChangedEvent() { OnServerChange(global::System.EventArgs.Empty); }
        public global::System.Boolean Checked
        {
            get { global::System.String s = Attributes["checked"]; return s != null && global::System.String.Equals(s, "checked", global::System.StringComparison.OrdinalIgnoreCase); }
            set { if (value) { Attributes["checked"] = "checked"; } else { Attributes.Remove("checked"); } }
        }
        public event global::System.EventHandler ServerChange { add { Events.AddHandler(EventServerChange, value); } remove { Events.RemoveHandler(EventServerChange, value); } }
    }
    public class HtmlInputRadioButton : global::System.Web.UI.HtmlControls.HtmlInputControl, global::System.Web.UI.IPostBackDataHandler
    {
        private static readonly global::System.Object EventServerChange = new global::System.Object();
        public HtmlInputRadioButton() : base("radio") { }
        protected internal override void OnPreRender(global::System.EventArgs e)
        {
            base.OnPreRender(e);
            if (Page != null) { Page.RegisterRequiresPostBack(this); }
        }
        protected virtual void OnServerChange(global::System.EventArgs e)
        {
            global::System.EventHandler h = (global::System.EventHandler)Events[EventServerChange];
            if (h != null) { h(this, e); }
        }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            if (Checked) { Attributes["checked"] = "checked"; }
            else { Attributes.Remove("checked"); }
            base.RenderAttributes(writer);
        }
        global::System.Boolean global::System.Web.UI.IPostBackDataHandler.LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection) { return LoadPostData(postDataKey, postCollection); }
        protected virtual global::System.Boolean LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection)
        {
            global::System.String posted = postCollection[Name];
            global::System.Boolean wasChecked = Checked;
            global::System.Boolean nowChecked = posted != null && global::System.String.Equals(posted, Value, global::System.StringComparison.Ordinal);
            Checked = nowChecked;
            return nowChecked && !wasChecked;
        }
        void global::System.Web.UI.IPostBackDataHandler.RaisePostDataChangedEvent() { RaisePostDataChangedEvent(); }
        protected virtual void RaisePostDataChangedEvent() { OnServerChange(global::System.EventArgs.Empty); }
        public global::System.Boolean Checked
        {
            get { global::System.String s = Attributes["checked"]; return s != null && global::System.String.Equals(s, "checked", global::System.StringComparison.OrdinalIgnoreCase); }
            set { if (value) { Attributes["checked"] = "checked"; } else { Attributes.Remove("checked"); } }
        }
        public override global::System.String Name
        {
            get { global::System.String s = Attributes["name"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["name"] = value; }
        }
        internal override global::System.String RenderedNameAttribute { get { global::System.String s = Attributes["name"]; return s == null ? UniqueID : s; } }
        public override global::System.String Value
        {
            get { global::System.String s = Attributes["value"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["value"] = value; }
        }
        public event global::System.EventHandler ServerChange { add { Events.AddHandler(EventServerChange, value); } remove { Events.RemoveHandler(EventServerChange, value); } }
    }
    public class HtmlInputFile : global::System.Web.UI.HtmlControls.HtmlInputControl, global::System.Web.UI.IPostBackDataHandler
    {
        public HtmlInputFile() : base("file") { }
        global::System.Boolean global::System.Web.UI.IPostBackDataHandler.LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection) { return LoadPostData(postDataKey, postCollection); }
        protected virtual global::System.Boolean LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection) { return false; }
        void global::System.Web.UI.IPostBackDataHandler.RaisePostDataChangedEvent() { RaisePostDataChangedEvent(); }
        protected virtual void RaisePostDataChangedEvent() { }
        protected internal override void OnPreRender(global::System.EventArgs e)
        {
            base.OnPreRender(e);
            global::System.Web.UI.HtmlControls.HtmlForm form = Page != null ? Page.Form : null;
            if (form != null) { form.Enctype = "multipart/form-data"; }
        }
        public global::System.String Accept
        {
            get { global::System.String s = Attributes["accept"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["accept"] = value; }
        }
        public global::System.Int32 MaxLength
        {
            get { global::System.String s = Attributes["maxlength"]; return s == null ? -1 : global::System.Int32.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture); }
            set { if (value < 0) { Attributes.Remove("maxlength"); } else { Attributes["maxlength"] = value.ToString(global::System.Globalization.CultureInfo.InvariantCulture); } }
        }
        public global::System.Web.HttpPostedFile PostedFile
        {
            get
            {
                global::System.Web.HttpRequest req = (Context != null) ? Context.Request : null;
                if (req != null && req.Files != null) { return req.Files[RenderedNameAttribute]; }
                return null;
            }
        }
        public global::System.Int32 Size
        {
            get { global::System.String s = Attributes["size"]; return s == null ? -1 : global::System.Int32.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture); }
            set { if (value < 0) { Attributes.Remove("size"); } else { Attributes["size"] = value.ToString(global::System.Globalization.CultureInfo.InvariantCulture); } }
        }
        public override global::System.String Value { get { return global::System.String.Empty; } set { } }
    }
    public class HtmlInputImage : global::System.Web.UI.HtmlControls.HtmlInputControl, global::System.Web.UI.IPostBackDataHandler, global::System.Web.UI.IPostBackEventHandler
    {
        private static readonly global::System.Object EventServerClick = new global::System.Object();
        private global::System.Int32 _x;
        private global::System.Int32 _y;
        public HtmlInputImage() : base("image") { }
        protected internal override void OnPreRender(global::System.EventArgs e)
        {
            base.OnPreRender(e);
            if (Events[EventServerClick] != null && Page != null) { Page.RegisterRequiresPostBack(this); }
        }
        protected virtual void OnServerClick(global::System.Web.UI.ImageClickEventArgs e)
        {
            global::System.Web.UI.ImageClickEventHandler h = (global::System.Web.UI.ImageClickEventHandler)Events[EventServerClick];
            if (h != null) { h(this, e); }
        }
        void global::System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(global::System.String eventArgument) { RaisePostBackEvent(eventArgument); }
        protected virtual void RaisePostBackEvent(global::System.String eventArgument)
        {
            if (CausesValidation && Page != null) { Page.Validate(ValidationGroup); }
            OnServerClick(new global::System.Web.UI.ImageClickEventArgs(_x, _y));
        }
        global::System.Boolean global::System.Web.UI.IPostBackDataHandler.LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection) { return LoadPostData(postDataKey, postCollection); }
        protected virtual global::System.Boolean LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection)
        {
            global::System.String name = RenderedNameAttribute;
            global::System.String xs = postCollection[name + ".x"];
            global::System.String ys = postCollection[name + ".y"];
            if (xs != null && ys != null)
            {
                global::System.Int32.TryParse(xs, global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out _x);
                global::System.Int32.TryParse(ys, global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out _y);
                if (Page != null) { Page.RegisterRequiresRaiseEvent(this); }
                return false;
            }
            return false;
        }
        void global::System.Web.UI.IPostBackDataHandler.RaisePostDataChangedEvent() { RaisePostDataChangedEvent(); }
        protected virtual void RaisePostDataChangedEvent() { }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            base.RenderAttributes(writer);
        }
        public global::System.String Align
        {
            get { global::System.String s = Attributes["align"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["align"] = value; }
        }
        public global::System.String Alt
        {
            get { global::System.String s = Attributes["alt"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["alt"] = value; }
        }
        public global::System.Int32 Border
        {
            get { global::System.String s = Attributes["border"]; return s == null ? -1 : global::System.Int32.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture); }
            set { if (value < 0) { Attributes.Remove("border"); } else { Attributes["border"] = value.ToString(global::System.Globalization.CultureInfo.InvariantCulture); } }
        }
        public global::System.String Src
        {
            get { global::System.String s = Attributes["src"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["src"] = value; }
        }
        public virtual global::System.Boolean CausesValidation
        {
            get { global::System.Object o = ViewState["CausesValidation"]; return o == null ? true : (global::System.Boolean)o; }
            set { ViewState["CausesValidation"] = value; }
        }
        public virtual global::System.String ValidationGroup
        {
            get { global::System.String s = (global::System.String)ViewState["ValidationGroup"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["ValidationGroup"] = value; }
        }
        public event global::System.Web.UI.ImageClickEventHandler ServerClick { add { Events.AddHandler(EventServerClick, value); } remove { Events.RemoveHandler(EventServerClick, value); } }
    }
    public class HtmlInputGenericControl : global::System.Web.UI.HtmlControls.HtmlInputControl, global::System.Web.UI.IPostBackDataHandler
    {
        private static readonly global::System.Object EventServerChange = new global::System.Object();
        public HtmlInputGenericControl() : base("text") { }
        public HtmlInputGenericControl(global::System.String type) : base(type) { }
        protected virtual void OnServerChange(global::System.EventArgs e)
        {
            global::System.EventHandler h = (global::System.EventHandler)Events[EventServerChange];
            if (h != null) { h(this, e); }
        }
        protected internal override void OnPreRender(global::System.EventArgs e)
        {
            base.OnPreRender(e);
            if (Events[EventServerChange] != null && Page != null) { Page.RegisterRequiresPostBack(this); }
        }
        global::System.Boolean global::System.Web.UI.IPostBackDataHandler.LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection) { return LoadPostData(postDataKey, postCollection); }
        protected virtual global::System.Boolean LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection)
        {
            global::System.String current = Value;
            global::System.String posted = postCollection[postDataKey];
            if (posted != null && !global::System.String.Equals(current, posted, global::System.StringComparison.Ordinal))
            {
                Value = posted;
                return true;
            }
            return false;
        }
        void global::System.Web.UI.IPostBackDataHandler.RaisePostDataChangedEvent() { RaisePostDataChangedEvent(); }
        protected virtual void RaisePostDataChangedEvent() { OnServerChange(global::System.EventArgs.Empty); }
        public event global::System.EventHandler ServerChange { add { Events.AddHandler(EventServerChange, value); } remove { Events.RemoveHandler(EventServerChange, value); } }
    }
    public class HtmlButton : global::System.Web.UI.HtmlControls.HtmlContainerControl, global::System.Web.UI.IPostBackEventHandler
    {
        private static readonly global::System.Object EventServerClick = new global::System.Object();
        public HtmlButton() : base("button") { }
        protected internal override void OnPreRender(global::System.EventArgs e)
        {
            base.OnPreRender(e);
        }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            if (Events[EventServerClick] != null && Page != null)
            {
                global::System.String onclick = Attributes["onclick"];
                global::System.String pb = Page.ClientScript.GetPostBackEventReference(this, global::System.String.Empty);
                if (string.IsNullOrEmpty(onclick)) { Attributes["onclick"] = pb + ";"; }
                else { Attributes["onclick"] = onclick + " " + pb + ";"; }
            }
            base.RenderAttributes(writer);
        }
        protected virtual void OnServerClick(global::System.EventArgs e)
        {
            global::System.EventHandler h = (global::System.EventHandler)Events[EventServerClick];
            if (h != null) { h(this, e); }
        }
        void global::System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(global::System.String eventArgument) { RaisePostBackEvent(eventArgument); }
        protected virtual void RaisePostBackEvent(global::System.String eventArgument)
        {
            if (CausesValidation && Page != null) { Page.Validate(ValidationGroup); }
            OnServerClick(global::System.EventArgs.Empty);
        }
        public virtual global::System.Boolean CausesValidation
        {
            get { global::System.Object o = ViewState["CausesValidation"]; return o == null ? true : (global::System.Boolean)o; }
            set { ViewState["CausesValidation"] = value; }
        }
        public virtual global::System.String ValidationGroup
        {
            get { global::System.String s = (global::System.String)ViewState["ValidationGroup"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["ValidationGroup"] = value; }
        }
        public event global::System.EventHandler ServerClick { add { Events.AddHandler(EventServerClick, value); } remove { Events.RemoveHandler(EventServerClick, value); } }
    }
    public class HtmlAnchor : global::System.Web.UI.HtmlControls.HtmlContainerControl, global::System.Web.UI.IPostBackEventHandler
    {
        private static readonly global::System.Object EventServerClick = new global::System.Object();
        public HtmlAnchor() : base("a") { }
        protected internal override void OnPreRender(global::System.EventArgs e)
        {
            base.OnPreRender(e);
        }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            if (Events[EventServerClick] != null && Page != null)
            {
                Attributes["href"] = Page.ClientScript.GetPostBackClientHyperlink(this, global::System.String.Empty);
            }
            base.RenderAttributes(writer);
        }
        protected virtual void OnServerClick(global::System.EventArgs e)
        {
            global::System.EventHandler h = (global::System.EventHandler)Events[EventServerClick];
            if (h != null) { h(this, e); }
        }
        void global::System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(global::System.String eventArgument) { RaisePostBackEvent(eventArgument); }
        protected virtual void RaisePostBackEvent(global::System.String eventArgument)
        {
            if (CausesValidation && Page != null) { Page.Validate(ValidationGroup); }
            OnServerClick(global::System.EventArgs.Empty);
        }
        public virtual global::System.Boolean CausesValidation
        {
            get { global::System.Object o = ViewState["CausesValidation"]; return o == null ? true : (global::System.Boolean)o; }
            set { ViewState["CausesValidation"] = value; }
        }
        public global::System.String HRef
        {
            get { global::System.String s = Attributes["href"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["href"] = value; }
        }
        public global::System.String Name
        {
            get { global::System.String s = Attributes["name"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["name"] = value; }
        }
        public global::System.String Target
        {
            get { global::System.String s = Attributes["target"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["target"] = value; }
        }
        public global::System.String Title
        {
            get { global::System.String s = Attributes["title"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["title"] = value; }
        }
        public virtual global::System.String ValidationGroup
        {
            get { global::System.String s = (global::System.String)ViewState["ValidationGroup"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["ValidationGroup"] = value; }
        }
        public event global::System.EventHandler ServerClick { add { Events.AddHandler(EventServerClick, value); } remove { Events.RemoveHandler(EventServerClick, value); } }
    }
    public class HtmlImage : global::System.Web.UI.HtmlControls.HtmlControl
    {
        public HtmlImage() : base("img") { }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            base.RenderAttributes(writer);
            writer.Write(' ');
            writer.Write('/');
        }
        public global::System.String Alt
        {
            get { global::System.String s = Attributes["alt"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["alt"] = value; }
        }
        public global::System.String Align
        {
            get { global::System.String s = Attributes["align"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["align"] = value; }
        }
        public global::System.Int32 Border
        {
            get { global::System.String s = Attributes["border"]; return s == null ? -1 : global::System.Int32.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture); }
            set { Attributes["border"] = value.ToString(global::System.Globalization.CultureInfo.InvariantCulture); }
        }
        public global::System.Int32 Height
        {
            get { global::System.String s = Attributes["height"]; return s == null ? -1 : global::System.Int32.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture); }
            set { Attributes["height"] = value.ToString(global::System.Globalization.CultureInfo.InvariantCulture); }
        }
        public global::System.String Src
        {
            get { global::System.String s = Attributes["src"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["src"] = value; }
        }
        public global::System.Int32 Width
        {
            get { global::System.String s = Attributes["width"]; return s == null ? -1 : global::System.Int32.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture); }
            set { Attributes["width"] = value.ToString(global::System.Globalization.CultureInfo.InvariantCulture); }
        }
    }
    public class HtmlTextArea : global::System.Web.UI.HtmlControls.HtmlContainerControl, global::System.Web.UI.IPostBackDataHandler
    {
        private static readonly global::System.Object EventServerChange = new global::System.Object();
        public HtmlTextArea() : base("textarea") { }
        protected override void AddParsedSubObject(global::System.Object obj)
        {
            global::System.Web.UI.LiteralControl lit = obj as global::System.Web.UI.LiteralControl;
            if (lit != null) { Value = lit.Text; return; }
            throw new global::System.Web.HttpException("HtmlTextArea cannot have children of type " + obj.GetType().Name + ".");
        }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            Attributes.Remove("value");
            if (ID != null) { writer.WriteAttribute("id", ClientID); }
            writer.WriteAttribute("name", UniqueID);
            Attributes.Render(writer);
        }
        protected internal override void Render(global::System.Web.UI.HtmlTextWriter writer)
        {
            writer.WriteBeginTag(TagName);
            RenderAttributes(writer);
            writer.Write(global::System.Web.UI.HtmlTextWriter.TagRightChar);
            writer.Write(global::System.Web.HttpUtility.HtmlEncode(Value));
            writer.WriteEndTag(TagName);
        }
        protected virtual void OnServerChange(global::System.EventArgs e)
        {
            global::System.EventHandler h = (global::System.EventHandler)Events[EventServerChange];
            if (h != null) { h(this, e); }
        }
        protected internal override void OnPreRender(global::System.EventArgs e)
        {
            base.OnPreRender(e);
            if (Events[EventServerChange] != null && Page != null) { Page.RegisterRequiresPostBack(this); }
        }
        global::System.Boolean global::System.Web.UI.IPostBackDataHandler.LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection) { return LoadPostData(postDataKey, postCollection); }
        protected virtual global::System.Boolean LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection)
        {
            global::System.String current = Value;
            global::System.String posted = postCollection[postDataKey];
            if (posted != null && !global::System.String.Equals(current, posted, global::System.StringComparison.Ordinal))
            {
                Value = posted;
                return true;
            }
            return false;
        }
        void global::System.Web.UI.IPostBackDataHandler.RaisePostDataChangedEvent() { RaisePostDataChangedEvent(); }
        protected virtual void RaisePostDataChangedEvent() { OnServerChange(global::System.EventArgs.Empty); }
        public global::System.Int32 Cols
        {
            get { global::System.String s = Attributes["cols"]; return s == null ? -1 : global::System.Int32.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture); }
            set { if (value < 0) { Attributes.Remove("cols"); } else { Attributes["cols"] = value.ToString(global::System.Globalization.CultureInfo.InvariantCulture); } }
        }
        public virtual global::System.String Name
        {
            get { return UniqueID; }
            set { }
        }
        public global::System.Int32 Rows
        {
            get { global::System.String s = Attributes["rows"]; return s == null ? -1 : global::System.Int32.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture); }
            set { if (value < 0) { Attributes.Remove("rows"); } else { Attributes["rows"] = value.ToString(global::System.Globalization.CultureInfo.InvariantCulture); } }
        }
        public global::System.String Value
        {
            get { global::System.String s = (global::System.String)ViewState["value"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["value"] = value; }
        }
        public event global::System.EventHandler ServerChange { add { Events.AddHandler(EventServerChange, value); } remove { Events.RemoveHandler(EventServerChange, value); } }
    }
    public class HtmlTitle : global::System.Web.UI.HtmlControls.HtmlControl
    {
        public HtmlTitle() : base("title") { }
        protected override void AddParsedSubObject(global::System.Object obj)
        {
            global::System.Web.UI.LiteralControl lit = obj as global::System.Web.UI.LiteralControl;
            if (lit != null) { Text = lit.Text; return; }
            throw new global::System.Web.HttpException("HtmlTitle cannot have children of type " + obj.GetType().Name + ".");
        }
        protected override global::System.Web.UI.ControlCollection CreateControlCollection()
        {
            return new global::System.Web.UI.EmptyControlCollection(this);
        }
        protected internal override void Render(global::System.Web.UI.HtmlTextWriter writer)
        {
            writer.WriteBeginTag(TagName);
            RenderAttributes(writer);
            writer.Write(global::System.Web.UI.HtmlTextWriter.TagRightChar);
            writer.Write(global::System.Web.HttpUtility.HtmlEncode(Text));
            writer.WriteEndTag(TagName);
        }
        public virtual global::System.String Text
        {
            get { global::System.String s = (global::System.String)ViewState["Text"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["Text"] = value; }
        }
    }
    public class HtmlLink : global::System.Web.UI.HtmlControls.HtmlControl
    {
        public HtmlLink() : base("link") { }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            global::System.String href = (global::System.String)ViewState["Href"];
            if (href != null) { Attributes["href"] = ResolveClientUrl(href); }
            base.RenderAttributes(writer);
        }
        protected internal override void Render(global::System.Web.UI.HtmlTextWriter writer)
        {
            writer.WriteBeginTag(TagName);
            RenderAttributes(writer);
            writer.Write(global::System.Web.UI.HtmlTextWriter.TagRightChar);
        }
        public virtual global::System.String Href
        {
            get { global::System.String s = (global::System.String)ViewState["Href"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["Href"] = value; }
        }
    }
    public class HtmlMeta : global::System.Web.UI.HtmlControls.HtmlControl
    {
        public HtmlMeta() : base("meta") { }
        protected internal override void Render(global::System.Web.UI.HtmlTextWriter writer)
        {
            writer.WriteBeginTag(TagName);
            RenderAttributes(writer);
            writer.Write(global::System.Web.UI.HtmlTextWriter.SelfClosingTagEnd);
        }
        public virtual global::System.String Content
        {
            get { global::System.String s = Attributes["content"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["content"] = value; }
        }
        public virtual global::System.String HttpEquiv
        {
            get { global::System.String s = Attributes["http-equiv"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["http-equiv"] = value; }
        }
        public virtual global::System.String Name
        {
            get { global::System.String s = Attributes["name"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["name"] = value; }
        }
        public virtual global::System.String Scheme
        {
            get { global::System.String s = Attributes["scheme"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["scheme"] = value; }
        }
    }
    public class HtmlSelectBuilder : global::System.Web.UI.ControlBuilder
    {
        public HtmlSelectBuilder() { }
        public override global::System.Type GetChildControlType(global::System.String tagName, global::System.Collections.IDictionary attribs)
        {
            if (tagName != null && global::System.String.Equals(tagName, "option", global::System.StringComparison.OrdinalIgnoreCase))
            {
                return typeof(global::System.Web.UI.WebControls.ListItem);
            }
            return null;
        }
        public override global::System.Boolean AllowWhitespaceLiterals() { return false; }
    }
    public class HtmlSelect : global::System.Web.UI.HtmlControls.HtmlContainerControl, global::System.Web.UI.IPostBackDataHandler, global::System.Web.UI.IParserAccessor
    {
        private static readonly global::System.Object EventServerChange = new global::System.Object();
        private global::System.Web.UI.WebControls.ListItemCollection _items;
        private global::System.Boolean _requiresDataBinding;
        public HtmlSelect() : base("select") { }
        protected override void AddParsedSubObject(global::System.Object obj)
        {
            global::System.Web.UI.WebControls.ListItem li = obj as global::System.Web.UI.WebControls.ListItem;
            if (li != null) { Items.Add(li); return; }
            global::System.Web.UI.LiteralControl lit = obj as global::System.Web.UI.LiteralControl;
            if (lit != null) { return; }
            throw new global::System.Web.HttpException("HtmlSelect cannot have children of type " + obj.GetType().Name + ".");
        }
        protected virtual void ClearSelection()
        {
            global::System.Web.UI.WebControls.ListItemCollection items = Items;
            for (global::System.Int32 i = 0; i < items.Count; i++) { items[i].Selected = false; }
        }
        protected override global::System.Web.UI.ControlCollection CreateControlCollection()
        {
            return new global::System.Web.UI.EmptyControlCollection(this);
        }
        protected void EnsureDataBound()
        {
            if (_requiresDataBinding && IsBoundUsingDataSourceID) { DataBind(); }
        }
        protected virtual global::System.Collections.IEnumerable GetData() { return null; }
        protected override void LoadViewState(global::System.Object savedState)
        {
            base.LoadViewState(savedState);
        }
        protected override void OnDataBinding(global::System.EventArgs e) { base.OnDataBinding(e); }
        protected virtual void OnDataPropertyChanged() { _requiresDataBinding = true; }
        protected virtual void OnDataSourceViewChanged(global::System.Object sender, global::System.EventArgs e) { _requiresDataBinding = true; }
        protected internal override void OnInit(global::System.EventArgs e) { base.OnInit(e); }
        protected internal override void OnLoad(global::System.EventArgs e) { base.OnLoad(e); }
        protected internal override void OnPreRender(global::System.EventArgs e)
        {
            base.OnPreRender(e);
            if (Page != null) { Page.RegisterRequiresPostBack(this); }
        }
        protected virtual void OnServerChange(global::System.EventArgs e)
        {
            global::System.EventHandler h = (global::System.EventHandler)Events[EventServerChange];
            if (h != null) { h(this, e); }
        }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            Attributes.Remove("DataValueField");
            Attributes.Remove("DataTextField");
            Attributes.Remove("DataMember");
            if (ID != null) { writer.WriteAttribute("id", ClientID); }
            writer.WriteAttribute("name", Name);
            Attributes.Remove("name");
            Attributes.Render(writer);
        }
        protected internal override void RenderChildren(global::System.Web.UI.HtmlTextWriter writer)
        {
            global::System.Web.UI.WebControls.ListItemCollection items = Items;
            for (global::System.Int32 i = 0; i < items.Count; i++)
            {
                global::System.Web.UI.WebControls.ListItem item = items[i];
                writer.WriteBeginTag("option");
                if (item.Selected) { writer.WriteAttribute("selected", "selected"); }
                writer.WriteAttribute("value", item.Value, true);
                writer.Write(global::System.Web.UI.HtmlTextWriter.TagRightChar);
                writer.Write(global::System.Web.HttpUtility.HtmlEncode(item.Text));
                writer.WriteEndTag("option");
                writer.WriteLine();
            }
        }
        protected override global::System.Object SaveViewState() { return base.SaveViewState(); }
        protected virtual void Select(global::System.Int32[] selectedIndices)
        {
            ClearSelection();
            global::System.Web.UI.WebControls.ListItemCollection items = Items;
            for (global::System.Int32 i = 0; i < selectedIndices.Length; i++)
            {
                global::System.Int32 idx = selectedIndices[i];
                if (idx >= 0 && idx < items.Count) { items[idx].Selected = true; }
            }
        }
        protected override void TrackViewState() { base.TrackViewState(); }
        global::System.Boolean global::System.Web.UI.IPostBackDataHandler.LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection) { return LoadPostData(postDataKey, postCollection); }
        protected virtual global::System.Boolean LoadPostData(global::System.String postDataKey, global::System.Collections.Specialized.NameValueCollection postCollection)
        {
            global::System.String[] selectedItems = postCollection.GetValues(postDataKey);
            global::System.Boolean changed = false;
            if (!Multiple)
            {
                global::System.Int32 oldIndex = SelectedIndex;
                if (selectedItems != null && selectedItems.Length > 0)
                {
                    global::System.Int32 newIndex = FindByValueInternal(selectedItems[0]);
                    if (newIndex != oldIndex) { SelectedIndex = newIndex; changed = true; }
                }
            }
            else
            {
                global::System.Web.UI.WebControls.ListItemCollection items = Items;
                global::System.Boolean[] desired = new global::System.Boolean[items.Count];
                if (selectedItems != null)
                {
                    for (global::System.Int32 i = 0; i < selectedItems.Length; i++)
                    {
                        global::System.Int32 idx = FindByValueInternal(selectedItems[i]);
                        if (idx >= 0) { desired[idx] = true; }
                    }
                }
                for (global::System.Int32 i = 0; i < items.Count; i++)
                {
                    if (items[i].Selected != desired[i]) { items[i].Selected = desired[i]; changed = true; }
                }
            }
            return changed;
        }
        private global::System.Int32 FindByValueInternal(global::System.String value)
        {
            global::System.Web.UI.WebControls.ListItemCollection items = Items;
            for (global::System.Int32 i = 0; i < items.Count; i++)
            {
                if (global::System.String.Equals(items[i].Value, value, global::System.StringComparison.Ordinal)) { return i; }
            }
            return -1;
        }
        void global::System.Web.UI.IPostBackDataHandler.RaisePostDataChangedEvent() { RaisePostDataChangedEvent(); }
        protected virtual void RaisePostDataChangedEvent() { OnServerChange(global::System.EventArgs.Empty); }
        public virtual global::System.String DataMember
        {
            get { global::System.String s = (global::System.String)ViewState["DataMember"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["DataMember"] = value; OnDataPropertyChanged(); }
        }
        public virtual global::System.Object DataSource
        {
            get { return ViewState["DataSource"]; }
            set { ViewState["DataSource"] = value; OnDataPropertyChanged(); }
        }
        public virtual global::System.String DataSourceID
        {
            get { global::System.String s = (global::System.String)ViewState["DataSourceID"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["DataSourceID"] = value; OnDataPropertyChanged(); }
        }
        public virtual global::System.String DataTextField
        {
            get { global::System.String s = (global::System.String)ViewState["DataTextField"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["DataTextField"] = value; OnDataPropertyChanged(); }
        }
        public virtual global::System.String DataValueField
        {
            get { global::System.String s = (global::System.String)ViewState["DataValueField"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["DataValueField"] = value; OnDataPropertyChanged(); }
        }
        public override global::System.String InnerHtml
        {
            get { throw new global::System.NotSupportedException("HtmlSelect does not support InnerHtml."); }
            set { throw new global::System.NotSupportedException("HtmlSelect does not support InnerHtml."); }
        }
        public override global::System.String InnerText
        {
            get { throw new global::System.NotSupportedException("HtmlSelect does not support InnerText."); }
            set { throw new global::System.NotSupportedException("HtmlSelect does not support InnerText."); }
        }
        protected global::System.Boolean IsBoundUsingDataSourceID { get { return DataSourceID.Length > 0; } }
        public global::System.Web.UI.WebControls.ListItemCollection Items
        {
            get { if (_items == null) { _items = new global::System.Web.UI.WebControls.ListItemCollection(); } return _items; }
        }
        public global::System.Boolean Multiple
        {
            get { global::System.String s = Attributes["multiple"]; return s != null && global::System.String.Equals(s, "multiple", global::System.StringComparison.OrdinalIgnoreCase); }
            set { if (value) { Attributes["multiple"] = "multiple"; } else { Attributes.Remove("multiple"); } }
        }
        public global::System.String Name
        {
            get { return UniqueID; }
            set { }
        }
        protected global::System.Boolean RequiresDataBinding { get { return _requiresDataBinding; } set { _requiresDataBinding = value; } }
        public virtual global::System.Int32 SelectedIndex
        {
            get
            {
                global::System.Web.UI.WebControls.ListItemCollection items = Items;
                for (global::System.Int32 i = 0; i < items.Count; i++) { if (items[i].Selected) { return i; } }
                if (items.Count > 0 && !Multiple) { return 0; }
                return -1;
            }
            set
            {
                ClearSelection();
                global::System.Web.UI.WebControls.ListItemCollection items = Items;
                if (value >= 0 && value < items.Count) { items[value].Selected = true; }
            }
        }
        protected virtual global::System.Int32[] SelectedIndices
        {
            get
            {
                global::System.Web.UI.WebControls.ListItemCollection items = Items;
                global::System.Collections.Generic.List<global::System.Int32> list = new global::System.Collections.Generic.List<global::System.Int32>();
                for (global::System.Int32 i = 0; i < items.Count; i++) { if (items[i].Selected) { list.Add(i); } }
                return list.ToArray();
            }
        }
        public global::System.Int32 Size
        {
            get { global::System.String s = Attributes["size"]; return s == null ? -1 : global::System.Int32.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture); }
            set { if (value < 0) { Attributes.Remove("size"); } else { Attributes["size"] = value.ToString(global::System.Globalization.CultureInfo.InvariantCulture); } }
        }
        public global::System.String Value
        {
            get { global::System.Int32 idx = SelectedIndex; global::System.Web.UI.WebControls.ListItemCollection items = Items; return (idx >= 0 && idx < items.Count) ? items[idx].Value : global::System.String.Empty; }
            set { SelectedIndex = FindByValueInternal(value); }
        }
        public event global::System.EventHandler ServerChange { add { Events.AddHandler(EventServerChange, value); } remove { Events.RemoveHandler(EventServerChange, value); } }
    }
    public class HtmlTable : global::System.Web.UI.HtmlControls.HtmlContainerControl
    {
        private global::System.Web.UI.HtmlControls.HtmlTableRowCollection _rows;
        public HtmlTable() : base("table") { }
        protected internal override void RenderChildren(global::System.Web.UI.HtmlTextWriter writer)
        {
            writer.WriteLine();
            writer.Indent = writer.Indent + 1;
            base.RenderChildren(writer);
            writer.Indent = writer.Indent - 1;
        }
        protected override void RenderEndTag(global::System.Web.UI.HtmlTextWriter writer)
        {
            base.RenderEndTag(writer);
            writer.WriteLine();
        }
        protected override global::System.Web.UI.ControlCollection CreateControlCollection()
        {
            return new HtmlTableRowControlCollection(this);
        }
        public global::System.String Align
        {
            get { global::System.String s = Attributes["align"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["align"] = value; }
        }
        public global::System.String BgColor
        {
            get { global::System.String s = Attributes["bgcolor"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["bgcolor"] = value; }
        }
        public global::System.Int32 Border
        {
            get { global::System.String s = Attributes["border"]; return s == null ? -1 : global::System.Int32.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture); }
            set { if (value < 0) { Attributes.Remove("border"); } else { Attributes["border"] = value.ToString(global::System.Globalization.CultureInfo.InvariantCulture); } }
        }
        public global::System.String BorderColor
        {
            get { global::System.String s = Attributes["bordercolor"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["bordercolor"] = value; }
        }
        public global::System.Int32 CellPadding
        {
            get { global::System.String s = Attributes["cellpadding"]; return s == null ? -1 : global::System.Int32.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture); }
            set { if (value < 0) { Attributes.Remove("cellpadding"); } else { Attributes["cellpadding"] = value.ToString(global::System.Globalization.CultureInfo.InvariantCulture); } }
        }
        public global::System.Int32 CellSpacing
        {
            get { global::System.String s = Attributes["cellspacing"]; return s == null ? -1 : global::System.Int32.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture); }
            set { if (value < 0) { Attributes.Remove("cellspacing"); } else { Attributes["cellspacing"] = value.ToString(global::System.Globalization.CultureInfo.InvariantCulture); } }
        }
        public override global::System.String InnerHtml
        {
            get { throw new global::System.NotSupportedException("HtmlTable does not support InnerHtml."); }
            set { throw new global::System.NotSupportedException("HtmlTable does not support InnerHtml."); }
        }
        public override global::System.String InnerText
        {
            get { throw new global::System.NotSupportedException("HtmlTable does not support InnerText."); }
            set { throw new global::System.NotSupportedException("HtmlTable does not support InnerText."); }
        }
        public global::System.String Height
        {
            get { global::System.String s = Attributes["height"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["height"] = value; }
        }
        public global::System.String Width
        {
            get { global::System.String s = Attributes["width"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["width"] = value; }
        }
        public virtual global::System.Web.UI.HtmlControls.HtmlTableRowCollection Rows
        {
            get { if (_rows == null) { _rows = new global::System.Web.UI.HtmlControls.HtmlTableRowCollection(this); } return _rows; }
        }
        protected class HtmlTableRowControlCollection : global::System.Web.UI.ControlCollection
        {
            internal HtmlTableRowControlCollection(global::System.Web.UI.Control owner) : base(owner) { }
            public override void Add(global::System.Web.UI.Control child)
            {
                if (!(child is global::System.Web.UI.HtmlControls.HtmlTableRow)) { throw new global::System.ArgumentException("HtmlTable rows must be HtmlTableRow."); }
                base.Add(child);
            }
            public override void AddAt(global::System.Int32 index, global::System.Web.UI.Control child)
            {
                if (!(child is global::System.Web.UI.HtmlControls.HtmlTableRow)) { throw new global::System.ArgumentException("HtmlTable rows must be HtmlTableRow."); }
                base.AddAt(index, child);
            }
        }
    }
    public class HtmlTableRow : global::System.Web.UI.HtmlControls.HtmlContainerControl
    {
        private global::System.Web.UI.HtmlControls.HtmlTableCellCollection _cells;
        public HtmlTableRow() : base("tr") { }
        protected internal override void RenderChildren(global::System.Web.UI.HtmlTextWriter writer)
        {
            writer.WriteLine();
            writer.Indent = writer.Indent + 1;
            base.RenderChildren(writer);
            writer.Indent = writer.Indent - 1;
        }
        protected override void RenderEndTag(global::System.Web.UI.HtmlTextWriter writer)
        {
            base.RenderEndTag(writer);
            writer.WriteLine();
        }
        protected override global::System.Web.UI.ControlCollection CreateControlCollection()
        {
            return new HtmlTableCellControlCollection(this);
        }
        public global::System.String Align
        {
            get { global::System.String s = Attributes["align"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["align"] = value; }
        }
        public virtual global::System.Web.UI.HtmlControls.HtmlTableCellCollection Cells
        {
            get { if (_cells == null) { _cells = new global::System.Web.UI.HtmlControls.HtmlTableCellCollection(this); } return _cells; }
        }
        public global::System.String BgColor
        {
            get { global::System.String s = Attributes["bgcolor"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["bgcolor"] = value; }
        }
        public global::System.String BorderColor
        {
            get { global::System.String s = Attributes["bordercolor"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["bordercolor"] = value; }
        }
        public global::System.String Height
        {
            get { global::System.String s = Attributes["height"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["height"] = value; }
        }
        public override global::System.String InnerHtml
        {
            get { throw new global::System.NotSupportedException("HtmlTableRow does not support InnerHtml."); }
            set { throw new global::System.NotSupportedException("HtmlTableRow does not support InnerHtml."); }
        }
        public override global::System.String InnerText
        {
            get { throw new global::System.NotSupportedException("HtmlTableRow does not support InnerText."); }
            set { throw new global::System.NotSupportedException("HtmlTableRow does not support InnerText."); }
        }
        public global::System.String VAlign
        {
            get { global::System.String s = Attributes["valign"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["valign"] = value; }
        }
        protected class HtmlTableCellControlCollection : global::System.Web.UI.ControlCollection
        {
            internal HtmlTableCellControlCollection(global::System.Web.UI.Control owner) : base(owner) { }
            public override void Add(global::System.Web.UI.Control child)
            {
                if (!(child is global::System.Web.UI.HtmlControls.HtmlTableCell)) { throw new global::System.ArgumentException("HtmlTableRow cells must be HtmlTableCell."); }
                base.Add(child);
            }
            public override void AddAt(global::System.Int32 index, global::System.Web.UI.Control child)
            {
                if (!(child is global::System.Web.UI.HtmlControls.HtmlTableCell)) { throw new global::System.ArgumentException("HtmlTableRow cells must be HtmlTableCell."); }
                base.AddAt(index, child);
            }
        }
    }
    public class HtmlTableCell : global::System.Web.UI.HtmlControls.HtmlContainerControl
    {
        public HtmlTableCell() : base("td") { }
        public HtmlTableCell(global::System.String tagName) : base(tagName) { }
        protected override void RenderEndTag(global::System.Web.UI.HtmlTextWriter writer)
        {
            base.RenderEndTag(writer);
            writer.WriteLine();
        }
        public global::System.String Align
        {
            get { global::System.String s = Attributes["align"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["align"] = value; }
        }
        public global::System.String BgColor
        {
            get { global::System.String s = Attributes["bgcolor"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["bgcolor"] = value; }
        }
        public global::System.String BorderColor
        {
            get { global::System.String s = Attributes["bordercolor"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["bordercolor"] = value; }
        }
        public global::System.Int32 ColSpan
        {
            get { global::System.String s = Attributes["colspan"]; return s == null ? -1 : global::System.Int32.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture); }
            set { if (value < 0) { Attributes.Remove("colspan"); } else { Attributes["colspan"] = value.ToString(global::System.Globalization.CultureInfo.InvariantCulture); } }
        }
        public global::System.String Height
        {
            get { global::System.String s = Attributes["height"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["height"] = value; }
        }
        public global::System.Boolean NoWrap
        {
            get { global::System.String s = Attributes["nowrap"]; return s != null && global::System.String.Equals(s, "nowrap", global::System.StringComparison.OrdinalIgnoreCase); }
            set { if (value) { Attributes["nowrap"] = "nowrap"; } else { Attributes.Remove("nowrap"); } }
        }
        public global::System.Int32 RowSpan
        {
            get { global::System.String s = Attributes["rowspan"]; return s == null ? -1 : global::System.Int32.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture); }
            set { if (value < 0) { Attributes.Remove("rowspan"); } else { Attributes["rowspan"] = value.ToString(global::System.Globalization.CultureInfo.InvariantCulture); } }
        }
        public global::System.String VAlign
        {
            get { global::System.String s = Attributes["valign"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["valign"] = value; }
        }
        public global::System.String Width
        {
            get { global::System.String s = Attributes["width"]; return s == null ? global::System.String.Empty : s; }
            set { Attributes["width"] = value; }
        }
    }
    public sealed class HtmlTableCellCollection : global::System.Collections.ICollection, global::System.Collections.IEnumerable
    {
        private readonly global::System.Web.UI.Control _owner;
        internal HtmlTableCellCollection(global::System.Web.UI.Control owner) { _owner = owner; }
        public void Add(global::System.Web.UI.HtmlControls.HtmlTableCell cell) { Insert(-1, cell); }
        public void Insert(global::System.Int32 index, global::System.Web.UI.HtmlControls.HtmlTableCell cell) { _owner.Controls.AddAt(index, cell); }
        public void Clear() { if (_owner.HasControls()) { _owner.Controls.Clear(); } }
        public global::System.Collections.IEnumerator GetEnumerator() { return _owner.Controls.GetEnumerator(); }
        public void CopyTo(global::System.Array array, global::System.Int32 index)
        {
            global::System.Collections.IEnumerator e = GetEnumerator();
            global::System.Int32 i = index;
            while (e.MoveNext()) { array.SetValue(e.Current, i); i++; }
        }
        public void Remove(global::System.Web.UI.HtmlControls.HtmlTableCell cell) { _owner.Controls.Remove(cell); }
        public void RemoveAt(global::System.Int32 index) { _owner.Controls.RemoveAt(index); }
        public global::System.Int32 Count { get { return _owner.Controls.Count; } }
        public global::System.Web.UI.HtmlControls.HtmlTableCell this[global::System.Int32 index] { get { return (global::System.Web.UI.HtmlControls.HtmlTableCell)_owner.Controls[index]; } }
        public global::System.Object SyncRoot { get { return this; } }
        public global::System.Boolean IsReadOnly { get { return false; } }
        public global::System.Boolean IsSynchronized { get { return false; } }
    }
    public sealed class HtmlTableRowCollection : global::System.Collections.ICollection, global::System.Collections.IEnumerable
    {
        private readonly global::System.Web.UI.Control _owner;
        internal HtmlTableRowCollection(global::System.Web.UI.Control owner) { _owner = owner; }
        public void Add(global::System.Web.UI.HtmlControls.HtmlTableRow row) { Insert(-1, row); }
        public void Insert(global::System.Int32 index, global::System.Web.UI.HtmlControls.HtmlTableRow row) { _owner.Controls.AddAt(index, row); }
        public void Clear() { if (_owner.HasControls()) { _owner.Controls.Clear(); } }
        public void CopyTo(global::System.Array array, global::System.Int32 index)
        {
            global::System.Collections.IEnumerator e = GetEnumerator();
            global::System.Int32 i = index;
            while (e.MoveNext()) { array.SetValue(e.Current, i); i++; }
        }
        public global::System.Collections.IEnumerator GetEnumerator() { return _owner.Controls.GetEnumerator(); }
        public void Remove(global::System.Web.UI.HtmlControls.HtmlTableRow row) { _owner.Controls.Remove(row); }
        public void RemoveAt(global::System.Int32 index) { _owner.Controls.RemoveAt(index); }
        public global::System.Int32 Count { get { return _owner.Controls.Count; } }
        public global::System.Web.UI.HtmlControls.HtmlTableRow this[global::System.Int32 index] { get { return (global::System.Web.UI.HtmlControls.HtmlTableRow)_owner.Controls[index]; } }
        public global::System.Object SyncRoot { get { return this; } }
        public global::System.Boolean IsReadOnly { get { return false; } }
        public global::System.Boolean IsSynchronized { get { return false; } }
    }
    public class HtmlForm : global::System.Web.UI.HtmlControls.HtmlContainerControl
    {
        public HtmlForm() : base("form") { }
        protected internal override void OnInit(global::System.EventArgs e)
        {
            base.OnInit(e);
        }
        protected internal override void OnPreRender(global::System.EventArgs e)
        {
            base.OnPreRender(e);
        }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            writer.WriteAttribute("name", Name);
            Attributes.Remove("name");
            writer.WriteAttribute("method", Method);
            Attributes.Remove("method");
            writer.WriteAttribute("action", GetActionAttribute(), true);
            Attributes.Remove("action");
            global::System.String enctype = (global::System.String)ViewState["Enctype"];
            if (!string.IsNullOrEmpty(enctype)) { writer.WriteAttribute("enctype", enctype); }
            global::System.String target = (global::System.String)ViewState["Target"];
            if (!string.IsNullOrEmpty(target)) { writer.WriteAttribute("target", target); }
            if (ID != null) { writer.WriteAttribute("id", ClientID); }
            Attributes.Render(writer);
        }
        private global::System.String GetActionAttribute()
        {
            global::System.String action = (global::System.String)ViewState["Action"];
            if (!string.IsNullOrEmpty(action)) { return action; }
            global::System.Web.HttpRequest req = (Context != null) ? Context.Request : null;
            if (req != null)
            {
                global::System.String path = req.CurrentExecutionFilePath;
                if (!string.IsNullOrEmpty(path))
                {
                    global::System.String qs = req.QueryString != null ? req.QueryString.ToString() : null;
                    if (!string.IsNullOrEmpty(qs)) { return path + "?" + qs; }
                    return path;
                }
            }
            return global::System.String.Empty;
        }
        protected override global::System.Web.UI.ControlCollection CreateControlCollection()
        {
            return new global::System.Web.UI.ControlCollection(this);
        }
        protected internal override void Render(global::System.Web.UI.HtmlTextWriter output)
        {
            RenderBeginTag(output);
            RenderChildren(output);
            RenderEndTag(output);
        }
        protected internal override void RenderChildren(global::System.Web.UI.HtmlTextWriter writer)
        {
            // As the page form, emit the page-registered hidden fields (__VIEWSTATE,
            // __VIEWSTATEGENERATOR, __EVENTTARGET, __EVENTARGUMENT) and client scripts INSIDE
            // the <form>, then the child controls, then the startup scripts.
            global::System.Web.UI.Page page = Page;
            if (page != null)
            {
                writer.WriteLine();
                page.RenderViewStateFields(writer);
                page.ClientScript.RenderClientScriptBlocks(writer);
            }
            base.RenderChildren(writer);
            if (page != null)
            {
                page.ClientScript.RenderStartupScripts(writer);
            }
        }
        public override void RenderControl(global::System.Web.UI.HtmlTextWriter writer)
        {
            base.RenderControl(writer);
        }
        public global::System.String Action
        {
            get { global::System.String s = (global::System.String)ViewState["Action"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["Action"] = value; }
        }
        public global::System.String DefaultButton
        {
            get { global::System.String s = (global::System.String)ViewState["DefaultButton"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["DefaultButton"] = value; }
        }
        public global::System.String DefaultFocus
        {
            get { global::System.String s = (global::System.String)ViewState["DefaultFocus"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["DefaultFocus"] = value; }
        }
        public global::System.String Enctype
        {
            get { global::System.String s = (global::System.String)ViewState["Enctype"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["Enctype"] = value; }
        }
        public global::System.String Method
        {
            get { global::System.String s = (global::System.String)ViewState["Method"]; return string.IsNullOrEmpty(s) ? "post" : s; }
            set { ViewState["Method"] = value; }
        }
        public virtual global::System.String Name
        {
            get { return UniqueID; }
            set { /* Name follows UniqueID for the server form */ }
        }
        public virtual global::System.Boolean SubmitDisabledControls
        {
            get { global::System.Object o = ViewState["SubmitDisabledControls"]; return o != null && (global::System.Boolean)o; }
            set { ViewState["SubmitDisabledControls"] = value; }
        }
        public global::System.String Target
        {
            get { global::System.String s = (global::System.String)ViewState["Target"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["Target"] = value; }
        }
        public override global::System.String UniqueID { get { return base.UniqueID; } }
        public override global::System.String ClientID { get { return base.ClientID; } }
    }

    // ===== HTML5 / extended element controls =====
    public class HtmlElement : global::System.Web.UI.HtmlControls.HtmlContainerControl
    {
        public HtmlElement() : base("div") { }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            global::System.String manifest = (global::System.String)ViewState["manifest"];
            if (manifest != null) { Attributes["manifest"] = manifest; }
            base.RenderAttributes(writer);
        }
        public global::System.String Manifest
        {
            get { global::System.String s = (global::System.String)ViewState["manifest"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["manifest"] = value; }
        }
    }
    public class HtmlArea : global::System.Web.UI.HtmlControls.HtmlControl
    {
        public HtmlArea() : base("area") { }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            global::System.String href = (global::System.String)ViewState["href"];
            if (href != null) { Attributes["href"] = ResolveClientUrl(href); }
            base.RenderAttributes(writer);
            writer.Write(' ');
            writer.Write('/');
        }
        public global::System.String Href
        {
            get { global::System.String s = (global::System.String)ViewState["href"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["href"] = value; }
        }
    }
    public class HtmlEmbed : global::System.Web.UI.HtmlControls.HtmlContainerControl
    {
        public HtmlEmbed() : base("embed") { }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            global::System.String src = (global::System.String)ViewState["src"];
            if (src != null) { Attributes["src"] = ResolveClientUrl(src); }
            base.RenderAttributes(writer);
        }
        public global::System.String Src
        {
            get { global::System.String s = (global::System.String)ViewState["src"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["src"] = value; }
        }
    }
    public class HtmlIframe : global::System.Web.UI.HtmlControls.HtmlContainerControl
    {
        public HtmlIframe() : base("iframe") { }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            global::System.String src = (global::System.String)ViewState["src"];
            if (src != null) { Attributes["src"] = ResolveClientUrl(src); }
            base.RenderAttributes(writer);
        }
        public global::System.String Src
        {
            get { global::System.String s = (global::System.String)ViewState["src"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["src"] = value; }
        }
    }
    public class HtmlSource : global::System.Web.UI.HtmlControls.HtmlControl
    {
        public HtmlSource() : base("source") { }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            global::System.String src = (global::System.String)ViewState["src"];
            if (src != null) { Attributes["src"] = ResolveClientUrl(src); }
            base.RenderAttributes(writer);
            writer.Write(' ');
            writer.Write('/');
        }
        public global::System.String Src
        {
            get { global::System.String s = (global::System.String)ViewState["src"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["src"] = value; }
        }
    }
    public class HtmlTrack : global::System.Web.UI.HtmlControls.HtmlControl
    {
        public HtmlTrack() : base("track") { }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            global::System.String src = (global::System.String)ViewState["src"];
            if (src != null) { Attributes["src"] = ResolveClientUrl(src); }
            base.RenderAttributes(writer);
            writer.Write(' ');
            writer.Write('/');
        }
        public global::System.String Src
        {
            get { global::System.String s = (global::System.String)ViewState["src"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["src"] = value; }
        }
    }
    public class HtmlVideo : global::System.Web.UI.HtmlControls.HtmlContainerControl
    {
        public HtmlVideo() : base("video") { }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            global::System.String src = (global::System.String)ViewState["src"];
            if (src != null) { Attributes["src"] = ResolveClientUrl(src); }
            global::System.String poster = (global::System.String)ViewState["poster"];
            if (poster != null) { Attributes["poster"] = ResolveClientUrl(poster); }
            base.RenderAttributes(writer);
        }
        public global::System.String Poster
        {
            get { global::System.String s = (global::System.String)ViewState["poster"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["poster"] = value; }
        }
        public global::System.String Src
        {
            get { global::System.String s = (global::System.String)ViewState["src"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["src"] = value; }
        }
    }
    public class HtmlAudio : global::System.Web.UI.HtmlControls.HtmlContainerControl
    {
        public HtmlAudio() : base("audio") { }
        protected override void RenderAttributes(global::System.Web.UI.HtmlTextWriter writer)
        {
            global::System.String src = (global::System.String)ViewState["src"];
            if (src != null) { Attributes["src"] = ResolveClientUrl(src); }
            base.RenderAttributes(writer);
        }
        public global::System.String Src
        {
            get { global::System.String s = (global::System.String)ViewState["src"]; return s == null ? global::System.String.Empty : s; }
            set { ViewState["src"] = value; }
        }
    }
}
