// <auto-generated> clean-room System.Web API skeleton.
// Bodies are NotImplementedException; this proves signature completeness only.
#nullable disable
#pragma warning disable

namespace System.Web.Mail
{
    public class SmtpMail
    {
        private static global::System.String s_smtpServer = string.Empty;
        internal SmtpMail() { }
        public static global::System.String SmtpServer { get { return s_smtpServer; } set { s_smtpServer = value == null ? string.Empty : value; } }
        public static void Send(global::System.String from, global::System.String to, global::System.String subject, global::System.String messageText)
        {
            global::System.Web.Mail.MailMessage m = new global::System.Web.Mail.MailMessage();
            m.From = from;
            m.To = to;
            m.Subject = subject;
            m.Body = messageText;
            Send(m);
        }
        public static void Send(global::System.Web.Mail.MailMessage message)
        {
            if (message == null) { throw new global::System.ArgumentNullException("message"); }
            using (global::System.Net.Mail.MailMessage net = message.ToNetMailMessage())
            {
                global::System.Net.Mail.SmtpClient client = CreateClient();
                client.Send(net);
            }
        }
        // Builds an SmtpClient from the legacy SmtpServer (host[:port]) setting, falling
        // back to the System.Net.Mail configured defaults when no server is specified.
        private static global::System.Net.Mail.SmtpClient CreateClient()
        {
            global::System.String server = s_smtpServer;
            if (string.IsNullOrEmpty(server)) { return new global::System.Net.Mail.SmtpClient(); }
            global::System.String host = server;
            global::System.Int32 port = 0;
            global::System.Int32 colon = server.LastIndexOf(':');
            if (colon > 0 && colon < server.Length - 1)
            {
                global::System.String portPart = server.Substring(colon + 1);
                global::System.Int32 parsed;
                if (global::System.Int32.TryParse(portPart, out parsed))
                {
                    host = server.Substring(0, colon);
                    port = parsed;
                }
            }
            if (port > 0) { return new global::System.Net.Mail.SmtpClient(host, port); }
            return new global::System.Net.Mail.SmtpClient(host);
        }
    }
    public enum MailFormat
    {
        Text = 0,
        Html = 1,
    }
    public enum MailPriority
    {
        Normal = 0,
        Low = 1,
        High = 2,
    }
    public enum MailEncoding
    {
        UUEncode = 0,
        Base64 = 1,
    }
    public class MailAttachment
    {
        private readonly global::System.String _filename;
        private readonly global::System.Web.Mail.MailEncoding _encoding;
        public MailAttachment(global::System.String filename) : this(filename, global::System.Web.Mail.MailEncoding.Base64) { }
        public MailAttachment(global::System.String filename, global::System.Web.Mail.MailEncoding encoding)
        {
            if (filename == null) { throw new global::System.ArgumentNullException("filename"); }
            // Legacy semantics: the file must exist on construction.
            try
            {
                global::System.IO.FileInfo fi = new global::System.IO.FileInfo(filename);
                if (fi.DirectoryName == null || !fi.Exists)
                {
                    throw new global::System.Web.HttpException("Cannot find attachment file '" + filename + "'.");
                }
            }
            catch (global::System.Web.HttpException) { throw; }
            catch (global::System.Exception)
            {
                throw new global::System.Web.HttpException("Cannot find attachment file '" + filename + "'.");
            }
            _filename = filename;
            _encoding = encoding;
        }
        public global::System.String Filename { get { return _filename; } }
        public global::System.Web.Mail.MailEncoding Encoding { get { return _encoding; } }
    }
    public class MailMessage
    {
        private global::System.String _from;
        private global::System.String _to;
        private global::System.String _cc;
        private global::System.String _bcc;
        private global::System.String _subject;
        private global::System.String _body;
        private global::System.Web.Mail.MailPriority _priority = global::System.Web.Mail.MailPriority.Normal;
        private global::System.Web.Mail.MailFormat _bodyFormat = global::System.Web.Mail.MailFormat.Text;
        private global::System.String _urlContentBase;
        private global::System.String _urlContentLocation;
        private global::System.Text.Encoding _bodyEncoding;
        private readonly global::System.Collections.Specialized.ListDictionary _headers = new global::System.Collections.Specialized.ListDictionary();
        private readonly global::System.Collections.Specialized.ListDictionary _fields = new global::System.Collections.Specialized.ListDictionary();
        private readonly global::System.Collections.ArrayList _attachments = new global::System.Collections.ArrayList();

        public MailMessage() { }
        public global::System.String From { get { return _from; } set { _from = value; } }
        public global::System.String To { get { return _to; } set { _to = value; } }
        public global::System.String Cc { get { return _cc; } set { _cc = value; } }
        public global::System.String Bcc { get { return _bcc; } set { _bcc = value; } }
        public global::System.String Subject { get { return _subject; } set { _subject = value; } }
        public global::System.Web.Mail.MailPriority Priority { get { return _priority; } set { _priority = value; } }
        public global::System.String UrlContentBase { get { return _urlContentBase; } set { _urlContentBase = value; } }
        public global::System.String UrlContentLocation { get { return _urlContentLocation; } set { _urlContentLocation = value; } }
        public global::System.String Body { get { return _body; } set { _body = value; } }
        public global::System.Web.Mail.MailFormat BodyFormat { get { return _bodyFormat; } set { _bodyFormat = value; } }
        public global::System.Text.Encoding BodyEncoding { get { return _bodyEncoding; } set { _bodyEncoding = value; } }
        public global::System.Collections.IDictionary Headers { get { return _headers; } }
        public global::System.Collections.IDictionary Fields { get { return _fields; } }
        public global::System.Collections.IList Attachments { get { return _attachments; } }

        // Maps this legacy message onto a System.Net.Mail.MailMessage for delivery.
        internal global::System.Net.Mail.MailMessage ToNetMailMessage()
        {
            global::System.Net.Mail.MailMessage net = new global::System.Net.Mail.MailMessage();
            if (!string.IsNullOrEmpty(_from)) { net.From = new global::System.Net.Mail.MailAddress(_from); }
            AddAddresses(net.To, _to);
            AddAddresses(net.CC, _cc);
            AddAddresses(net.Bcc, _bcc);
            net.Subject = _subject == null ? string.Empty : _subject;
            net.Body = _body == null ? string.Empty : _body;
            net.IsBodyHtml = _bodyFormat == global::System.Web.Mail.MailFormat.Html;
            if (_bodyEncoding != null)
            {
                net.BodyEncoding = _bodyEncoding;
                net.SubjectEncoding = _bodyEncoding;
            }
            switch (_priority)
            {
                case global::System.Web.Mail.MailPriority.High: net.Priority = global::System.Net.Mail.MailPriority.High; break;
                case global::System.Web.Mail.MailPriority.Low: net.Priority = global::System.Net.Mail.MailPriority.Low; break;
                default: net.Priority = global::System.Net.Mail.MailPriority.Normal; break;
            }
            foreach (global::System.Collections.DictionaryEntry de in _headers)
            {
                if (de.Key != null) { net.Headers.Add(global::System.Convert.ToString(de.Key), global::System.Convert.ToString(de.Value)); }
            }
            for (global::System.Int32 i = 0; i < _attachments.Count; i++)
            {
                global::System.Web.Mail.MailAttachment att = _attachments[i] as global::System.Web.Mail.MailAttachment;
                if (att != null && !string.IsNullOrEmpty(att.Filename))
                {
                    net.Attachments.Add(new global::System.Net.Mail.Attachment(att.Filename));
                }
            }
            return net;
        }
        private static void AddAddresses(global::System.Net.Mail.MailAddressCollection col, global::System.String list)
        {
            if (string.IsNullOrEmpty(list)) { return; }
            // Legacy MailMessage uses ';' as the address separator.
            global::System.String[] parts = list.Split(';', ',');
            for (global::System.Int32 i = 0; i < parts.Length; i++)
            {
                global::System.String addr = parts[i].Trim();
                if (addr.Length != 0) { col.Add(new global::System.Net.Mail.MailAddress(addr)); }
            }
        }
    }
}
