// <auto-generated> clean-room System.Web API skeleton.
// Bodies are NotImplementedException; this proves signature completeness only.
#nullable disable
#pragma warning disable

namespace System.Web.Security.AntiXss
{
    public enum LowerCodeCharts : global::System.Int64
    {
        None = 0,
        BasicLatin = 1,
        C1ControlsAndLatin1Supplement = 2,
        LatinExtendedA = 4,
        LatinExtendedB = 8,
        IpaExtensions = 16,
        SpacingModifierLetters = 32,
        CombiningDiacriticalMarks = 64,
        GreekAndCoptic = 128,
        Cyrillic = 256,
        CyrillicSupplement = 512,
        Armenian = 1024,
        Hebrew = 2048,
        Arabic = 4096,
        Syriac = 8192,
        ArabicSupplement = 16384,
        Thaana = 32768,
        Nko = 65536,
        Samaritan = 131072,
        Devanagari = 262144,
        Bengali = 524288,
        Gurmukhi = 1048576,
        Gujarati = 2097152,
        Oriya = 4194304,
        Tamil = 8388608,
        Telugu = 16777216,
        Kannada = 33554432,
        Malayalam = 67108864,
        Sinhala = 134217728,
        Thai = 268435456,
        Lao = 536870912,
        Tibetan = 1073741824,
        Default = 127,
    }
    public enum LowerMidCodeCharts : global::System.Int64
    {
        None = 0,
        Myanmar = 1,
        Georgian = 2,
        HangulJamo = 4,
        Ethiopic = 8,
        EthiopicSupplement = 16,
        Cherokee = 32,
        UnifiedCanadianAboriginalSyllabics = 64,
        Ogham = 128,
        Runic = 256,
        Tagalog = 512,
        Hanunoo = 1024,
        Buhid = 2048,
        Tagbanwa = 4096,
        Khmer = 8192,
        Mongolian = 16384,
        UnifiedCanadianAboriginalSyllabicsExtended = 32768,
        Limbu = 65536,
        TaiLe = 131072,
        NewTaiLue = 262144,
        KhmerSymbols = 524288,
        Buginese = 1048576,
        TaiTham = 2097152,
        Balinese = 4194304,
        Sudanese = 8388608,
        Lepcha = 16777216,
        OlChiki = 33554432,
        VedicExtensions = 67108864,
        PhoneticExtensions = 134217728,
        PhoneticExtensionsSupplement = 268435456,
        CombiningDiacriticalMarksSupplement = 536870912,
        LatinExtendedAdditional = 1073741824,
    }
    public enum MidCodeCharts : global::System.Int64
    {
        None = 0,
        GreekExtended = 1,
        GeneralPunctuation = 2,
        SuperscriptsAndSubscripts = 4,
        CurrencySymbols = 8,
        CombiningDiacriticalMarksForSymbols = 16,
        LetterlikeSymbols = 32,
        NumberForms = 64,
        Arrows = 128,
        MathematicalOperators = 256,
        MiscellaneousTechnical = 512,
        ControlPictures = 1024,
        OpticalCharacterRecognition = 2048,
        EnclosedAlphanumerics = 4096,
        BoxDrawing = 8192,
        BlockElements = 16384,
        GeometricShapes = 32768,
        MiscellaneousSymbols = 65536,
        Dingbats = 131072,
        MiscellaneousMathematicalSymbolsA = 262144,
        SupplementalArrowsA = 524288,
        BraillePatterns = 1048576,
        SupplementalArrowsB = 2097152,
        MiscellaneousMathematicalSymbolsB = 4194304,
        SupplementalMathematicalOperators = 8388608,
        MiscellaneousSymbolsAndArrows = 16777216,
        Glagolitic = 33554432,
        LatinExtendedC = 67108864,
        Coptic = 134217728,
        GeorgianSupplement = 268435456,
        Tifinagh = 536870912,
        EthiopicExtended = 16384,
    }
    public enum UpperMidCodeCharts : global::System.Int64
    {
        None = 0,
        CyrillicExtendedA = 1,
        SupplementalPunctuation = 2,
        CjkRadicalsSupplement = 4,
        KangxiRadicals = 8,
        IdeographicDescriptionCharacters = 16,
        CjkSymbolsAndPunctuation = 32,
        Hiragana = 64,
        Katakana = 128,
        Bopomofo = 256,
        HangulCompatibilityJamo = 512,
        Kanbun = 1024,
        BopomofoExtended = 2048,
        CjkStrokes = 4096,
        KatakanaPhoneticExtensions = 8192,
        EnclosedCjkLettersAndMonths = 16384,
        CjkCompatibility = 32768,
        CjkUnifiedIdeographsExtensionA = 65536,
        YijingHexagramSymbols = 131072,
        CjkUnifiedIdeographs = 262144,
        YiSyllables = 524288,
        YiRadicals = 1048576,
        Lisu = 2097152,
        Vai = 4194304,
        CyrillicExtendedB = 8388608,
        Bamum = 16777216,
        ModifierToneLetters = 33554432,
        LatinExtendedD = 67108864,
        SylotiNagri = 134217728,
        CommonIndicNumberForms = 268435456,
        Phagspa = 536870912,
        Saurashtra = 1073741824,
    }
    public enum UpperCodeCharts
    {
        None = 0,
        DevanagariExtended = 1,
        KayahLi = 2,
        Rejang = 4,
        HangulJamoExtendedA = 8,
        Javanese = 16,
        Cham = 32,
        MyanmarExtendedA = 64,
        TaiViet = 128,
        MeeteiMayek = 256,
        HangulSyllables = 512,
        HangulJamoExtendedB = 1024,
        CjkCompatibilityIdeographs = 2048,
        AlphabeticPresentationForms = 4096,
        ArabicPresentationFormsA = 8192,
        VariationSelectors = 16384,
        VerticalForms = 32768,
        CombiningHalfMarks = 65536,
        CjkCompatibilityForms = 131072,
        SmallFormVariants = 262144,
        ArabicPresentationFormsB = 524288,
        HalfWidthAndFullWidthForms = 1048576,
        Specials = 2097152,
    }
    // A safe-list (allow-list) encoder. Rather than blacklisting known-dangerous
    // characters, every output method emits a small set of explicitly-safe
    // characters verbatim and encodes everything else into the entity/escape
    // form appropriate to the target context (HTML, HTML attribute, XML, CSS,
    // URL, or HTML form URL). This makes the encoder resistant to novel attack
    // vectors that a blacklist would miss.
    public class AntiXssEncoder : global::System.Web.Util.HttpEncoder
    {
        public AntiXssEncoder() { }

        // ---- HttpEncoder overrides (used when this encoder is installed as the
        // application's HttpEncoder via configuration). These delegate to the
        // safe-list helpers so the framework-level Html/Url encoding paths also
        // receive safe-list treatment. ----
        protected internal override void HtmlAttributeEncode(global::System.String value, global::System.IO.TextWriter output)
        {
            if (output == null) { throw new global::System.ArgumentNullException("output"); }
            if (global::System.String.IsNullOrEmpty(value)) { return; }
            HtmlAttributeEncodeCore(value, output);
        }

        protected internal override void HtmlEncode(global::System.String value, global::System.IO.TextWriter output)
        {
            if (output == null) { throw new global::System.ArgumentNullException("output"); }
            if (global::System.String.IsNullOrEmpty(value)) { return; }
            HtmlEncodeCore(value, false, output);
        }

        protected internal override global::System.Byte[] UrlEncode(global::System.Byte[] bytes, global::System.Int32 offset, global::System.Int32 count)
        {
            // The byte-slice URL encoding rules match the base class safe-list
            // percent-encoding; reuse it.
            return base.UrlEncode(bytes, offset, count);
        }

        protected internal override global::System.String UrlPathEncode(global::System.String value)
        {
            return base.UrlPathEncode(value);
        }

        // MarkAsSafe adjusts the global safe-list of Unicode code charts. The
        // chart granularity is preserved in the public API; this clean-room
        // implementation records the supplied flags. The character-level safe-list
        // used by the encoders is the ASCII alphanumeric set and is independent of
        // chart selection, so this records state without altering encoding output.
        public static void MarkAsSafe(global::System.Web.Security.AntiXss.LowerCodeCharts lowerCodeCharts, global::System.Web.Security.AntiXss.LowerMidCodeCharts lowerMidCodeCharts, global::System.Web.Security.AntiXss.MidCodeCharts midCodeCharts, global::System.Web.Security.AntiXss.UpperMidCodeCharts upperMidCodeCharts, global::System.Web.Security.AntiXss.UpperCodeCharts upperCodeCharts)
        {
            s_lowerCodeCharts = lowerCodeCharts;
            s_lowerMidCodeCharts = lowerMidCodeCharts;
            s_midCodeCharts = midCodeCharts;
            s_upperMidCodeCharts = upperMidCodeCharts;
            s_upperCodeCharts = upperCodeCharts;
        }

        private static global::System.Web.Security.AntiXss.LowerCodeCharts s_lowerCodeCharts = global::System.Web.Security.AntiXss.LowerCodeCharts.Default;
        private static global::System.Web.Security.AntiXss.LowerMidCodeCharts s_lowerMidCodeCharts = global::System.Web.Security.AntiXss.LowerMidCodeCharts.None;
        private static global::System.Web.Security.AntiXss.MidCodeCharts s_midCodeCharts = global::System.Web.Security.AntiXss.MidCodeCharts.None;
        private static global::System.Web.Security.AntiXss.UpperMidCodeCharts s_upperMidCodeCharts = global::System.Web.Security.AntiXss.UpperMidCodeCharts.None;
        private static global::System.Web.Security.AntiXss.UpperCodeCharts s_upperCodeCharts = global::System.Web.Security.AntiXss.UpperCodeCharts.None;

        public static global::System.String CssEncode(global::System.String input)
        {
            if (global::System.String.IsNullOrEmpty(input)) { return input; }
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length * 2);
            for (global::System.Int32 i = 0; i < input.Length; i++)
            {
                global::System.Char c = input[i];
                if (IsCssSafe(c))
                {
                    sb.Append(c);
                }
                else
                {
                    // CSS escape: backslash + hex code point + terminating space.
                    sb.Append('\\');
                    sb.Append(((global::System.Int32)c).ToString("X", global::System.Globalization.CultureInfo.InvariantCulture));
                    sb.Append(' ');
                }
            }
            return sb.ToString();
        }

        public static global::System.String HtmlEncode(global::System.String input, global::System.Boolean useNamedEntities)
        {
            if (global::System.String.IsNullOrEmpty(input)) { return input; }
            global::System.IO.StringWriter writer = new global::System.IO.StringWriter(global::System.Globalization.CultureInfo.InvariantCulture);
            HtmlEncodeCore(input, useNamedEntities, writer);
            return writer.ToString();
        }

        public static global::System.String UrlEncode(global::System.String input)
        {
            return UrlEncode(input, global::System.Text.Encoding.UTF8);
        }

        public static global::System.String HtmlFormUrlEncode(global::System.String input)
        {
            return HtmlFormUrlEncode(input, global::System.Text.Encoding.UTF8);
        }

        public static global::System.String UrlEncode(global::System.String input, global::System.Int32 codePage)
        {
            return UrlEncode(input, global::System.Text.Encoding.GetEncoding(codePage));
        }

        public static global::System.String HtmlFormUrlEncode(global::System.String input, global::System.Int32 codePage)
        {
            return HtmlFormUrlEncode(input, global::System.Text.Encoding.GetEncoding(codePage));
        }

        public static global::System.String UrlEncode(global::System.String input, global::System.Text.Encoding inputEncoding)
        {
            if (global::System.String.IsNullOrEmpty(input)) { return input; }
            if (inputEncoding == null) { inputEncoding = global::System.Text.Encoding.UTF8; }
            // URL (query/segment) encoding: spaces become %20.
            return PercentEncode(input, inputEncoding, false);
        }

        public static global::System.String HtmlFormUrlEncode(global::System.String input, global::System.Text.Encoding inputEncoding)
        {
            if (global::System.String.IsNullOrEmpty(input)) { return input; }
            if (inputEncoding == null) { inputEncoding = global::System.Text.Encoding.UTF8; }
            // application/x-www-form-urlencoded: spaces become '+'.
            return PercentEncode(input, inputEncoding, true);
        }

        public static global::System.String XmlEncode(global::System.String input)
        {
            if (global::System.String.IsNullOrEmpty(input)) { return input; }
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length * 2);
            for (global::System.Int32 i = 0; i < input.Length; i++)
            {
                AppendXmlChar(sb, input[i], false);
            }
            return sb.ToString();
        }

        public static global::System.String XmlAttributeEncode(global::System.String input)
        {
            if (global::System.String.IsNullOrEmpty(input)) { return input; }
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length * 2);
            for (global::System.Int32 i = 0; i < input.Length; i++)
            {
                AppendXmlChar(sb, input[i], true);
            }
            return sb.ToString();
        }

        // ---- private safe-list helpers ----

        private static global::System.Boolean IsAlphaNumeric(global::System.Char c)
        {
            return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9');
        }

        private static global::System.Boolean IsHtmlSafe(global::System.Char c)
        {
            if (IsAlphaNumeric(c)) { return true; }
            switch (c)
            {
                case ' ':
                case '.':
                case ',':
                case '-':
                case '_':
                    return true;
                default:
                    return false;
            }
        }

        private static global::System.Boolean IsCssSafe(global::System.Char c)
        {
            // Only ASCII alphanumerics pass through unescaped in CSS contexts.
            return IsAlphaNumeric(c);
        }

        private static void HtmlEncodeCore(global::System.String input, global::System.Boolean useNamedEntities, global::System.IO.TextWriter output)
        {
            for (global::System.Int32 i = 0; i < input.Length; i++)
            {
                global::System.Char c = input[i];
                if (IsHtmlSafe(c))
                {
                    output.Write(c);
                    continue;
                }
                if (useNamedEntities)
                {
                    global::System.String named = GetNamedEntity(c);
                    if (named != null)
                    {
                        output.Write(named);
                        continue;
                    }
                }
                output.Write("&#");
                output.Write(((global::System.Int32)c).ToString(global::System.Globalization.CultureInfo.InvariantCulture));
                output.Write(';');
            }
        }

        private static void HtmlAttributeEncodeCore(global::System.String input, global::System.IO.TextWriter output)
        {
            // Attribute context: encode spaces too, so unquoted-attribute breakouts
            // are impossible.
            for (global::System.Int32 i = 0; i < input.Length; i++)
            {
                global::System.Char c = input[i];
                if (IsAlphaNumeric(c) || c == '.' || c == ',' || c == '-' || c == '_')
                {
                    output.Write(c);
                    continue;
                }
                output.Write("&#");
                output.Write(((global::System.Int32)c).ToString(global::System.Globalization.CultureInfo.InvariantCulture));
                output.Write(';');
            }
        }

        private static global::System.String GetNamedEntity(global::System.Char c)
        {
            switch (c)
            {
                case '<': return "&lt;";
                case '>': return "&gt;";
                case '&': return "&amp;";
                case '"': return "&quot;";
                case '\'': return "&#39;";
                default: return null;
            }
        }

        private static void AppendXmlChar(global::System.Text.StringBuilder sb, global::System.Char c, global::System.Boolean attribute)
        {
            if (IsHtmlSafe(c))
            {
                sb.Append(c);
                return;
            }
            switch (c)
            {
                case '<': sb.Append("&lt;"); return;
                case '>': sb.Append("&gt;"); return;
                case '&': sb.Append("&amp;"); return;
                case '"':
                    if (attribute) { sb.Append("&quot;"); return; }
                    break;
                case '\'':
                    if (attribute) { sb.Append("&apos;"); return; }
                    break;
            }
            sb.Append("&#");
            sb.Append(((global::System.Int32)c).ToString(global::System.Globalization.CultureInfo.InvariantCulture));
            sb.Append(';');
        }

        private static global::System.String PercentEncode(global::System.String input, global::System.Text.Encoding encoding, global::System.Boolean spaceAsPlus)
        {
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length * 2);
            for (global::System.Int32 i = 0; i < input.Length; i++)
            {
                global::System.Char c = input[i];
                if (IsAlphaNumeric(c) || c == '-' || c == '_' || c == '.')
                {
                    sb.Append(c);
                }
                else if (c == ' ')
                {
                    if (spaceAsPlus) { sb.Append('+'); }
                    else { sb.Append("%20"); }
                }
                else
                {
                    global::System.Byte[] bytes = encoding.GetBytes(c.ToString());
                    for (global::System.Int32 b = 0; b < bytes.Length; b++)
                    {
                        sb.Append('%');
                        sb.Append(HexUpper((bytes[b] >> 4) & 0x0F));
                        sb.Append(HexUpper(bytes[b] & 0x0F));
                    }
                }
            }
            return sb.ToString();
        }

        private static global::System.Char HexUpper(global::System.Int32 n)
        {
            if (n <= 9) { return (global::System.Char)(n + '0'); }
            return (global::System.Char)(n - 10 + 'A');
        }
    }
}