// <auto-generated> clean-room System.Web reimplementation.
// Tier 1: in-memory Cache + file/dependency-key CacheDependency are real.
// SQL / output-cache / distributed providers are documented stubs (later tier).
#nullable disable
#pragma warning disable

namespace System.Web.Caching
{
    public class CacheInsertOptions
    {
        private global::System.Web.Caching.CacheDependency _dependencies;
        private global::System.DateTime _absoluteExpiration = global::System.Web.Caching.Cache.NoAbsoluteExpiration;
        private global::System.TimeSpan _slidingExpiration = global::System.Web.Caching.Cache.NoSlidingExpiration;
        private global::System.Web.Caching.CacheItemPriority _priority = global::System.Web.Caching.CacheItemPriority.Default;
        private global::System.Web.Caching.CacheItemRemovedCallback _onRemovedCallback;

        public CacheInsertOptions() { }
        public global::System.Web.Caching.CacheDependency Dependencies { get { return _dependencies; } set { _dependencies = value; } }
        public global::System.DateTime AbsoluteExpiration { get { return _absoluteExpiration; } set { _absoluteExpiration = value; } }
        public global::System.TimeSpan SlidingExpiration { get { return _slidingExpiration; } set { _slidingExpiration = value; } }
        public global::System.Web.Caching.CacheItemPriority Priority { get { return _priority; } set { _priority = value; } }
        public global::System.Web.Caching.CacheItemRemovedCallback OnRemovedCallback { get { return _onRemovedCallback; } set { _onRemovedCallback = value; } }
    }

    public abstract class CacheStoreProvider : global::System.Configuration.Provider.ProviderBase, global::System.IDisposable
    {
        protected CacheStoreProvider() { }
        public abstract void Initialize(global::System.String name, global::System.Collections.Specialized.NameValueCollection config);
        public abstract global::System.Object Add(global::System.String key, global::System.Object item, global::System.Web.Caching.CacheInsertOptions options);
        public abstract global::System.Object Get(global::System.String key);
        public abstract void Insert(global::System.String key, global::System.Object item, global::System.Web.Caching.CacheInsertOptions options);
        public abstract global::System.Object Remove(global::System.String key);
        public abstract global::System.Object Remove(global::System.String key, global::System.Web.Caching.CacheItemRemovedReason reason);
        public abstract global::System.Int64 Trim(global::System.Int32 percent);
        public abstract global::System.Boolean AddDependent(global::System.String key, global::System.Web.Caching.CacheDependency dependency, out global::System.DateTime utcLastUpdated);
        public abstract void RemoveDependent(global::System.String key, global::System.Web.Caching.CacheDependency dependency);
        public abstract void Dispose();
        public abstract global::System.Collections.IDictionaryEnumerator GetEnumerator();
        public abstract global::System.Int64 ItemCount { get; }
        public abstract global::System.Int64 SizeInBytes { get; }
    }

    public delegate void CacheItemRemovedCallback(global::System.String key, global::System.Object value, global::System.Web.Caching.CacheItemRemovedReason reason);
    public delegate void CacheItemUpdateCallback(global::System.String key, global::System.Web.Caching.CacheItemUpdateReason reason, out global::System.Object expensiveObject, out global::System.Web.Caching.CacheDependency dependency, out global::System.DateTime absoluteExpiration, out global::System.TimeSpan slidingExpiration);

    public enum CacheItemPriority
    {
        Low = 1,
        BelowNormal = 2,
        Normal = 3,
        AboveNormal = 4,
        High = 5,
        NotRemovable = 6,
        Default = 3,
    }
    public enum CacheItemRemovedReason
    {
        Removed = 1,
        Expired = 2,
        Underused = 3,
        DependencyChanged = 4,
    }
    public enum CacheItemUpdateReason
    {
        Expired = 1,
        DependencyChanged = 2,
    }

    public sealed class Cache : global::System.Collections.IEnumerable
    {
        // ----- internal entry -----
        private sealed class CacheEntry
        {
            public global::System.String Key;
            public global::System.Object Value;
            public global::System.Web.Caching.CacheDependency Dependency;
            public global::System.DateTime UtcAbsoluteExpiration;   // NoAbsoluteExpiration (UTC sentinel) if none
            public global::System.TimeSpan SlidingExpiration;       // NoSlidingExpiration if none
            public global::System.DateTime UtcLastAccess;           // for sliding
            public global::System.Web.Caching.CacheItemPriority Priority;
            public global::System.Web.Caching.CacheItemRemovedCallback OnRemovedCallback;
            public global::System.Web.Caching.CacheItemUpdateCallback OnUpdateCallback;
            // guards a single removal so a callback fires exactly once
            public global::System.Int32 RemovedFlag;
        }

        // NoAbsoluteExpiration is DateTime.MaxValue; NoSlidingExpiration is TimeSpan.Zero.
        public static readonly global::System.DateTime NoAbsoluteExpiration = global::System.DateTime.MaxValue;
        public static readonly global::System.TimeSpan NoSlidingExpiration = global::System.TimeSpan.Zero;

        // The largest sliding window allowed by the original API (one year).
        private static readonly global::System.TimeSpan s_maxSliding = global::System.TimeSpan.FromDays(365);

        private readonly global::System.Collections.Concurrent.ConcurrentDictionary<global::System.String, CacheEntry> _store =
            new global::System.Collections.Concurrent.ConcurrentDictionary<global::System.String, CacheEntry>(global::System.StringComparer.Ordinal);

        private readonly global::System.Threading.Timer _sweeper;

        public Cache()
        {
            // Lightweight background sweeper for expired/changed items (every 20s).
            _sweeper = new global::System.Threading.Timer(SweepCallback, null,
                global::System.TimeSpan.FromSeconds(20), global::System.TimeSpan.FromSeconds(20));
        }

        // ---------- enumeration ----------
        global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public global::System.Collections.IDictionaryEnumerator GetEnumerator()
        {
            // Snapshot of live (non-expired) entries.
            var snapshot = new global::System.Collections.Hashtable();
            global::System.DateTime utcNow = global::System.DateTime.UtcNow;
            foreach (var kvp in _store)
            {
                CacheEntry e = kvp.Value;
                if (IsExpired(e, utcNow) || (e.Dependency != null && e.Dependency.HasChanged))
                {
                    continue;
                }
                snapshot[kvp.Key] = e.Value;
            }
            return snapshot.GetEnumerator();
        }

        // ---------- get ----------
        public global::System.Object Get(global::System.String key)
        {
            if (key == null) throw new global::System.ArgumentNullException("key");

            CacheEntry e;
            if (!_store.TryGetValue(key, out e))
            {
                return null;
            }

            global::System.DateTime utcNow = global::System.DateTime.UtcNow;
            if (e.Dependency != null && e.Dependency.HasChanged)
            {
                RemoveEntry(key, e, global::System.Web.Caching.CacheItemRemovedReason.DependencyChanged);
                return null;
            }
            if (IsExpired(e, utcNow))
            {
                RemoveEntry(key, e, global::System.Web.Caching.CacheItemRemovedReason.Expired);
                return null;
            }

            // Refresh sliding window on access.
            if (e.SlidingExpiration != NoSlidingExpiration)
            {
                e.UtcLastAccess = utcNow;
                e.UtcAbsoluteExpiration = utcNow.Add(e.SlidingExpiration);
            }
            return e.Value;
        }

        // ---------- insert overloads ----------
        public void Insert(global::System.String key, global::System.Object value)
        {
            DoInsert(key, value, null, NoAbsoluteExpiration, NoSlidingExpiration,
                global::System.Web.Caching.CacheItemPriority.Default, null, null, false);
        }

        public void Insert(global::System.String key, global::System.Object value, global::System.Web.Caching.CacheDependency dependencies)
        {
            DoInsert(key, value, dependencies, NoAbsoluteExpiration, NoSlidingExpiration,
                global::System.Web.Caching.CacheItemPriority.Default, null, null, false);
        }

        public void Insert(global::System.String key, global::System.Object value, global::System.Web.Caching.CacheDependency dependencies, global::System.DateTime absoluteExpiration, global::System.TimeSpan slidingExpiration)
        {
            DoInsert(key, value, dependencies, absoluteExpiration, slidingExpiration,
                global::System.Web.Caching.CacheItemPriority.Default, null, null, false);
        }

        public void Insert(global::System.String key, global::System.Object value, global::System.Web.Caching.CacheDependency dependencies, global::System.DateTime absoluteExpiration, global::System.TimeSpan slidingExpiration, global::System.Web.Caching.CacheItemPriority priority, global::System.Web.Caching.CacheItemRemovedCallback onRemoveCallback)
        {
            DoInsert(key, value, dependencies, absoluteExpiration, slidingExpiration,
                priority, onRemoveCallback, null, false);
        }

        public void Insert(global::System.String key, global::System.Object value, global::System.Web.Caching.CacheDependency dependencies, global::System.DateTime absoluteExpiration, global::System.TimeSpan slidingExpiration, global::System.Web.Caching.CacheItemUpdateCallback onUpdateCallback)
        {
            if (onUpdateCallback == null) throw new global::System.ArgumentNullException("onUpdateCallback");
            DoInsert(key, value, dependencies, absoluteExpiration, slidingExpiration,
                global::System.Web.Caching.CacheItemPriority.Default, null, onUpdateCallback, false);
        }

        // ---------- add (only succeeds if key absent) ----------
        public global::System.Object Add(global::System.String key, global::System.Object value, global::System.Web.Caching.CacheDependency dependencies, global::System.DateTime absoluteExpiration, global::System.TimeSpan slidingExpiration, global::System.Web.Caching.CacheItemPriority priority, global::System.Web.Caching.CacheItemRemovedCallback onRemoveCallback)
        {
            // Add returns the existing live item if present (and does NOT overwrite), else null.
            CacheEntry existing;
            if (_store.TryGetValue(key, out existing))
            {
                global::System.DateTime utcNow = global::System.DateTime.UtcNow;
                if (!IsExpired(existing, utcNow) && !(existing.Dependency != null && existing.Dependency.HasChanged))
                {
                    return existing.Value;
                }
            }
            DoInsert(key, value, dependencies, absoluteExpiration, slidingExpiration,
                priority, onRemoveCallback, null, true);
            CacheEntry now;
            if (_store.TryGetValue(key, out now) && !object.ReferenceEquals(now.Value, value))
            {
                return now.Value;
            }
            return null;
        }

        private void DoInsert(global::System.String key, global::System.Object value,
            global::System.Web.Caching.CacheDependency dependencies,
            global::System.DateTime absoluteExpiration, global::System.TimeSpan slidingExpiration,
            global::System.Web.Caching.CacheItemPriority priority,
            global::System.Web.Caching.CacheItemRemovedCallback onRemoveCallback,
            global::System.Web.Caching.CacheItemUpdateCallback onUpdateCallback,
            global::System.Boolean addOnlyIfAbsent)
        {
            if (key == null) throw new global::System.ArgumentNullException("key");
            if (value == null) throw new global::System.ArgumentNullException("value");

            // Validate expiration combination, mirroring the original API contract:
            // sliding and absolute may not both be set, and sliding must be within range.
            bool hasSliding = slidingExpiration != NoSlidingExpiration;
            bool hasAbsolute = absoluteExpiration != NoAbsoluteExpiration;
            if (hasSliding)
            {
                if (slidingExpiration < global::System.TimeSpan.Zero || slidingExpiration > s_maxSliding)
                {
                    throw new global::System.ArgumentOutOfRangeException("slidingExpiration");
                }
                if (hasAbsolute)
                {
                    throw new global::System.ArgumentException("absoluteExpiration must be NoAbsoluteExpiration when slidingExpiration is used.");
                }
            }
            if (onUpdateCallback != null && onRemoveCallback != null)
            {
                throw new global::System.ArgumentException("Cannot set both onRemoveCallback and onUpdateCallback.");
            }

            global::System.DateTime utcNow = global::System.DateTime.UtcNow;
            global::System.DateTime utcAbsolute;
            if (hasSliding)
            {
                utcAbsolute = utcNow.Add(slidingExpiration);
            }
            else if (hasAbsolute)
            {
                utcAbsolute = absoluteExpiration.ToUniversalTime();
            }
            else
            {
                utcAbsolute = NoAbsoluteExpiration; // DateTime.MaxValue sentinel
            }

            var entry = new CacheEntry
            {
                Key = key,
                Value = value,
                Dependency = dependencies,
                UtcAbsoluteExpiration = utcAbsolute,
                SlidingExpiration = slidingExpiration,
                UtcLastAccess = utcNow,
                Priority = priority,
                OnRemovedCallback = onRemoveCallback,
                OnUpdateCallback = onUpdateCallback,
                RemovedFlag = 0,
            };

            if (dependencies != null)
            {
                // Finalize the dependency and snapshot its current state.
                dependencies.FinishInit();
                if (dependencies.HasChanged)
                {
                    // Already changed before insert: do not cache; fire callback as DependencyChanged.
                    InvokeRemovedCallback(entry, global::System.Web.Caching.CacheItemRemovedReason.DependencyChanged);
                    DisposeDependency(dependencies);
                    return;
                }
                // Wire change notification to evict this item.
                dependencies.SetCacheDependencyChanged((sender, args) =>
                {
                    CacheEntry cur;
                    if (_store.TryGetValue(key, out cur) && object.ReferenceEquals(cur, entry))
                    {
                        RemoveEntry(key, cur, global::System.Web.Caching.CacheItemRemovedReason.DependencyChanged);
                    }
                });
            }

            if (addOnlyIfAbsent)
            {
                if (!_store.TryAdd(key, entry))
                {
                    // Key present (live or stale). Leave existing entry alone.
                    if (dependencies != null) DisposeDependency(dependencies);
                    return;
                }
            }
            else
            {
                CacheEntry old;
                if (_store.TryGetValue(key, out old))
                {
                    _store[key] = entry;
                    // Existing item is being overwritten: original semantics fire Removed.
                    InvokeRemovedCallback(old, global::System.Web.Caching.CacheItemRemovedReason.Removed);
                    DisposeDependency(old.Dependency);
                }
                else
                {
                    _store[key] = entry;
                }
            }
        }

        // ---------- remove ----------
        public global::System.Object Remove(global::System.String key)
        {
            if (key == null) throw new global::System.ArgumentNullException("key");
            CacheEntry e;
            if (!_store.TryGetValue(key, out e))
            {
                return null;
            }
            global::System.Object val = e.Value;
            RemoveEntry(key, e, global::System.Web.Caching.CacheItemRemovedReason.Removed);
            return val;
        }

        private void RemoveEntry(global::System.String key, CacheEntry entry, global::System.Web.Caching.CacheItemRemovedReason reason)
        {
            // Remove only if this exact entry is still mapped (avoid races with re-insert).
            var pair = new global::System.Collections.Generic.KeyValuePair<global::System.String, CacheEntry>(key, entry);
            var collection = (global::System.Collections.Generic.ICollection<global::System.Collections.Generic.KeyValuePair<global::System.String, CacheEntry>>)_store;
            bool removed = collection.Remove(pair);
            if (!removed)
            {
                // Already gone or replaced by another instance; still fire the targeted entry's
                // callback once for correctness.
                InvokeUpdateOrRemoved(entry, reason);
                return;
            }
            InvokeUpdateOrRemoved(entry, reason);
        }

        private void InvokeUpdateOrRemoved(CacheEntry entry, global::System.Web.Caching.CacheItemRemovedReason reason)
        {
            if (global::System.Threading.Interlocked.Exchange(ref entry.RemovedFlag, 1) != 0)
            {
                return; // already handled
            }

            // CacheItemUpdateCallback gets a chance to refresh the item before final removal,
            // for Expired and DependencyChanged reasons only.
            if (entry.OnUpdateCallback != null &&
                (reason == global::System.Web.Caching.CacheItemRemovedReason.Expired ||
                 reason == global::System.Web.Caching.CacheItemRemovedReason.DependencyChanged))
            {
                global::System.Web.Caching.CacheItemUpdateReason updReason =
                    reason == global::System.Web.Caching.CacheItemRemovedReason.Expired
                        ? global::System.Web.Caching.CacheItemUpdateReason.Expired
                        : global::System.Web.Caching.CacheItemUpdateReason.DependencyChanged;
                global::System.Object newValue = null;
                global::System.Web.Caching.CacheDependency newDep = null;
                global::System.DateTime newAbs = NoAbsoluteExpiration;
                global::System.TimeSpan newSliding = NoSlidingExpiration;
                try
                {
                    entry.OnUpdateCallback(entry.Key, updReason, out newValue, out newDep, out newAbs, out newSliding);
                }
                catch
                {
                    newValue = null;
                }
                if (newValue != null)
                {
                    // Re-insert the refreshed value, preserving the update callback.
                    DoInsert(entry.Key, newValue, newDep, newAbs, newSliding,
                        global::System.Web.Caching.CacheItemPriority.Default, null, entry.OnUpdateCallback, false);
                }
                else
                {
                    DisposeDependency(entry.Dependency);
                }
                return;
            }

            InvokeRemovedCallbackCore(entry, reason);
            DisposeDependency(entry.Dependency);
        }

        private void InvokeRemovedCallback(CacheEntry entry, global::System.Web.Caching.CacheItemRemovedReason reason)
        {
            if (global::System.Threading.Interlocked.Exchange(ref entry.RemovedFlag, 1) != 0)
            {
                return;
            }
            InvokeRemovedCallbackCore(entry, reason);
        }

        private void InvokeRemovedCallbackCore(CacheEntry entry, global::System.Web.Caching.CacheItemRemovedReason reason)
        {
            if (entry.OnRemovedCallback != null)
            {
                try
                {
                    entry.OnRemovedCallback(entry.Key, entry.Value, reason);
                }
                catch
                {
                    // Callbacks must not break cache integrity.
                }
            }
        }

        private static void DisposeDependency(global::System.Web.Caching.CacheDependency dep)
        {
            if (dep != null)
            {
                try { dep.Dispose(); } catch { }
            }
        }

        // ---------- count / indexer ----------
        public global::System.Int32 Count
        {
            get
            {
                // Count of live items (expired/changed are pruned lazily).
                int n = 0;
                global::System.DateTime utcNow = global::System.DateTime.UtcNow;
                foreach (var kvp in _store)
                {
                    CacheEntry e = kvp.Value;
                    if (IsExpired(e, utcNow) || (e.Dependency != null && e.Dependency.HasChanged))
                    {
                        continue;
                    }
                    n++;
                }
                return n;
            }
        }

        public global::System.Object this[global::System.String key]
        {
            get { return Get(key); }
            set { Insert(key, value); }
        }

        // EffectivePrivateBytesLimit / physical-memory limits: in-process memory governance is not
        // modeled in this clean-room cache. Report best-effort values; 0 means "no explicit limit".
        public global::System.Int64 EffectivePrivateBytesLimit
        {
            get
            {
                try
                {
                    var info = global::System.GC.GetGCMemoryInfo();
                    if (info.TotalAvailableMemoryBytes > 0)
                    {
                        return info.TotalAvailableMemoryBytes;
                    }
                }
                catch { }
                return 0L;
            }
        }

        public global::System.Int64 EffectivePercentagePhysicalMemoryLimit
        {
            get
            {
                // No physical-memory pressure governor implemented.
                return 0L;
            }
        }

        // ---------- expiration helpers ----------
        private static global::System.Boolean IsExpired(CacheEntry e, global::System.DateTime utcNow)
        {
            if (e.UtcAbsoluteExpiration == NoAbsoluteExpiration)
            {
                return false;
            }
            return utcNow >= e.UtcAbsoluteExpiration;
        }

        private void SweepCallback(global::System.Object state)
        {
            global::System.DateTime utcNow = global::System.DateTime.UtcNow;
            // Iterating a ConcurrentDictionary while removing is safe.
            foreach (var kvp in _store)
            {
                CacheEntry e = kvp.Value;
                if (e.Dependency != null && e.Dependency.HasChanged)
                {
                    RemoveEntry(kvp.Key, e, global::System.Web.Caching.CacheItemRemovedReason.DependencyChanged);
                }
                else if (IsExpired(e, utcNow))
                {
                    RemoveEntry(kvp.Key, e, global::System.Web.Caching.CacheItemRemovedReason.Expired);
                }
            }
        }
    }

    public class CacheDependency : global::System.IDisposable
    {
        // ----- file watch state -----
        private sealed class FileWatch
        {
            public global::System.String Path;
            public global::System.DateTime LastWriteUtc; // baseline; DateTime.MinValue if missing
            public global::System.Boolean Existed;
        }

        private global::System.Collections.Generic.List<FileWatch> _files;
        private global::System.String[] _cacheKeys;
        private global::System.Web.Caching.CacheDependency[] _childDependencies;
        private global::System.DateTime _start;                 // UTC; only changes after this time count
        private global::System.DateTime _utcLastModified;
        private global::System.Int32 _changed;                  // 0 = not changed, 1 = changed
        private global::System.Boolean _disposed;
        private global::System.Boolean _initialized;
        private global::System.Int32 _ownership;                // TakeOwnership latch
        private global::System.Action<global::System.Object, global::System.EventArgs> _onChangedAction;
        private global::System.String _uniqueId;
        private readonly global::System.Object _sync = new global::System.Object();
        private global::System.Collections.Generic.List<global::System.IO.FileSystemWatcher> _watchers;

        protected CacheDependency()
        {
            _start = global::System.DateTime.MinValue;
            _utcLastModified = global::System.DateTime.UtcNow;
        }

        public CacheDependency(global::System.String filename)
            : this(filename == null ? null : new[] { filename }, (global::System.String[])null, (global::System.Web.Caching.CacheDependency)null, global::System.DateTime.MaxValue) { }

        public CacheDependency(global::System.String filename, global::System.DateTime start)
            : this(filename == null ? null : new[] { filename }, (global::System.String[])null, (global::System.Web.Caching.CacheDependency)null, start) { }

        public CacheDependency(global::System.String[] filenames)
            : this(filenames, (global::System.String[])null, (global::System.Web.Caching.CacheDependency)null, global::System.DateTime.MaxValue) { }

        public CacheDependency(global::System.String[] filenames, global::System.DateTime start)
            : this(filenames, (global::System.String[])null, (global::System.Web.Caching.CacheDependency)null, start) { }

        public CacheDependency(global::System.String[] filenames, global::System.String[] cachekeys)
            : this(filenames, cachekeys, (global::System.Web.Caching.CacheDependency)null, global::System.DateTime.MaxValue) { }

        public CacheDependency(global::System.String[] filenames, global::System.String[] cachekeys, global::System.DateTime start)
            : this(filenames, cachekeys, (global::System.Web.Caching.CacheDependency)null, start) { }

        public CacheDependency(global::System.String[] filenames, global::System.String[] cachekeys, global::System.Web.Caching.CacheDependency dependency)
            : this(filenames, cachekeys, dependency, global::System.DateTime.MaxValue) { }

        public CacheDependency(global::System.String[] filenames, global::System.String[] cachekeys, global::System.Web.Caching.CacheDependency dependency, global::System.DateTime start)
        {
            // start == DateTime.MaxValue is our internal "use now" marker (no explicit start).
            if (start == global::System.DateTime.MaxValue)
            {
                _start = global::System.DateTime.UtcNow;
            }
            else
            {
                _start = start.ToUniversalTime();
            }

            _files = new global::System.Collections.Generic.List<FileWatch>();
            if (filenames != null)
            {
                for (int i = 0; i < filenames.Length; i++)
                {
                    global::System.String f = filenames[i];
                    if (f == null) throw new global::System.ArgumentNullException("filenames");
                    var fw = new FileWatch { Path = f };
                    CaptureFileState(fw);
                    _files.Add(fw);
                }
            }

            _cacheKeys = cachekeys;

            if (dependency != null)
            {
                _childDependencies = new[] { dependency };
            }

            _utcLastModified = ComputeInitialLastModified();

            // Chain change propagation from a child dependency.
            if (_childDependencies != null)
            {
                for (int i = 0; i < _childDependencies.Length; i++)
                {
                    var child = _childDependencies[i];
                    if (child != null)
                    {
                        if (child.HasChanged)
                        {
                            MarkChanged();
                        }
                        child.SetCacheDependencyChanged((s, e) => NotifyDependencyChanged(this, global::System.EventArgs.Empty));
                    }
                }
            }

            SetUpFileWatchers();

            // For non-derived instances, init is complete immediately.
            if (this.GetType() == typeof(global::System.Web.Caching.CacheDependency))
            {
                FinishInit();
            }
        }

        private void CaptureFileState(FileWatch fw)
        {
            try
            {
                if (global::System.IO.File.Exists(fw.Path))
                {
                    fw.Existed = true;
                    fw.LastWriteUtc = global::System.IO.File.GetLastWriteTimeUtc(fw.Path);
                }
                else if (global::System.IO.Directory.Exists(fw.Path))
                {
                    fw.Existed = true;
                    fw.LastWriteUtc = global::System.IO.Directory.GetLastWriteTimeUtc(fw.Path);
                }
                else
                {
                    fw.Existed = false;
                    fw.LastWriteUtc = global::System.DateTime.MinValue;
                }
            }
            catch
            {
                fw.Existed = false;
                fw.LastWriteUtc = global::System.DateTime.MinValue;
            }
        }

        private global::System.DateTime ComputeInitialLastModified()
        {
            global::System.DateTime max = _start;
            if (_files != null)
            {
                for (int i = 0; i < _files.Count; i++)
                {
                    if (_files[i].Existed && _files[i].LastWriteUtc > max)
                    {
                        max = _files[i].LastWriteUtc;
                    }
                }
            }
            return max;
        }

        private void SetUpFileWatchers()
        {
            if (_files == null || _files.Count == 0) return;
            _watchers = new global::System.Collections.Generic.List<global::System.IO.FileSystemWatcher>();
            for (int i = 0; i < _files.Count; i++)
            {
                FileWatch fw = _files[i];
                try
                {
                    global::System.String dir = global::System.IO.Path.GetDirectoryName(fw.Path);
                    global::System.String name = global::System.IO.Path.GetFileName(fw.Path);
                    if (string.IsNullOrEmpty(dir) || string.IsNullOrEmpty(name) || !global::System.IO.Directory.Exists(dir))
                    {
                        continue; // fall back to poll-on-access via CheckFiles()
                    }
                    var w = new global::System.IO.FileSystemWatcher(dir, name);
                    w.NotifyFilter = global::System.IO.NotifyFilters.LastWrite
                        | global::System.IO.NotifyFilters.FileName
                        | global::System.IO.NotifyFilters.CreationTime
                        | global::System.IO.NotifyFilters.Size;
                    global::System.IO.FileSystemEventHandler handler = (s, e) => OnFileChanged();
                    w.Changed += handler;
                    w.Created += handler;
                    w.Deleted += handler;
                    w.Renamed += (s, e) => OnFileChanged();
                    w.EnableRaisingEvents = true;
                    _watchers.Add(w);
                }
                catch
                {
                    // If a watcher cannot be created, rely on polling in CheckFiles().
                }
            }
        }

        private void OnFileChanged()
        {
            // The watcher fires on any modification; re-validate against baseline + start.
            if (CheckFiles())
            {
                NotifyDependencyChanged(this, global::System.EventArgs.Empty);
            }
        }

        // Polls files; returns true if a relevant change (after _start) is detected.
        private global::System.Boolean CheckFiles()
        {
            if (_files == null) return false;
            for (int i = 0; i < _files.Count; i++)
            {
                FileWatch fw = _files[i];
                bool existsNow;
                global::System.DateTime writeNow = global::System.DateTime.MinValue;
                try
                {
                    if (global::System.IO.File.Exists(fw.Path))
                    {
                        existsNow = true;
                        writeNow = global::System.IO.File.GetLastWriteTimeUtc(fw.Path);
                    }
                    else if (global::System.IO.Directory.Exists(fw.Path))
                    {
                        existsNow = true;
                        writeNow = global::System.IO.Directory.GetLastWriteTimeUtc(fw.Path);
                    }
                    else
                    {
                        existsNow = false;
                    }
                }
                catch
                {
                    existsNow = false;
                }

                if (existsNow != fw.Existed)
                {
                    return true; // created or deleted
                }
                if (existsNow && writeNow != fw.LastWriteUtc && writeNow >= _start)
                {
                    return true;
                }
            }
            return false;
        }

        private void MarkChanged()
        {
            if (global::System.Threading.Interlocked.Exchange(ref _changed, 1) == 0)
            {
                _utcLastModified = global::System.DateTime.UtcNow;
            }
        }

        public void Dispose()
        {
            if (_disposed) return;
            _disposed = true;
            DependencyDispose();
        }

        protected internal void FinishInit()
        {
            _initialized = true;
        }

        protected virtual void DependencyDispose()
        {
            lock (_sync)
            {
                if (_watchers != null)
                {
                    for (int i = 0; i < _watchers.Count; i++)
                    {
                        try { _watchers[i].EnableRaisingEvents = false; _watchers[i].Dispose(); } catch { }
                    }
                    _watchers = null;
                }
            }
            _onChangedAction = null;
        }

        public global::System.Boolean TakeOwnership()
        {
            // Returns true exactly once (the first caller becomes the owner).
            return global::System.Threading.Interlocked.Exchange(ref _ownership, 1) == 0;
        }

        protected void SetUtcLastModified(global::System.DateTime utcLastModified)
        {
            _utcLastModified = utcLastModified;
        }

        public void KeepDependenciesAlive()
        {
            // The original keeps GC references to dependent objects; our model already holds strong
            // references via fields, so this just touches them.
            global::System.GC.KeepAlive(_childDependencies);
            global::System.GC.KeepAlive(_watchers);
        }

        public void SetCacheDependencyChanged(global::System.Action<global::System.Object, global::System.EventArgs> dependencyChangedAction)
        {
            _onChangedAction = dependencyChangedAction;
            // If already changed, fire immediately so a late subscriber still evicts.
            if (global::System.Threading.Volatile.Read(ref _changed) == 1 && dependencyChangedAction != null)
            {
                try { dependencyChangedAction(this, global::System.EventArgs.Empty); } catch { }
            }
        }

        public virtual global::System.String GetUniqueID()
        {
            if (_uniqueId != null) return _uniqueId;
            var sb = new global::System.Text.StringBuilder();
            if (_files != null)
            {
                for (int i = 0; i < _files.Count; i++)
                {
                    sb.Append("f:").Append(_files[i].Path).Append(';');
                }
            }
            if (_cacheKeys != null)
            {
                for (int i = 0; i < _cacheKeys.Length; i++)
                {
                    sb.Append("k:").Append(_cacheKeys[i]).Append(';');
                }
            }
            if (_childDependencies != null)
            {
                for (int i = 0; i < _childDependencies.Length; i++)
                {
                    if (_childDependencies[i] != null)
                    {
                        global::System.String inner = _childDependencies[i].GetUniqueID();
                        if (inner != null) sb.Append("d:").Append(inner).Append(';');
                    }
                }
            }
            _uniqueId = sb.Length == 0 ? null : sb.ToString();
            return _uniqueId;
        }

        protected void NotifyDependencyChanged(global::System.Object sender, global::System.EventArgs e)
        {
            MarkChanged();
            var action = _onChangedAction;
            if (action != null)
            {
                try { action(this, global::System.EventArgs.Empty); } catch { }
            }
        }

        public void ItemRemoved()
        {
            // Called by the cache when the dependent item is removed; release watchers.
            Dispose();
        }

        public virtual global::System.String[] GetFileDependencies()
        {
            var list = new global::System.Collections.Generic.List<global::System.String>();
            if (_files != null)
            {
                for (int i = 0; i < _files.Count; i++)
                {
                    list.Add(_files[i].Path);
                }
            }
            if (_childDependencies != null)
            {
                for (int i = 0; i < _childDependencies.Length; i++)
                {
                    if (_childDependencies[i] != null)
                    {
                        global::System.String[] inner = _childDependencies[i].GetFileDependencies();
                        if (inner != null)
                        {
                            for (int j = 0; j < inner.Length; j++) list.Add(inner[j]);
                        }
                    }
                }
            }
            if (list.Count == 0) return null;
            return list.ToArray();
        }

        public global::System.Boolean HasChanged
        {
            get
            {
                if (global::System.Threading.Volatile.Read(ref _changed) == 1)
                {
                    return true;
                }
                // Lazy poll for environments where FileSystemWatcher missed/cannot run.
                if (CheckFiles())
                {
                    MarkChanged();
                    return true;
                }
                if (_childDependencies != null)
                {
                    for (int i = 0; i < _childDependencies.Length; i++)
                    {
                        if (_childDependencies[i] != null && _childDependencies[i].HasChanged)
                        {
                            MarkChanged();
                            return true;
                        }
                    }
                }
                return false;
            }
        }

        public global::System.DateTime UtcLastModified
        {
            get { return _utcLastModified; }
        }
    }

    public sealed class AggregateCacheDependency : global::System.Web.Caching.CacheDependency
    {
        private readonly global::System.Collections.Generic.List<global::System.Web.Caching.CacheDependency> _dependencies =
            new global::System.Collections.Generic.List<global::System.Web.Caching.CacheDependency>();
        private readonly global::System.Object _aggSync = new global::System.Object();

        public AggregateCacheDependency()
        {
            FinishInit();
        }

        public void Add(params global::System.Web.Caching.CacheDependency[] dependencies)
        {
            if (dependencies == null) throw new global::System.ArgumentNullException("dependencies");
            for (int i = 0; i < dependencies.Length; i++)
            {
                if (dependencies[i] == null) throw new global::System.ArgumentNullException("dependencies");
            }

            bool anyChanged = false;
            lock (_aggSync)
            {
                for (int i = 0; i < dependencies.Length; i++)
                {
                    var dep = dependencies[i];
                    _dependencies.Add(dep);
                    if (dep.HasChanged)
                    {
                        anyChanged = true;
                    }
                    else
                    {
                        dep.SetCacheDependencyChanged((s, e) => NotifyDependencyChanged(this, global::System.EventArgs.Empty));
                    }
                }
            }
            if (anyChanged)
            {
                NotifyDependencyChanged(this, global::System.EventArgs.Empty);
            }
        }

        protected override void DependencyDispose()
        {
            lock (_aggSync)
            {
                for (int i = 0; i < _dependencies.Count; i++)
                {
                    try { _dependencies[i].Dispose(); } catch { }
                }
                _dependencies.Clear();
            }
            base.DependencyDispose();
        }

        public override global::System.String GetUniqueID()
        {
            var sb = new global::System.Text.StringBuilder();
            lock (_aggSync)
            {
                for (int i = 0; i < _dependencies.Count; i++)
                {
                    global::System.String id = _dependencies[i].GetUniqueID();
                    if (id == null)
                    {
                        // A child without a stable id makes the aggregate id indeterminate.
                        return null;
                    }
                    sb.Append(id).Append(';');
                }
            }
            return sb.Length == 0 ? null : sb.ToString();
        }

        public override global::System.String[] GetFileDependencies()
        {
            var list = new global::System.Collections.Generic.List<global::System.String>();
            lock (_aggSync)
            {
                for (int i = 0; i < _dependencies.Count; i++)
                {
                    global::System.String[] inner = _dependencies[i].GetFileDependencies();
                    if (inner != null)
                    {
                        for (int j = 0; j < inner.Length; j++) list.Add(inner[j]);
                    }
                }
            }
            if (list.Count == 0) return null;
            return list.ToArray();
        }
    }

    public class FileResponseElement : global::System.Web.Caching.ResponseElement
    {
        private readonly global::System.String _path;
        private readonly global::System.Int64 _offset;
        private readonly global::System.Int64 _length;

        public FileResponseElement(global::System.String path, global::System.Int64 offset, global::System.Int64 length)
        {
            if (path == null) throw new global::System.ArgumentNullException("path");
            if (offset < 0) throw new global::System.ArgumentOutOfRangeException("offset");
            if (length < 0) throw new global::System.ArgumentOutOfRangeException("length");
            _path = path;
            _offset = offset;
            _length = length;
        }
        public global::System.String Path { get { return _path; } }
        public global::System.Int64 Offset { get { return _offset; } }
        public global::System.Int64 Length { get { return _length; } }
    }

    public sealed class HeaderElement
    {
        private readonly global::System.String _name;
        private readonly global::System.String _value;
        public HeaderElement(global::System.String name, global::System.String value)
        {
            _name = name;
            _value = value;
        }
        public global::System.String Name { get { return _name; } }
        public global::System.String Value { get { return _value; } }
    }

    public interface IOutputCacheEntry
    {
        global::System.Collections.Generic.List<global::System.Web.Caching.HeaderElement> HeaderElements { get; set; }
        global::System.Collections.Generic.List<global::System.Web.Caching.ResponseElement> ResponseElements { get; set; }
    }

    public class MemoryResponseElement : global::System.Web.Caching.ResponseElement
    {
        private readonly global::System.Byte[] _buffer;
        private readonly global::System.Int64 _length;
        public MemoryResponseElement(global::System.Byte[] buffer, global::System.Int64 length)
        {
            if (buffer == null) throw new global::System.ArgumentNullException("buffer");
            if (length < 0) throw new global::System.ArgumentOutOfRangeException("length");
            _buffer = buffer;
            _length = length;
        }
        public global::System.Byte[] Buffer { get { return _buffer; } }
        public global::System.Int64 Length { get { return _length; } }
    }

    public static class OutputCache
    {
        // TODO: output-cache provider serialization, later tier (depends on HttpResponse pipeline).
        public static void Serialize(global::System.IO.Stream stream, global::System.Object data) { throw new global::System.NotImplementedException("TODO: output-cache provider, later tier"); }
        public static global::System.Object Deserialize(global::System.IO.Stream stream) { throw new global::System.NotImplementedException("TODO: output-cache provider, later tier"); }
        public static global::System.String DefaultProviderName { get { throw new global::System.NotImplementedException("TODO: output-cache provider, later tier"); } }
        public static global::System.Web.Caching.OutputCacheProviderCollection Providers { get { throw new global::System.NotImplementedException("TODO: output-cache provider, later tier"); } }
    }

    public abstract class OutputCacheProvider : global::System.Configuration.Provider.ProviderBase
    {
        protected OutputCacheProvider() { }
        public abstract global::System.Object Get(global::System.String key);
        public abstract global::System.Object Add(global::System.String key, global::System.Object entry, global::System.DateTime utcExpiry);
        public abstract void Set(global::System.String key, global::System.Object entry, global::System.DateTime utcExpiry);
        public abstract void Remove(global::System.String key);
    }

    public abstract class OutputCacheProviderAsync : global::System.Web.Caching.OutputCacheProvider
    {
        protected OutputCacheProviderAsync() { }
        public abstract global::System.Threading.Tasks.Task<global::System.Object> GetAsync(global::System.String key);
        public abstract global::System.Threading.Tasks.Task<global::System.Object> AddAsync(global::System.String key, global::System.Object entry, global::System.DateTime utcExpiry);
        public abstract global::System.Threading.Tasks.Task SetAsync(global::System.String key, global::System.Object entry, global::System.DateTime utcExpiry);
        public abstract global::System.Threading.Tasks.Task RemoveAsync(global::System.String key);
    }

    public sealed class OutputCacheProviderCollection : global::System.Configuration.Provider.ProviderCollection
    {
        public OutputCacheProviderCollection() { }
        public override void Add(global::System.Configuration.Provider.ProviderBase provider)
        {
            if (provider == null) throw new global::System.ArgumentNullException("provider");
            if (!(provider is global::System.Web.Caching.OutputCacheProvider))
            {
                throw new global::System.ArgumentException("provider must be an OutputCacheProvider.", "provider");
            }
            base.Add(provider);
        }
        public void CopyTo(global::System.Web.Caching.OutputCacheProvider[] array, global::System.Int32 index)
        {
            base.CopyTo(array, index);
        }
        public global::System.Web.Caching.OutputCacheProvider this[global::System.String name]
        {
            get { return (global::System.Web.Caching.OutputCacheProvider)base[name]; }
        }
    }

    public static class OutputCacheUtility
    {
        // TODO: output-cache kernel/HttpResponse integration, later tier.
        public static global::System.String SetupKernelCaching(global::System.String originalCacheUrl, global::System.Web.HttpResponse response) { throw new global::System.NotImplementedException("TODO: output-cache provider, later tier"); }
        public static void FlushKernelCache(global::System.String cacheKey) { throw new global::System.NotImplementedException("TODO: output-cache provider, later tier"); }
        public static global::System.Web.Caching.CacheDependency CreateCacheDependency(global::System.Web.HttpResponse response) { throw new global::System.NotImplementedException("TODO: output-cache provider, later tier"); }
        public static global::System.Collections.ArrayList GetContentBuffers(global::System.Web.HttpResponse response) { throw new global::System.NotImplementedException("TODO: output-cache provider, later tier"); }
        public static void SetContentBuffers(global::System.Web.HttpResponse response, global::System.Collections.ArrayList buffers) { throw new global::System.NotImplementedException("TODO: output-cache provider, later tier"); }
        public static global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<global::System.Web.HttpCacheValidateHandler, global::System.Object>> GetValidationCallbacks(global::System.Web.HttpResponse response) { throw new global::System.NotImplementedException("TODO: output-cache provider, later tier"); }
    }

    public abstract class ResponseElement
    {
        protected ResponseElement() { }
    }

    public sealed class SqlCacheDependency : global::System.Web.Caching.CacheDependency
    {
        // TODO: SQL/output-cache provider, later tier (SQL notification / polling infrastructure).
        public SqlCacheDependency(global::System.String databaseEntryName, global::System.String tableName) { throw new global::System.NotImplementedException("TODO: SQL/output-cache provider, later tier"); }
        public SqlCacheDependency(global::System.Data.SqlClient.SqlCommand sqlCmd) { throw new global::System.NotImplementedException("TODO: SQL/output-cache provider, later tier"); }
        protected override void DependencyDispose() { throw new global::System.NotImplementedException("TODO: SQL/output-cache provider, later tier"); }
        public override global::System.String GetUniqueID() { throw new global::System.NotImplementedException("TODO: SQL/output-cache provider, later tier"); }
        public static global::System.Web.Caching.CacheDependency CreateOutputCacheDependency(global::System.String dependency) { throw new global::System.NotImplementedException("TODO: SQL/output-cache provider, later tier"); }
    }

    public sealed class DatabaseNotEnabledForNotificationException : global::System.SystemException
    {
        public DatabaseNotEnabledForNotificationException() : base() { }
        public DatabaseNotEnabledForNotificationException(global::System.String message) : base(message) { }
        public DatabaseNotEnabledForNotificationException(global::System.String message, global::System.Exception innerException) : base(message, innerException) { }
    }

    public sealed class TableNotEnabledForNotificationException : global::System.SystemException
    {
        public TableNotEnabledForNotificationException() : base() { }
        public TableNotEnabledForNotificationException(global::System.String message) : base(message) { }
        public TableNotEnabledForNotificationException(global::System.String message, global::System.Exception innerException) : base(message, innerException) { }
    }

    public static class SqlCacheDependencyAdmin
    {
        // TODO: SQL/output-cache provider, later tier (SQL Server notification administration).
        public static void EnableNotifications(global::System.String connectionString) { throw new global::System.NotImplementedException("TODO: SQL/output-cache provider, later tier"); }
        public static void DisableNotifications(global::System.String connectionString) { throw new global::System.NotImplementedException("TODO: SQL/output-cache provider, later tier"); }
        public static void EnableTableForNotifications(global::System.String connectionString, global::System.String table) { throw new global::System.NotImplementedException("TODO: SQL/output-cache provider, later tier"); }
        public static void EnableTableForNotifications(global::System.String connectionString, global::System.String[] tables) { throw new global::System.NotImplementedException("TODO: SQL/output-cache provider, later tier"); }
        public static void DisableTableForNotifications(global::System.String connectionString, global::System.String table) { throw new global::System.NotImplementedException("TODO: SQL/output-cache provider, later tier"); }
        public static void DisableTableForNotifications(global::System.String connectionString, global::System.String[] tables) { throw new global::System.NotImplementedException("TODO: SQL/output-cache provider, later tier"); }
        public static global::System.String[] GetTablesEnabledForNotifications(global::System.String connectionString) { throw new global::System.NotImplementedException("TODO: SQL/output-cache provider, later tier"); }
    }

    public class SubstitutionResponseElement : global::System.Web.Caching.ResponseElement
    {
        private readonly global::System.Web.HttpResponseSubstitutionCallback _callback;
        public SubstitutionResponseElement(global::System.Web.HttpResponseSubstitutionCallback callback)
        {
            if (callback == null) throw new global::System.ArgumentNullException("callback");
            _callback = callback;
        }
        public global::System.Web.HttpResponseSubstitutionCallback Callback { get { return _callback; } }
    }
}
