// <auto-generated> clean-room System.Web API skeleton.
// Bodies are NotImplementedException; this proves signature completeness only.
#nullable disable
#pragma warning disable

namespace System.Web.Handlers
{
    public sealed class AssemblyResourceLoader : global::System.Web.IHttpHandler
    {
        public AssemblyResourceLoader() { throw new global::System.NotImplementedException(); }
        void global::System.Web.IHttpHandler.ProcessRequest(global::System.Web.HttpContext context) { throw new global::System.NotImplementedException(); }
        global::System.Boolean global::System.Web.IHttpHandler.IsReusable { get { throw new global::System.NotImplementedException(); } }
    }
    public class TraceHandler : global::System.Web.IHttpHandler
    {
        public TraceHandler() { throw new global::System.NotImplementedException(); }
        protected void ProcessRequest(global::System.Web.HttpContext context) { throw new global::System.NotImplementedException(); }
        void global::System.Web.IHttpHandler.ProcessRequest(global::System.Web.HttpContext context) { throw new global::System.NotImplementedException(); }
        protected void ShowDetails(global::System.Data.DataSet data) { throw new global::System.NotImplementedException(); }
        protected void ShowVersionDetails() { throw new global::System.NotImplementedException(); }
        protected void ShowRequests(global::System.Collections.IList data) { throw new global::System.NotImplementedException(); }
        protected global::System.Boolean IsReusable { get { throw new global::System.NotImplementedException(); } }
        global::System.Boolean global::System.Web.IHttpHandler.IsReusable { get { throw new global::System.NotImplementedException(); } }
    }
}
