// <auto-generated> clean-room System.Web API skeleton.
// Bodies are NotImplementedException; this proves signature completeness only.
#nullable disable
#pragma warning disable

namespace System.Web.Configuration.Internal
{
    public interface IInternalConfigWebHost
    {
        void GetSiteIDAndVPathFromConfigPath(global::System.String configPath, out global::System.String siteID, out global::System.String vpath);
        global::System.String GetConfigPathFromSiteIDAndVPath(global::System.String siteID, global::System.String vpath);
    }
}
