// <auto-generated>
// CLEAN-ROOM COMPATIBILITY SHIMS for the standalone net8.0 System.Web reimplementation.
//
// These types do NOT exist (or are not reachable) on net8.0 but are required by the
// frozen public signatures of the System.Web skeleton (src/*.cs). On .NET Framework 4.8
// they lived in SEPARATE assemblies that System.Web referenced:
//   - System.EnterpriseServices  -> System.EnterpriseServices.TransactionOption
//   - System.Web.Services        -> System.Web.Services.Configuration.WebServicesSection
//   - System.Web.ApplicationServices -> the System.Web.Security membership/role provider types
//
// They are reproduced here clean-room, from PUBLIC API shape only, with the MINIMAL
// surface needed to satisfy the frozen skeleton signatures (base classes whose members
// the skeleton overrides, referenced return/parameter types, etc). All bodies throw
// NotImplementedException, consistent with Tier 0. No runtime logic is implemented.
//
// DO NOT add behavior here. DO NOT widen the surface beyond what the build requires.
#nullable disable
#pragma warning disable

namespace System.EnterpriseServices
{
    // From System.EnterpriseServices. Used by System.Web.Util.Transactions.InvokeTransacted.
    public enum TransactionOption
    {
        Disabled = 0,
        NotSupported = 1,
        Supported = 2,
        Required = 3,
        RequiresNew = 4,
    }
}

namespace System.Web.Services.Configuration
{
    // From System.Web.Services. Returned by ScriptingWebServicesSectionGroup.WebServices.
    public sealed class WebServicesSection : global::System.Configuration.ConfigurationSection
    {
        public WebServicesSection() { }
    }
}

namespace System.Web.Security
{
    // ===== From System.Web.ApplicationServices =====
    // The membership/role provider model. Reproduced clean-room with the union of all
    // members the skeleton's concrete providers override, marked abstract/virtual.

    public enum MembershipCreateStatus
    {
        Success = 0,
        InvalidUserName = 1,
        InvalidPassword = 2,
        InvalidQuestion = 3,
        InvalidAnswer = 4,
        InvalidEmail = 5,
        DuplicateUserName = 6,
        DuplicateEmail = 7,
        UserRejected = 8,
        InvalidProviderUserKey = 9,
        DuplicateProviderUserKey = 10,
        ProviderError = 11,
    }

    public enum MembershipPasswordFormat
    {
        Clear = 0,
        Hashed = 1,
        Encrypted = 2,
    }

    public class MembershipUser
    {
        // Clean-room flesh-out: backing fields for the documented MembershipUser property set.
        private global::System.String _providerName;
        private global::System.String _userName;
        private global::System.Object _providerUserKey;
        private global::System.String _email;
        private global::System.String _passwordQuestion;
        private global::System.String _comment;
        private global::System.Boolean _isApproved;
        private global::System.Boolean _isLockedOut;
        private global::System.DateTime _creationDate;
        private global::System.DateTime _lastLoginDate;
        private global::System.DateTime _lastActivityDate;
        private global::System.DateTime _lastPasswordChangedDate;
        private global::System.DateTime _lastLockoutDate;

        public MembershipUser() { }
        public MembershipUser(global::System.String providerName, global::System.String name, global::System.Object providerUserKey, global::System.String email, global::System.String passwordQuestion, global::System.String comment, global::System.Boolean isApproved, global::System.Boolean isLockedOut, global::System.DateTime creationDate, global::System.DateTime lastLoginDate, global::System.DateTime lastActivityDate, global::System.DateTime lastPasswordChangedDate, global::System.DateTime lastLockoutDate)
        {
            _providerName = providerName;
            _userName = name;
            _providerUserKey = providerUserKey;
            _email = email;
            _passwordQuestion = passwordQuestion;
            _comment = comment;
            _isApproved = isApproved;
            _isLockedOut = isLockedOut;
            _creationDate = creationDate.ToUniversalTime();
            _lastLoginDate = lastLoginDate.ToUniversalTime();
            _lastActivityDate = lastActivityDate.ToUniversalTime();
            _lastPasswordChangedDate = lastPasswordChangedDate.ToUniversalTime();
            _lastLockoutDate = lastLockoutDate.ToUniversalTime();
        }

        public virtual global::System.String UserName { get { return _userName; } }
        public virtual global::System.Object ProviderUserKey { get { return _providerUserKey; } }
        public virtual global::System.String Email { get { return _email; } set { _email = value; } }
        public virtual global::System.String PasswordQuestion { get { return _passwordQuestion; } }
        public virtual global::System.String Comment { get { return _comment; } set { _comment = value; } }
        public virtual global::System.Boolean IsApproved { get { return _isApproved; } set { _isApproved = value; } }
        public virtual global::System.Boolean IsLockedOut { get { return _isLockedOut; } }
        public virtual global::System.DateTime LastLockoutDate { get { return _lastLockoutDate.ToLocalTime(); } }
        public virtual global::System.DateTime CreationDate { get { return _creationDate.ToLocalTime(); } }
        public virtual global::System.DateTime LastLoginDate { get { return _lastLoginDate.ToLocalTime(); } set { _lastLoginDate = value.ToUniversalTime(); } }
        public virtual global::System.DateTime LastActivityDate { get { return _lastActivityDate.ToLocalTime(); } set { _lastActivityDate = value.ToUniversalTime(); } }
        public virtual global::System.DateTime LastPasswordChangedDate { get { return _lastPasswordChangedDate.ToLocalTime(); } }
        public virtual global::System.String ProviderName { get { return _providerName; } }

        // Internal setters used by the in-memory provider to mutate state it owns.
        internal void SetIsLockedOut(global::System.Boolean value) { _isLockedOut = value; }
        internal void SetLastLockoutDate(global::System.DateTime value) { _lastLockoutDate = value.ToUniversalTime(); }
        internal void SetLastPasswordChangedDate(global::System.DateTime value) { _lastPasswordChangedDate = value.ToUniversalTime(); }
    }

    public sealed class MembershipUserCollection : global::System.Collections.IEnumerable
    {
        private readonly global::System.Collections.Hashtable _indices;
        private readonly global::System.Collections.ArrayList _values;
        private global::System.Boolean _readOnly;

        public MembershipUserCollection()
        {
            _indices = new global::System.Collections.Hashtable(10, global::System.StringComparer.OrdinalIgnoreCase);
            _values = new global::System.Collections.ArrayList();
        }
        public void Add(global::System.Web.Security.MembershipUser user)
        {
            if (user == null) { throw new global::System.ArgumentNullException("user"); }
            if (_readOnly) { throw new global::System.NotSupportedException(); }
            if (_indices[user.UserName] != null) { throw new global::System.ArgumentException("A user with this name already exists.", "user"); }
            int pos = _values.Add(user);
            _indices[user.UserName] = pos;
        }
        public void Remove(global::System.String name)
        {
            if (_readOnly) { throw new global::System.NotSupportedException(); }
            global::System.Object boxed = _indices[name];
            if (boxed == null) { return; }
            int pos = (int)boxed;
            _values.RemoveAt(pos);
            _indices.Clear();
            for (int i = 0; i < _values.Count; i++)
            {
                global::System.Web.Security.MembershipUser u = (global::System.Web.Security.MembershipUser)_values[i];
                _indices[u.UserName] = i;
            }
        }
        public global::System.Web.Security.MembershipUser this[global::System.String name]
        {
            get
            {
                global::System.Object boxed = _indices[name];
                if (boxed == null) { return null; }
                return (global::System.Web.Security.MembershipUser)_values[(int)boxed];
            }
        }
        public global::System.Int32 Count { get { return _values.Count; } }
        public global::System.Collections.IEnumerator GetEnumerator() { return _values.GetEnumerator(); }
        public void CopyTo(global::System.Web.Security.MembershipUser[] array, global::System.Int32 index)
        {
            _values.CopyTo(array, index);
        }
        public void Clear()
        {
            if (_readOnly) { throw new global::System.NotSupportedException(); }
            _values.Clear();
            _indices.Clear();
        }
        public void SetReadOnly() { _readOnly = true; }
    }

    public abstract class MembershipProvider : global::System.Configuration.Provider.ProviderBase
    {
        protected MembershipProvider() { }

        public abstract global::System.String ApplicationName { get; set; }
        public abstract global::System.Boolean EnablePasswordRetrieval { get; }
        public abstract global::System.Boolean EnablePasswordReset { get; }
        public abstract global::System.Boolean RequiresQuestionAndAnswer { get; }
        public abstract global::System.Boolean RequiresUniqueEmail { get; }
        public abstract global::System.Int32 MaxInvalidPasswordAttempts { get; }
        public abstract global::System.Int32 PasswordAttemptWindow { get; }
        public abstract global::System.Int32 MinRequiredPasswordLength { get; }
        public abstract global::System.Int32 MinRequiredNonAlphanumericCharacters { get; }
        public abstract global::System.String PasswordStrengthRegularExpression { get; }
        public abstract global::System.Web.Security.MembershipPasswordFormat PasswordFormat { get; }

        public abstract global::System.Web.Security.MembershipUser CreateUser(global::System.String username, global::System.String password, global::System.String email, global::System.String passwordQuestion, global::System.String passwordAnswer, global::System.Boolean isApproved, global::System.Object providerUserKey, out global::System.Web.Security.MembershipCreateStatus status);
        public abstract global::System.Boolean ChangePasswordQuestionAndAnswer(global::System.String username, global::System.String password, global::System.String newPasswordQuestion, global::System.String newPasswordAnswer);
        public abstract global::System.String GetPassword(global::System.String username, global::System.String answer);
        public abstract global::System.Boolean ChangePassword(global::System.String username, global::System.String oldPassword, global::System.String newPassword);
        public abstract global::System.String ResetPassword(global::System.String username, global::System.String answer);
        public abstract void UpdateUser(global::System.Web.Security.MembershipUser user);
        public abstract global::System.Boolean ValidateUser(global::System.String username, global::System.String password);
        public abstract global::System.Boolean UnlockUser(global::System.String userName);
        public abstract global::System.Web.Security.MembershipUser GetUser(global::System.Object providerUserKey, global::System.Boolean userIsOnline);
        public abstract global::System.Web.Security.MembershipUser GetUser(global::System.String username, global::System.Boolean userIsOnline);
        public abstract global::System.String GetUserNameByEmail(global::System.String email);
        public abstract global::System.Boolean DeleteUser(global::System.String username, global::System.Boolean deleteAllRelatedData);
        public abstract global::System.Web.Security.MembershipUserCollection GetAllUsers(global::System.Int32 pageIndex, global::System.Int32 pageSize, out global::System.Int32 totalRecords);
        public abstract global::System.Int32 GetNumberOfUsersOnline();
        public abstract global::System.Web.Security.MembershipUserCollection FindUsersByName(global::System.String usernameToMatch, global::System.Int32 pageIndex, global::System.Int32 pageSize, out global::System.Int32 totalRecords);
        public abstract global::System.Web.Security.MembershipUserCollection FindUsersByEmail(global::System.String emailToMatch, global::System.Int32 pageIndex, global::System.Int32 pageSize, out global::System.Int32 totalRecords);
    }

    public sealed class MembershipProviderCollection : global::System.Configuration.Provider.ProviderCollection
    {
        public MembershipProviderCollection() { }
        public new global::System.Web.Security.MembershipProvider this[global::System.String name] { get { throw new global::System.NotImplementedException(); } }
        public void CopyTo(global::System.Web.Security.MembershipProvider[] array, global::System.Int32 index) { throw new global::System.NotImplementedException(); }
    }

    public sealed class ValidatePasswordEventArgs : global::System.EventArgs
    {
        public ValidatePasswordEventArgs(global::System.String userName, global::System.String password, global::System.Boolean isNewUser) { throw new global::System.NotImplementedException(); }
        public global::System.String UserName { get { throw new global::System.NotImplementedException(); } }
        public global::System.String Password { get { throw new global::System.NotImplementedException(); } }
        public global::System.Boolean IsNewUser { get { throw new global::System.NotImplementedException(); } }
        public global::System.Boolean Cancel { get { throw new global::System.NotImplementedException(); } set { throw new global::System.NotImplementedException(); } }
        public global::System.Exception FailureInformation { get { throw new global::System.NotImplementedException(); } set { throw new global::System.NotImplementedException(); } }
    }

    public delegate void MembershipValidatePasswordEventHandler(global::System.Object sender, global::System.Web.Security.ValidatePasswordEventArgs e);

    public abstract class RoleProvider : global::System.Configuration.Provider.ProviderBase
    {
        protected RoleProvider() { }

        public abstract global::System.String ApplicationName { get; set; }
        public abstract global::System.Boolean IsUserInRole(global::System.String username, global::System.String roleName);
        public abstract global::System.String[] GetRolesForUser(global::System.String username);
        public abstract void CreateRole(global::System.String roleName);
        public abstract global::System.Boolean DeleteRole(global::System.String roleName, global::System.Boolean throwOnPopulatedRole);
        public abstract global::System.Boolean RoleExists(global::System.String roleName);
        public abstract void AddUsersToRoles(global::System.String[] usernames, global::System.String[] roleNames);
        public abstract void RemoveUsersFromRoles(global::System.String[] usernames, global::System.String[] roleNames);
        public abstract global::System.String[] GetUsersInRole(global::System.String roleName);
        public abstract global::System.String[] GetAllRoles();
        public abstract global::System.String[] FindUsersInRole(global::System.String roleName, global::System.String usernameToMatch);
    }
}
